--
-- INFI_TB_018_VEHICULOS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_018_VEHICULOS
(
  VEHICU_ID                 VARCHAR2(25 BYTE)   NOT NULL,
  VEHICU_NOMBRE             VARCHAR2(50 BYTE)   NOT NULL,
  VEHICU_RIF                VARCHAR2(11 BYTE)   NOT NULL,
  VEHICU_SIGLAS             VARCHAR2(4 BYTE)    NOT NULL,
  VEHICU_NUMERO_CUENTA      VARCHAR2(20 BYTE),
  VEHICU_BRANCH             VARCHAR2(2 BYTE),
  VEHICU_NUMERO_CUENTA_BCV  VARCHAR2(20 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_018_VEHICULOS IS 'Permite definir los atributos relacionados a los Vehiculos del Banco.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_018_VEHICULOS.VEHICU_ID IS 'Id del vehículo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_018_VEHICULOS.VEHICU_NOMBRE IS 'Nombre del vehículo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_018_VEHICULOS.VEHICU_RIF IS 'Rif del vehículo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_018_VEHICULOS.VEHICU_SIGLAS IS 'Siglas del vehículo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_018_VEHICULOS.VEHICU_NUMERO_CUENTA IS 'Número de cuenta del vehículo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_018_VEHICULOS.VEHICU_BRANCH IS 'Id de branch relacionado a OPICS';

COMMENT ON COLUMN ADM_INFI.INFI_TB_018_VEHICULOS.VEHICU_NUMERO_CUENTA_BCV IS 'Número de cuenta del Banco Central de Venezuela asociado al vehículo';

--
-- PK_018  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_018 ON ADM_INFI.INFI_TB_018_VEHICULOS
(VEHICU_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_018_VEHICULOS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_018_VEHICULOS FOR ADM_INFI.INFI_TB_018_VEHICULOS;

GRANT DELETE ON  ADM_INFI.INFI_TB_018_VEHICULOS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_018_VEHICULOS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_018_VEHICULOS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_018_VEHICULOS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_018_VEHICULOS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_018_VEHICULOS ADD (
  CONSTRAINT PK_018
 PRIMARY KEY
 (VEHICU_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


