--
-- INFI_TB_031_VEHICULO_ROL  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_031_VEHICULO_ROL
(
  VEHICU_ROL_TOMADOR     VARCHAR2(25 BYTE)      NOT NULL,
  VEHICU_ROL_COLOCADOR   VARCHAR2(25 BYTE)      NOT NULL,
  VEHICU_ROL_RECOMPRA    VARCHAR2(25 BYTE)      NOT NULL,
  VEHICU_ROL_IN_DEFECTO  NUMBER(1)              NOT NULL,
  VEHICU_ROL_ID          NUMBER(4)              NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_031_VEHICULO_ROL IS 'Tabla que indica la combinación de vehículos según el rol que cumplen. Cuando un vehículo actua como tomador, otro puede ser el colocador y otro el de recompra';

COMMENT ON COLUMN ADM_INFI.INFI_TB_031_VEHICULO_ROL.VEHICU_ROL_TOMADOR IS 'Id del vehículo que actua como tomador';

COMMENT ON COLUMN ADM_INFI.INFI_TB_031_VEHICULO_ROL.VEHICU_ROL_COLOCADOR IS 'Id del vehículo que actua como colocador';

COMMENT ON COLUMN ADM_INFI.INFI_TB_031_VEHICULO_ROL.VEHICU_ROL_RECOMPRA IS 'Id del vehículo que actua como recomprador';

COMMENT ON COLUMN ADM_INFI.INFI_TB_031_VEHICULO_ROL.VEHICU_ROL_IN_DEFECTO IS 'Indica cuál es el vehículo tomador por defecto cuando el usuario no tiene la permisología adecuada para cambiarlo en la toma de una orden. 1=por defecto';

COMMENT ON COLUMN ADM_INFI.INFI_TB_031_VEHICULO_ROL.VEHICU_ROL_ID IS 'Id del campo';

--
-- INFI_TB_031_VEHICULO_ROL  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_031_VEHICULO_ROL FOR ADM_INFI.INFI_TB_031_VEHICULO_ROL;

GRANT DELETE ON  ADM_INFI.INFI_TB_031_VEHICULO_ROL TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_031_VEHICULO_ROL TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_031_VEHICULO_ROL TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_031_VEHICULO_ROL TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_031_VEHICULO_ROL 
-- 
ALTER TABLE ADM_INFI.INFI_TB_031_VEHICULO_ROL ADD (
  CONSTRAINT CHK_031_1
 CHECK (VEHICU_ROL_IN_DEFECTO IN (0,1)));


-- 
-- Foreign Key Constraints for Table INFI_TB_031_VEHICULO_ROL 
-- 
ALTER TABLE ADM_INFI.INFI_TB_031_VEHICULO_ROL ADD (
  CONSTRAINT FK_031_018_3 
 FOREIGN KEY (VEHICU_ROL_RECOMPRA) 
 REFERENCES ADM_INFI.INFI_TB_018_VEHICULOS (VEHICU_ID));

ALTER TABLE ADM_INFI.INFI_TB_031_VEHICULO_ROL ADD (
  CONSTRAINT FK_031_018_1 
 FOREIGN KEY (VEHICU_ROL_TOMADOR) 
 REFERENCES ADM_INFI.INFI_TB_018_VEHICULOS (VEHICU_ID));

ALTER TABLE ADM_INFI.INFI_TB_031_VEHICULO_ROL ADD (
  CONSTRAINT FK_031_018_2 
 FOREIGN KEY (VEHICU_ROL_COLOCADOR) 
 REFERENCES ADM_INFI.INFI_TB_018_VEHICULOS (VEHICU_ID));


