--
-- INFI_TB_236_MESA_CAMBIO  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_236_MESA_CAMBIO
(
  ID_OPER        VARCHAR2(12 BYTE),
  OPERACION      VARCHAR2(6 BYTE),
  RIF_CLIENTE    VARCHAR2(12 BYTE),
  NOM_CLIEN      VARCHAR2(31 BYTE),
  COD_DIVISAS    VARCHAR2(3 BYTE),
  MTO_DIVISAS    NUMBER(13,2),
  TASA_CAMBIO    FLOAT(126),
  COD_INS_BANCO  VARCHAR2(5 BYTE),
  CTA_CONVENIO   VARCHAR2(20 BYTE),
  CTA_CLIEN      VARCHAR2(20 BYTE),
  FECH_OPER      VARCHAR2(10 BYTE),
  STATUS_ENVIO   VARCHAR2(5 BYTE),
  OBSERVACION    VARCHAR2(150 BYTE),
  ID_BCV         VARCHAR2(40 BYTE),
  ID_PACTO       VARCHAR2(40 BYTE),
  INSTRUMENTO    VARCHAR2(30 BYTE),
  MTO_PACTO      NUMBER
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- INFI_TB_236_MESA_CAMBIO  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_236_MESA_CAMBIO FOR ADM_INFI.INFI_TB_236_MESA_CAMBIO;

GRANT DELETE ON  ADM_INFI.INFI_TB_236_MESA_CAMBIO TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_236_MESA_CAMBIO TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_236_MESA_CAMBIO TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_236_MESA_CAMBIO TO USU_INFI;

