--
-- INFI_TB_013_TRN_STATUS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_013_TRN_STATUS
(
  TRNSTA_ID           VARCHAR2(25 BYTE)         NOT NULL,
  TRNSTA_DESCRIPCION  VARCHAR2(200 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_013_TRN_STATUS IS 'Define los diferentes status que puede tener una transaccion.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_013_TRN_STATUS.TRNSTA_ID IS 'Id de la transacción';

COMMENT ON COLUMN ADM_INFI.INFI_TB_013_TRN_STATUS.TRNSTA_DESCRIPCION IS 'Descripción de la transacción';

--
-- PK_013  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_013 ON ADM_INFI.INFI_TB_013_TRN_STATUS
(TRNSTA_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_013_TRN_STATUS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_013_TRN_STATUS FOR ADM_INFI.INFI_TB_013_TRN_STATUS;

GRANT DELETE ON  ADM_INFI.INFI_TB_013_TRN_STATUS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_013_TRN_STATUS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_013_TRN_STATUS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_013_TRN_STATUS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_013_TRN_STATUS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_013_TRN_STATUS ADD (
  CONSTRAINT PK_013
 PRIMARY KEY
 (TRNSTA_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


