--
-- INFI_TB_Z51_TITULOS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_Z51_TITULOS
(
  Z51_TITULO_ID          VARCHAR2(25 BYTE),
  Z51_ISIN               VARCHAR2(25 BYTE),
  Z51_FE_EMISION         VARCHAR2(20 BYTE),
  Z51_FE_VENCIMIENTO     VARCHAR2(20 BYTE),
  Z51_FE_CUPON_PROX      VARCHAR2(20 BYTE),
  Z51_FE_CUPON_ULT       VARCHAR2(20 BYTE),
  Z51_FE_AMORT_PROX      VARCHAR2(20 BYTE),
  Z51_FE_AMORT_ULT       VARCHAR2(20 BYTE),
  Z51_MONEDA_DEN         VARCHAR2(3 BYTE),
  Z51_MONEDA_NEG         VARCHAR2(3 BYTE),
  Z51_VALOR_NOMINAL      VARCHAR2(12 BYTE),
  Z51_CLIENTE            VARCHAR2(50 BYTE),
  Z51_MONTO_ADJUDICADO   VARCHAR2(12 BYTE),
  Z51_FE_INGRESO_CUSTOD  VARCHAR2(20 BYTE),
  Z51_CEDRIF_CLIENTE     VARCHAR2(15 BYTE),
  Z51_NRO_DEAL           VARCHAR2(200 BYTE),
  Z51_BLOQUEO            VARCHAR2(20 BYTE),
  Z51_VEHICULO           VARCHAR2(50 BYTE),
  Z51_MONTO_VENDIDO      VARCHAR2(12 BYTE),
  Z51_FECHA_VENTA        VARCHAR2(20 BYTE),
  Z51_EN_CARMEN          VARCHAR2(30 BYTE),
  Z51_TRANSF_TIPO        VARCHAR2(20 BYTE),
  Z51_CONTRAPARTE        VARCHAR2(200 BYTE),
  Z51_COMENTARIOS        VARCHAR2(200 BYTE),
  Z51_CLIENTE_POR_DEAL   VARCHAR2(50 BYTE),
  Z51_ESTATUS            NUMBER(10),
  Z51_MENSAJE_ESTATUS    VARCHAR2(500 BYTE),
  Z51_TIPO_PRODUCTO_ID   VARCHAR2(10 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_Z51_TITULOS IS 'Tabla Temporal para carga de Titulos desde las Hojas Excel';

COMMENT ON COLUMN ADM_INFI.INFI_TB_Z51_TITULOS.Z51_ESTATUS IS 'Indica si el registro ha sido grabado en las tablas correspondientes de INFI. 1 : Grabado, 0 : No Grabado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_Z51_TITULOS.Z51_MENSAJE_ESTATUS IS 'Comentario sobre el estatus del registro. En Caso de que no haya sido grabado, describe cual problema ocurrió';

--
-- INFI_TB_Z51_TITULOS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_Z51_TITULOS FOR ADM_INFI.INFI_TB_Z51_TITULOS;

GRANT DELETE ON  ADM_INFI.INFI_TB_Z51_TITULOS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_Z51_TITULOS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_Z51_TITULOS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_Z51_TITULOS TO USU_INFI;

