--
-- INFI_TB_705_TITULOS_BLOQ_HIST  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_705_TITULOS_BLOQ_HIST
(
  TITULO_ID         VARCHAR2(25 BYTE)           NOT NULL,
  CLIENT_ID         NUMBER(8)                   NOT NULL,
  TIPBLO_ID         VARCHAR2(25 BYTE)           NOT NULL,
  BENEFICIARIO_ID   NUMBER(3)                   NOT NULL,
  TITCUS_CANTIDAD   NUMBER(12)                  NOT NULL,
  FECHA             DATE                        NOT NULL,
  NUMERO_GARANTIA   VARCHAR2(20 BYTE),
  TASA_CAMBIO       NUMBER(15,6),
  TIPO_PRODUCTO_ID  VARCHAR2(10 BYTE)           NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ADM_INFI.INFI_TB_705_TITULOS_BLOQ_HIST.TIPO_PRODUCTO_ID IS 'Tipo de producto asociado';

--
-- INX_705_TPF  (Index) 
--
CREATE INDEX ADM_INFI.INX_705_TPF ON ADM_INFI.INFI_TB_705_TITULOS_BLOQ_HIST
(CLIENT_ID, TITULO_ID, FECHA, TIPO_PRODUCTO_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_705_TITULOS_BLOQ_HIST  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_705_TITULOS_BLOQ_HIST FOR ADM_INFI.INFI_TB_705_TITULOS_BLOQ_HIST;

GRANT DELETE ON  ADM_INFI.INFI_TB_705_TITULOS_BLOQ_HIST TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_705_TITULOS_BLOQ_HIST TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_705_TITULOS_BLOQ_HIST TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_705_TITULOS_BLOQ_HIST TO USU_INFI;

