--
-- INFI_TB_706_FECHAS_CIERRE  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_706_FECHAS_CIERRE
(
  FECHA_CIERRE_ANTERIOR  DATE                   NOT NULL,
  FECHA_CIERRE_PROXIMO   DATE                   NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_706_FECHAS_CIERRE IS 'Tabla que contiene el próximo mes que debe cerrarse pra el cálculo de comisiones a clientes por títulos en custodia';

COMMENT ON COLUMN ADM_INFI.INFI_TB_706_FECHAS_CIERRE.FECHA_CIERRE_ANTERIOR IS 'Fecha con el mes anterior de cierre. Sirve para buscar las ordenes desde esa fecha hasta la fecha del próximo cierre';

COMMENT ON COLUMN ADM_INFI.INFI_TB_706_FECHAS_CIERRE.FECHA_CIERRE_PROXIMO IS 'Fecha con el próximo cierre del mes';

--
-- INFI_TB_706_FECHAS_CIERRE  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_706_FECHAS_CIERRE FOR ADM_INFI.INFI_TB_706_FECHAS_CIERRE;

GRANT DELETE ON  ADM_INFI.INFI_TB_706_FECHAS_CIERRE TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_706_FECHAS_CIERRE TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_706_FECHAS_CIERRE TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_706_FECHAS_CIERRE TO USU_INFI;

