--
-- INFI_TB_019_TIPO_DE_PRODUCTO  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO
(
  TIPO_PRODUCTO_ID  VARCHAR2(10 BYTE),
  NOMBRE            VARCHAR2(30 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO IS 'Tabla que contiene los diferentes tipos de producto';

COMMENT ON COLUMN ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO.TIPO_PRODUCTO_ID IS 'Id del tipo de producto';

COMMENT ON COLUMN ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO.NOMBRE IS 'Nombre o descripción del producto';

--
-- PK_019  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_019 ON ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO
(TIPO_PRODUCTO_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_019_TIPO_DE_PRODUCTO  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_019_TIPO_DE_PRODUCTO FOR ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO;

GRANT DELETE ON  ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_019_TIPO_DE_PRODUCTO 
-- 
ALTER TABLE ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO ADD (
  CONSTRAINT PK_019
 PRIMARY KEY
 (TIPO_PRODUCTO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


