--
-- INFI_TB_800_TRN_FINANCIERAS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_800_TRN_FINANCIERAS
(
  TRNFIN_ID                VARCHAR2(6 BYTE)     NOT NULL,
  TRNFIN_NOMBRE            VARCHAR2(50 BYTE)    NOT NULL,
  TRNFIN_DESCRIPCION       VARCHAR2(200 BYTE),
  TRNFIN_VALOR             NUMBER(10,2)         NOT NULL,
  TRNFIN_APLICACION        VARCHAR2(1 BYTE)     NOT NULL,
  TRNFIN_TIPO              VARCHAR2(3 BYTE)     NOT NULL,
  TRNFIN_FUNCION           VARCHAR2(30 BYTE),
  TRNFIN_IN_COMISION       NUMBER               NOT NULL,
  TRNFIN_FECHA_APLICACION  DATE,
  TRNFIN_STATUS            NUMBER               NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_800_TRN_FINANCIERAS IS 'Permite definir las diferentes transacciones finacieras utilizadas por el Sistema y sus atributos relacionados.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_800_TRN_FINANCIERAS.TRNFIN_ID IS 'Id de transacción financiera';

COMMENT ON COLUMN ADM_INFI.INFI_TB_800_TRN_FINANCIERAS.TRNFIN_NOMBRE IS 'Nombre';

COMMENT ON COLUMN ADM_INFI.INFI_TB_800_TRN_FINANCIERAS.TRNFIN_DESCRIPCION IS 'Descripcion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_800_TRN_FINANCIERAS.TRNFIN_VALOR IS 'Monto fijo a cobrar o porcentaje a calcular. El valor depende del campo aplicacion que indica la accion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_800_TRN_FINANCIERAS.TRNFIN_APLICACION IS 'Indica si se calcula por monto fijo o por porcentaje';

COMMENT ON COLUMN ADM_INFI.INFI_TB_800_TRN_FINANCIERAS.TRNFIN_TIPO IS 'Indica si es debito, credito o miscelanea.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_800_TRN_FINANCIERAS.TRNFIN_FUNCION IS 'Clase que contiene la lógica para el cálculo del monto de la transacción No es obligatorio';

COMMENT ON COLUMN ADM_INFI.INFI_TB_800_TRN_FINANCIERAS.TRNFIN_IN_COMISION IS 'Indica si es o no una transacción financiera de comisión. 0=No, 1=Si';

COMMENT ON COLUMN ADM_INFI.INFI_TB_800_TRN_FINANCIERAS.TRNFIN_FECHA_APLICACION IS 'Fecha de comienzo para aplicar la transacción';

COMMENT ON COLUMN ADM_INFI.INFI_TB_800_TRN_FINANCIERAS.TRNFIN_STATUS IS 'Estatus de la Transacción Financiera';

--
-- PK_800  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_800 ON ADM_INFI.INFI_TB_800_TRN_FINANCIERAS
(TRNFIN_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_800_TRN_FINANCIERAS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_800_TRN_FINANCIERAS FOR ADM_INFI.INFI_TB_800_TRN_FINANCIERAS;

GRANT DELETE ON  ADM_INFI.INFI_TB_800_TRN_FINANCIERAS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_800_TRN_FINANCIERAS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_800_TRN_FINANCIERAS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_800_TRN_FINANCIERAS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_800_TRN_FINANCIERAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_800_TRN_FINANCIERAS ADD (
  CONSTRAINT PK_800
 PRIMARY KEY
 (TRNFIN_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_800_TRN_FINANCIERAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_800_TRN_FINANCIERAS ADD (
  CONSTRAINT FK_800_805 
 FOREIGN KEY (TRNFIN_TIPO) 
 REFERENCES ADM_INFI.INFI_TB_805_TRNFIN_TIPO (TRNFIN_TIPO));


