--
-- INFI_TB_224_PLANT_MAIL_AREA  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA
(
  PLANT_MAIL_AREA_ID    NUMBER(4)               NOT NULL,
  PLANT_MAIL_AREA_NAME  VARCHAR2(70 BYTE),
  DESTINATARIO          VARCHAR2(4000 BYTE)     NOT NULL,
  PLANTILLA_MAIL_ID     NUMBER(4)               NOT NULL,
  ESTATUS_ACTIVACION    NUMBER(1)               DEFAULT 1
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA IS 'Contiene los destinatarios por áreas que pueden asociarse a las plantillas de correos con TIPO_DESTINATARIO=''Funcional''';

COMMENT ON COLUMN ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA.DESTINATARIO IS 'Emails de los miembros del área';

COMMENT ON COLUMN ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA.PLANT_MAIL_AREA_NAME IS 'Nombre del area';

COMMENT ON COLUMN ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA.PLANTILLA_MAIL_ID IS 'ID de la plantilla a la que se le asocia el área';

COMMENT ON COLUMN ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA.ESTATUS_ACTIVACION IS 'Indica si se encuentran activos los envíos de correo al área';

COMMENT ON COLUMN ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA.PLANT_MAIL_AREA_ID IS 'ID del area';

--
-- INFI_TB_224_PLANT_MAIL_AREA_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA_PK ON ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA
(PLANT_MAIL_AREA_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TRG_224  (Trigger) 
--
CREATE OR REPLACE TRIGGER ADM_INFI.INFI_TRG_224
    BEFORE INSERT
    ON ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA     REFERENCING NEW AS NEW OLD AS OLD
    FOR EACH ROW
BEGIN
    -- Si no se ha indicado un ID generamos uno
    IF :NEW.PLANT_MAIL_AREA_ID IS NULL THEN
        SELECT INFI_SQ_224.NEXTVAL INTO :NEW.PLANT_MAIL_AREA_ID FROM DUAL;
    END IF;
    EXCEPTION
        WHEN OTHERS THEN RAISE;
END INFI_TRG_224;
/
SHOW ERRORS;


--
-- INFI_TB_224_PLANT_MAIL_AREA  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_224_PLANT_MAIL_AREA FOR ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA;

GRANT DELETE ON  ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_224_PLANT_MAIL_AREA TO USU_INFI;

