--
-- INFI_TB_851_EVENTO_CONTABLE  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_851_EVENTO_CONTABLE
(
  EVENTO_ID         NUMBER(10)                  NOT NULL,
  NOMBRE            VARCHAR2(50 CHAR)           NOT NULL,
  DESCRIPCION       VARCHAR2(100 CHAR),
  TRANSA_ID         VARCHAR2(25 BYTE)           NOT NULL,
  TIPO_PRODUCTO_ID  VARCHAR2(10 BYTE)           NOT NULL,
  VEHICU_ID         VARCHAR2(25 BYTE)           NOT NULL,
  ORDSTA_ID         VARCHAR2(25 BYTE),
  MONEDA            VARCHAR2(4 BYTE),
  UPD_FECHA         DATE,
  UPD_USUARIO       VARCHAR2(10 BYTE),
  AUT_FECHA         DATE,
  AUT_USUARIO       VARCHAR2(10 BYTE),
  UPD_IP            VARCHAR2(50 BYTE),
  AUT_IP            VARCHAR2(50 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_851_EVENTO_CONTABLE IS 'Tabla que contiene los datos de los eventos contables de la aplicación INFI';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.EVENTO_ID IS 'Identificador del evento contable';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.NOMBRE IS 'Nombre del evento contable';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.DESCRIPCION IS 'Descripción del evento contable';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.TRANSA_ID IS 'Transacción asociada';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.TIPO_PRODUCTO_ID IS 'Tipo de producto asociado en INFI';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.VEHICU_ID IS 'Vehículo asociado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.ORDSTA_ID IS 'Estatus de la orden al cual debe ser aplicado el evento contable (Opcional)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.MONEDA IS 'Id de moneda base de la solicitud a asociar el evento contable (opcional)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.UPD_USUARIO IS 'Usuario modificador del evento contable';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.AUT_FECHA IS 'Fecha de autorización/aprobación del evento contable';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.AUT_USUARIO IS 'Usuario autorizador/aprobador del evento contable';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.UPD_IP IS 'Ip desde donde se realizó la modificación del evento contable';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.AUT_IP IS 'Ip desde donde se realizó la autorización/aprobación del evento contable';

COMMENT ON COLUMN ADM_INFI.INFI_TB_851_EVENTO_CONTABLE.UPD_FECHA IS 'Fecha de modificación del evento contable';

--
-- INFI_TB_851_EVENTO_CONTABLE_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.INFI_TB_851_EVENTO_CONTABLE_PK ON ADM_INFI.INFI_TB_851_EVENTO_CONTABLE
(EVENTO_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_851_EVENTO_CONTABLE 
-- 
ALTER TABLE ADM_INFI.INFI_TB_851_EVENTO_CONTABLE ADD (
  CONSTRAINT INFI_TB_851_EVENTO_CONTABLE_PK
 PRIMARY KEY
 (EVENTO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_851_EVENTO_CONTABLE 
-- 
ALTER TABLE ADM_INFI.INFI_TB_851_EVENTO_CONTABLE ADD (
  CONSTRAINT FK_801_019 
 FOREIGN KEY (TIPO_PRODUCTO_ID) 
 REFERENCES ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO (TIPO_PRODUCTO_ID));

ALTER TABLE ADM_INFI.INFI_TB_851_EVENTO_CONTABLE ADD (
  CONSTRAINT FK_801_012 
 FOREIGN KEY (TRANSA_ID) 
 REFERENCES ADM_INFI.INFI_TB_012_TRANSACCIONES (TRANSA_ID));

ALTER TABLE ADM_INFI.INFI_TB_851_EVENTO_CONTABLE ADD (
  CONSTRAINT FK_801_018 
 FOREIGN KEY (VEHICU_ID) 
 REFERENCES ADM_INFI.INFI_TB_018_VEHICULOS (VEHICU_ID));


