--
-- INFI_TB_207_ORDENES_OPERACION  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_207_ORDENES_OPERACION
(
  ORDENE_ID                  NUMBER(10)         NOT NULL,
  ORDENE_OPERACION_ID        NUMBER(9)          NOT NULL,
  TRNFIN_ID                  VARCHAR2(6 BYTE),
  STATUS_OPERACION           VARCHAR2(25 BYTE)  NOT NULL,
  CTA_ORIGEN                 VARCHAR2(25 BYTE),
  CTA_DESTINO                VARCHAR2(25 BYTE),
  APLICA_REVERSO             NUMBER(1)          NOT NULL,
  MONTO_OPERACION            NUMBER(19,5)       NOT NULL,
  TASA                       NUMBER(9,6)        NOT NULL,
  FECHA_APLICAR              DATE,
  FECHA_PROCESADA            DATE,
  ORDENE_OPERACION_ERROR     VARCHAR2(500 BYTE),
  SERIAL                     VARCHAR2(20 BYTE),
  IN_COMISION                NUMBER(1),
  MONEDA_ID                  VARCHAR2(3 BYTE),
  CTECTA_NUMERO              VARCHAR2(34 BYTE),
  CTECTA_NOMBRE              VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_BCO          VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_DIRECCION    VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_SWIFT        VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_BIC          VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_TELEFONO     VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_ABA          VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_PAIS         VARCHAR2(25 BYTE),
  CTECTA_BCOINT_BCO          VARCHAR2(50 BYTE),
  CTECTA_BCOINT_DIRECCION    VARCHAR2(50 BYTE),
  CTECTA_BCOINT_SWIFT        VARCHAR2(50 BYTE),
  CTECTA_BCOINT_BIC          VARCHAR2(50 BYTE),
  CTECTA_BCOINT_TELEFONO     VARCHAR2(50 BYTE),
  CTECTA_BCOINT_ABA          VARCHAR2(50 BYTE),
  CTECTA_BCOINT_PAIS         VARCHAR2(25 BYTE),
  TRNF_TIPO                  VARCHAR2(3 BYTE),
  TITULO_ID                  VARCHAR2(25 BYTE),
  NUMERO_RETENCION           VARCHAR2(10 BYTE),
  ORDENE_RELAC_OPERACION_ID  NUMBER(9),
  CHEQUE_NUMERO              VARCHAR2(20 BYTE),
  FECHA_PAGO_CHEQUE          DATE,
  CODIGO_OPERACION           VARCHAR2(10 BYTE),
  FECHA_INICIO_CP            DATE,
  FECHA_FIN_CP               DATE,
  IN_COMISION_INVARIABLE     NUMBER(1),
  DIAS_OPERACION             NUMBER(3),
  OPERACION_NOMBRE           VARCHAR2(50 BYTE),
  NUMERO_MOVIMIENTO          VARCHAR2(30 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_207_ORDENES_OPERACION IS 'Permite definir los atributos de las Cuentas Internacionales a ser utilizados 
en transacciones via SWIFT.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.ORDENE_ID IS 'Id de la orden de referencia';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.ORDENE_OPERACION_ID IS 'Id de orden de operación necesario para crear la clave primaria';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.TRNFIN_ID IS 'Id de la transacción financiera involucrada.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.STATUS_OPERACION IS 'Indica el status que tiene la operación financiera. APROBADA, RECHAZADA, PENDIENTE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTA_ORIGEN IS 'Cuenta origen de referencia para la operación. Si es un débito a que cuenta se va a debitar';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTA_DESTINO IS 'Cuenta final donde debe ir el monto de la operación.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.APLICA_REVERSO IS 'Indica si a la operación financiera se le puede aplicar reverso';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.MONTO_OPERACION IS 'Monto de la operación involucrada en el proceso';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.TASA IS 'Tasa aplicada en la operación';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.FECHA_APLICAR IS 'Fecha en la que se debe aplicar la operación.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.FECHA_PROCESADA IS 'Fecha en la que se aplicó la operación.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.ORDENE_OPERACION_ERROR IS 'Contiene la descripción del error del por qué una operación no se pudo aplicar.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.SERIAL IS 'Serial contable a enviar en la transacción financiera';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.IN_COMISION IS 'Indicador para saber si la operación es (1) o no (0) una comision.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.MONEDA_ID IS 'Id de la moneda involucrada en la operación financiera';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_NUMERO IS 'Numero de Cuenta del Cliente. Aplica solo para Cuentas Internacionales. No aplica para las Cuentas de ALTAIR. Las cuentas de ALTAIR se mantienen en ALTAIR y se obtienen a través de los Servicios, al momento de ser requeridas.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_NOMBRE IS 'Nombre de Referecia de la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOCTA_BCO IS 'Nombre del Banco donde se posee la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOCTA_SWIFT IS 'Código SWIFT del Banco donde se posee la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOCTA_BIC IS 'Código BIC del Banco donde se posee la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOCTA_TELEFONO IS 'Télefono del Banco donde se posee la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOCTA_ABA IS 'Código ABA del Banco donde se posee la Cuenta. Este código solo aplica a cuentas de Bancos en EEUU.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOCTA_PAIS IS 'País de donde es la Dirección de la sucursal donde se abrió la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOINT_BCO IS 'Nombre del Banco donde que fungirá como Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOINT_DIRECCION IS 'Direccion del Banco Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOINT_SWIFT IS 'Código SWIFT del Banco Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOINT_BIC IS 'Código BIC del Banco Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOINT_TELEFONO IS 'Télefono del Banco Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOINT_ABA IS 'Código ABA del Banco Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CTECTA_BCOINT_PAIS IS 'País de donde es la Dirección del Banco Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.TRNF_TIPO IS 'Indica el tipo de transacción financiera';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.TITULO_ID IS 'Indica una determinada operación sobre un título';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.NUMERO_RETENCION IS 'Número de retención cuando la operación es de bloqueo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.ORDENE_RELAC_OPERACION_ID IS 'Indica la relación que tiene una operación con otra';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CHEQUE_NUMERO IS 'Número de cheque con que se pago la operación financiera';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.FECHA_PAGO_CHEQUE IS 'Fecha en la que se envió la actualización de la operación con cheque';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.CODIGO_OPERACION IS 'Código de operación de la transacción financiera. Aplica solo para ALTAIR';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.FECHA_INICIO_CP IS 'Fecha que indica el inicio para el cálculo de un cupón o amortización';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.FECHA_FIN_CP IS 'Fecha que indica el fin para el cálculo de un cupón o amortización';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.IN_COMISION_INVARIABLE IS 'Indicador de comisión invariable en la adjudicación';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.DIAS_OPERACION IS 'Días de cálculo para el pago de cupón o amortización';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.OPERACION_NOMBRE IS 'Descripción de la operación ejecutada';

COMMENT ON COLUMN ADM_INFI.INFI_TB_207_ORDENES_OPERACION.NUMERO_MOVIMIENTO IS 'Número de movimiento generado por ALTAIR';

--
-- INDX_207_ID_IDOPE  (Index) 
--
CREATE INDEX ADM_INFI.INDX_207_ID_IDOPE ON ADM_INFI.INFI_TB_207_ORDENES_OPERACION
(ORDENE_ID, ORDENE_OPERACION_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- PK_207  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_207 ON ADM_INFI.INFI_TB_207_ORDENES_OPERACION
(ORDENE_OPERACION_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_207_ORDENES_OPERACION  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_207_ORDENES_OPERACION FOR ADM_INFI.INFI_TB_207_ORDENES_OPERACION;

GRANT DELETE ON  ADM_INFI.INFI_TB_207_ORDENES_OPERACION TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_207_ORDENES_OPERACION TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_207_ORDENES_OPERACION TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_207_ORDENES_OPERACION TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_207_ORDENES_OPERACION 
-- 
ALTER TABLE ADM_INFI.INFI_TB_207_ORDENES_OPERACION ADD (
  CONSTRAINT PK_207
 PRIMARY KEY
 (ORDENE_OPERACION_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_207_ORDENES_OPERACION 
-- 
ALTER TABLE ADM_INFI.INFI_TB_207_ORDENES_OPERACION ADD (
  CONSTRAINT FK_207_033 
 FOREIGN KEY (STATUS_OPERACION) 
 REFERENCES ADM_INFI.INFI_TB_033_OPERACION_STATUS (STATUS_OPERACION));

ALTER TABLE ADM_INFI.INFI_TB_207_ORDENES_OPERACION ADD (
  CONSTRAINT FK_207_204 
 FOREIGN KEY (ORDENE_ID) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));


