--
-- INFI_TB_112_UI_COMISION  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_112_UI_COMISION
(
  COMISION_ID          NUMBER(7)                NOT NULL,
  UNDINV_ID            NUMBER(7)                NOT NULL,
  COMISION_NOMBRE      VARCHAR2(50 BYTE)        NOT NULL,
  COMISION_MONTO_FIJO  NUMBER(10,2),
  COMISION_PCT         NUMBER(8,4),
  CODIGO_OPERACION     VARCHAR2(10 BYTE)        NOT NULL,
  COMISION_TIPO        NUMBER(1)                DEFAULT 1                     NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_112_UI_COMISION IS 'Contiene las comisiones que deben cobrarse por unidad de inversión en una toma de orden';

COMMENT ON COLUMN ADM_INFI.INFI_TB_112_UI_COMISION.COMISION_TIPO IS 'Indica si la  comision aplica para para Electronico o Efectivo. 1 = Electronico, 2= Efectivo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_112_UI_COMISION.COMISION_ID IS 'Id que identifica de manera única un registro';

COMMENT ON COLUMN ADM_INFI.INFI_TB_112_UI_COMISION.UNDINV_ID IS 'Id de la unidad de inversión';

COMMENT ON COLUMN ADM_INFI.INFI_TB_112_UI_COMISION.COMISION_NOMBRE IS 'Nombre de la comisión';

COMMENT ON COLUMN ADM_INFI.INFI_TB_112_UI_COMISION.COMISION_MONTO_FIJO IS 'Monto fijo a cobrar';

COMMENT ON COLUMN ADM_INFI.INFI_TB_112_UI_COMISION.COMISION_PCT IS 'Porcentaje a cobrar sobre la inversión';

COMMENT ON COLUMN ADM_INFI.INFI_TB_112_UI_COMISION.CODIGO_OPERACION IS 'Código de operación que debe enviarse a ALTAIR';

--
-- PK_112  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_112 ON ADM_INFI.INFI_TB_112_UI_COMISION
(COMISION_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_112_UI_COMISION  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_112_UI_COMISION FOR ADM_INFI.INFI_TB_112_UI_COMISION;

GRANT DELETE ON  ADM_INFI.INFI_TB_112_UI_COMISION TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_112_UI_COMISION TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_112_UI_COMISION TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_112_UI_COMISION TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_112_UI_COMISION 
-- 
ALTER TABLE ADM_INFI.INFI_TB_112_UI_COMISION ADD (
  CONSTRAINT PK_112
 PRIMARY KEY
 (COMISION_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_112_UI_COMISION 
-- 
ALTER TABLE ADM_INFI.INFI_TB_112_UI_COMISION ADD (
  CONSTRAINT FK_112_106 
 FOREIGN KEY (UNDINV_ID) 
 REFERENCES ADM_INFI.INFI_TB_106_UNIDAD_INVERSION (UNDINV_ID)
    ON DELETE CASCADE);


