--
-- INFI_TB_903_REGLA_CONCEPTO  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_903_REGLA_CONCEPTO
(
  REGLA_VALIDACION_ID  NUMBER(3)                NOT NULL,
  CONCEPTO_ID          NUMBER(3)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ADM_INFI.INFI_TB_903_REGLA_CONCEPTO.REGLA_VALIDACION_ID IS 'Id de validación de regla';

COMMENT ON COLUMN ADM_INFI.INFI_TB_903_REGLA_CONCEPTO.CONCEPTO_ID IS 'Id del concepto';


--
-- INFI_TB_903_REGLA_CONCEPTO  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_903_REGLA_CONCEPTO FOR ADM_INFI.INFI_TB_903_REGLA_CONCEPTO;

GRANT DELETE ON  ADM_INFI.INFI_TB_903_REGLA_CONCEPTO TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_903_REGLA_CONCEPTO TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_903_REGLA_CONCEPTO TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_903_REGLA_CONCEPTO TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_903_REGLA_CONCEPTO 
-- 
ALTER TABLE ADM_INFI.INFI_TB_903_REGLA_CONCEPTO ADD (
  PRIMARY KEY
 (REGLA_VALIDACION_ID, CONCEPTO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


