--
-- INFI_TB_225_OFERTAS_SIMADI  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_225_OFERTAS_SIMADI
(
  ID_OFERTA              NUMBER(10),
  ORDENE_ID_BCV          VARCHAR2(20 BYTE),
  ORDENE_ESTATUS_BCV     NUMBER(1),
  CLIENT_CEDRIF          NUMBER(10),
  TIPPER_ID              VARCHAR2(1 BYTE),
  CLIENT_NOMBRE          VARCHAR2(100 BYTE),
  ORDENE_MONTO_OFERTADO  NUMBER(15,4),
  ORDENE_TASA_CAMBIO     NUMBER(15,6),
  NRO_JORNADA            VARCHAR2(20 BYTE),
  COD_INSTITUCION        NUMBER(10),
  ESTATUS_CRUCE          VARCHAR2(25 BYTE)      DEFAULT 'SIN PROCESAR',
  DEALNO                 VARCHAR2(8 BYTE),
  FECHA_PACTO            DATE,
  OBSERVACION            VARCHAR2(1000 BYTE),
  FECHA_REGISTRO         DATE,
  FECHA_VALOR            DATE,
  ID_PRODUCTO            VARCHAR2(10 BYTE),
  ID_SUB_PRODUCTO        VARCHAR2(10 BYTE),
  ORIGEN                 NUMBER(1)              DEFAULT 0
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_225_OFERTAS_SIMADI IS 'TABLA QUE CONTIENE LAS OFERTAS CARGADAS DESDE LA APLICACION OPICS A SER NOTIFICADAS AL BCV';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.ID_OFERTA IS 'IDENTIFICADOR INTERNO DE LA OFERTA';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.ORDENE_ID_BCV IS 'IDENTIFICADOR ENVIADO POR EL BCV ASOCIADO A LA OFERTA';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.ORDENE_ESTATUS_BCV IS 'ESTATUS DEL PROCESO DE VERIFICACION VIA WEB SERVICE CON EL BCV DE LA OFERTA';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.CLIENT_CEDRIF IS 'NUMERO DE CEDULA O RIF DEL CLIENTE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.TIPPER_ID IS 'TIPO DE PERSONA ASOCIADO AL CLIENTE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.CLIENT_NOMBRE IS 'NOMBRE DEL CLIENTE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.ORDENE_MONTO_OFERTADO IS 'MONTO DE LA OFERTA';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.ORDENE_TASA_CAMBIO IS 'TASA DE CAMBIO DE LA OFERTA OFERTADO';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.NRO_JORNADA IS 'NUMERO IDENTIFICADOR DE LA JORNADA ACTIVA';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.COD_INSTITUCION IS 'NUMERO IDENTIFICADOR DE LA ORDEN REGISTRADA EN LA APLICACION';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.ESTATUS_CRUCE IS 'ESTATUS DE LA OFERTA EN EL PROCESO DE CRUCE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.DEALNO IS 'IDENTIFICADOR DEL NUMERO DE DEAL DE LA APLICACION OPICS';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.FECHA_PACTO IS 'FECHA EN LA QUE SE TOMA LA ORDEN';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.OBSERVACION IS 'OBSERVACION DE LA ORDEN';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.FECHA_REGISTRO IS 'FECHA DE REGISTRO DEL DEAL';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.FECHA_VALOR IS 'FECHA VALOR DE LA OPERACION';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.ID_PRODUCTO IS 'ID DE PRODUCTO EN OPICS';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.ID_SUB_PRODUCTO IS 'ID DE SUBPRODUCTO EN OPICS';

COMMENT ON COLUMN ADM_INFI.INFI_TB_225_OFERTAS_SIMADI.ORIGEN IS 'Origen de la Oferta. 0= Banco de Venezuela (ANTES DEL DESARROLLO DEFINITIVO DE LA OFERTA, LUEGO DE ESTO QUEDA EN DESUSO), 1= Banco Central  de Venezuela o Interbancario, 2= Banco de Venezuela Fondos Anticipados';


--
-- IDX_FECHA_PACTO  (Index) 
--
CREATE INDEX ADM_INFI.IDX_FECHA_PACTO ON ADM_INFI.INFI_TB_225_OFERTAS_SIMADI
(FECHA_PACTO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- IDX_ORDENE_TASA_CAMBIO  (Index) 
--
CREATE INDEX ADM_INFI.IDX_ORDENE_TASA_CAMBIO ON ADM_INFI.INFI_TB_225_OFERTAS_SIMADI
(ORDENE_TASA_CAMBIO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- IDX_ORDENE_MONTO_OFERTADO  (Index) 
--
CREATE INDEX ADM_INFI.IDX_ORDENE_MONTO_OFERTADO ON ADM_INFI.INFI_TB_225_OFERTAS_SIMADI
(ORDENE_MONTO_OFERTADO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- IDX_CLIENT_CEDRIF  (Index) 
--
CREATE INDEX ADM_INFI.IDX_CLIENT_CEDRIF ON ADM_INFI.INFI_TB_225_OFERTAS_SIMADI
(CLIENT_CEDRIF)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- IDX_ORIGEN  (Index) 
--
CREATE INDEX ADM_INFI.IDX_ORIGEN ON ADM_INFI.INFI_TB_225_OFERTAS_SIMADI
(ORIGEN)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- IDX_ORDENE_ESTATUS_BCV  (Index) 
--
CREATE INDEX ADM_INFI.IDX_ORDENE_ESTATUS_BCV ON ADM_INFI.INFI_TB_225_OFERTAS_SIMADI
(ORDENE_ESTATUS_BCV)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_225_OFERTAS_SIMADI  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_225_OFERTAS_SIMADI FOR ADM_INFI.INFI_TB_225_OFERTAS_SIMADI;

GRANT DELETE ON  ADM_INFI.INFI_TB_225_OFERTAS_SIMADI TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_225_OFERTAS_SIMADI TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_225_OFERTAS_SIMADI TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_225_OFERTAS_SIMADI TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_225_OFERTAS_SIMADI 
-- 
ALTER TABLE ADM_INFI.INFI_TB_225_OFERTAS_SIMADI ADD (
  PRIMARY KEY
 (ID_OFERTA)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


