--
-- INFI_TB_233_ANULACION_CONV36  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_233_ANULACION_CONV36
(
  ID_OPER                      VARCHAR2(12 BYTE),
  ID_ORDEN_BCV                 VARCHAR2(20 BYTE),
  RIF_OPERADOR_TURISTICO       VARCHAR2(20 BYTE),
  NUMERO_PASAPORTE_TURISTA     VARCHAR2(11 BYTE),
  RAZON_SOCIAL_OPER_TURIS      VARCHAR2(50 BYTE),
  NOMBRE_TURISTA               VARCHAR2(50 BYTE),
  TASA_CAMBIO_OPERACION        NUMBER(11,5)     DEFAULT 0,
  CODIGO_DIVISA_ORIGEN         VARCHAR2(3 BYTE),
  MONTO_DIVISAS                NUMBER(13,2)     DEFAULT 0,
  CUENTA_BOLIVARES             VARCHAR2(20 BYTE),
  CUENTA_DIVISAS               VARCHAR2(20 BYTE),
  ESTATUS_ANULACION            VARCHAR2(30 BYTE),
  FECHA_OPERACION              DATE,
  FECHA_VENCIMIENTO_OPERACION  DATE,
  FECHA_ANULACION              DATE,
  MOTIVO_ANULACION             VARCHAR2(50 BYTE),
  CODIGO_ANULACION_BCV         VARCHAR2(20 BYTE),
  ESTATUS_MONEDA_EXTRANJERA    VARCHAR2(2 BYTE),
  OBSERVACION                  VARCHAR2(100 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.RIF_OPERADOR_TURISTICO IS 'Rif del operador turistico que realiza la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.RAZON_SOCIAL_OPER_TURIS IS 'Razon social del operador turistico que realiza la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.NUMERO_PASAPORTE_TURISTA IS 'Numero de pasaporte del turista';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.NOMBRE_TURISTA IS 'Nombre del turista';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.TASA_CAMBIO_OPERACION IS 'Tasa de Cambio a la que se realiza la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.CODIGO_DIVISA_ORIGEN IS 'Codigo de la moneda de origen de la transaccion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.MONTO_DIVISAS IS 'Monto de la operacion en Divisas';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.CUENTA_BOLIVARES IS 'Numero de cuenta en bolivares del operador turistico';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.CUENTA_DIVISAS IS 'Numero de cuenta en divisa del operador turistico';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.ESTATUS_ANULACION IS 'Estatus del proceso de anulacion de la orden ante el BCV';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.FECHA_OPERACION IS 'Fecha en la que se realizo la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.FECHA_VENCIMIENTO_OPERACION IS 'Fecha en la que se vencio la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.FECHA_ANULACION IS 'Fecha en la que se realizo el prceso de anulacion de la operacion ante el BCV';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.MOTIVO_ANULACION IS 'Motivo por el cual se anula la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.ESTATUS_MONEDA_EXTRANJERA IS 'Estatus manejado por la aplicacion de Moneda extranjera del proceso de anulacion de la operacion 00 Sin procesar, 01 Anulada por BCV,02 Anulacion Rechazada por el BCV';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.OBSERVACION IS 'Observacion asociada al proceso de anulacion de la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.CODIGO_ANULACION_BCV IS 'Codigo de anulacion suministrado por el BCV';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.ID_OPER IS 'Identificador unico de la orden registrada en Moneda Extranjera';

COMMENT ON COLUMN ADM_INFI.INFI_TB_233_ANULACION_CONV36.ID_ORDEN_BCV IS 'Identificador unico suministrado por el Banco Central de Venezuela asociado la orden de convenio 36';


--
-- IDX_FECHA_VENC_ESTATUS_ME  (Index) 
--
CREATE INDEX ADM_INFI.IDX_FECHA_VENC_ESTATUS_ME ON ADM_INFI.INFI_TB_233_ANULACION_CONV36
(ESTATUS_MONEDA_EXTRANJERA, FECHA_VENCIMIENTO_OPERACION)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_233_ANULACION_CONV36  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_233_ANULACION_CONV36 FOR ADM_INFI.INFI_TB_233_ANULACION_CONV36;

GRANT DELETE ON  ADM_INFI.INFI_TB_233_ANULACION_CONV36 TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_233_ANULACION_CONV36 TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_233_ANULACION_CONV36 TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_233_ANULACION_CONV36 TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_233_ANULACION_CONV36 
-- 
ALTER TABLE ADM_INFI.INFI_TB_233_ANULACION_CONV36 ADD (
  PRIMARY KEY
 (ID_OPER)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


