--
-- INFI_TB_046_FECHA_VALOR  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_046_FECHA_VALOR
(
  FECHA_VALOR_ID      NUMBER(2),
  FECHA_VALOR_NOMBRE  VARCHAR2(50 BYTE),
  FECHA_VALOR         DATE
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ADM_INFI.INFI_TB_046_FECHA_VALOR.FECHA_VALOR_ID IS 'Id de la fecha valor';

COMMENT ON COLUMN ADM_INFI.INFI_TB_046_FECHA_VALOR.FECHA_VALOR_NOMBRE IS 'Nombre o descripción de fecha valor';

COMMENT ON COLUMN ADM_INFI.INFI_TB_046_FECHA_VALOR.FECHA_VALOR IS 'Fecha valor a tomar por los procesos';

--
-- PK_046  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_046 ON ADM_INFI.INFI_TB_046_FECHA_VALOR
(FECHA_VALOR_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_046_FECHA_VALOR  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_046_FECHA_VALOR FOR ADM_INFI.INFI_TB_046_FECHA_VALOR;

GRANT DELETE ON  ADM_INFI.INFI_TB_046_FECHA_VALOR TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_046_FECHA_VALOR TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_046_FECHA_VALOR TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_046_FECHA_VALOR TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_046_FECHA_VALOR 
-- 
ALTER TABLE ADM_INFI.INFI_TB_046_FECHA_VALOR ADD (
  CONSTRAINT PK_046
 PRIMARY KEY
 (FECHA_VALOR_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


