--
-- INFI_TB_104_BLOTER_USUARIOS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_104_BLOTER_USUARIOS
(
  BLOTER_ID  VARCHAR2(25 BYTE)                  NOT NULL,
  USERID     VARCHAR2(25 BYTE)                  NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_104_BLOTER_USUARIOS IS 'Permite definir usuarios que pueden utilizar en la toma de ordenes, aquellos Blotter 
que esten definido como Restringidos.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_104_BLOTER_USUARIOS.BLOTER_ID IS 'Id de bloter';

COMMENT ON COLUMN ADM_INFI.INFI_TB_104_BLOTER_USUARIOS.USERID IS 'Id de usuario';

--
-- PK_104  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_104 ON ADM_INFI.INFI_TB_104_BLOTER_USUARIOS
(BLOTER_ID, USERID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_104_BLOTER_USUARIOS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_104_BLOTER_USUARIOS FOR ADM_INFI.INFI_TB_104_BLOTER_USUARIOS;

GRANT DELETE ON  ADM_INFI.INFI_TB_104_BLOTER_USUARIOS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_104_BLOTER_USUARIOS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_104_BLOTER_USUARIOS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_104_BLOTER_USUARIOS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_104_BLOTER_USUARIOS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_104_BLOTER_USUARIOS ADD (
  CONSTRAINT PK_104
 PRIMARY KEY
 (BLOTER_ID, USERID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_104_BLOTER_USUARIOS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_104_BLOTER_USUARIOS ADD (
  FOREIGN KEY (BLOTER_ID) 
 REFERENCES ADM_INFI.INFI_TB_102_BLOTER (BLOTER_ID));


