--
-- INFI_TB_702_TITULOS_CIERRE  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_702_TITULOS_CIERRE
(
  TITULO_ID         VARCHAR2(25 BYTE)           NOT NULL,
  CLIENT_ID         NUMBER(8)                   NOT NULL,
  FECHA_CIERRE      DATE                        NOT NULL,
  TITCUS_CANTIDAD   NUMBER(12)                  NOT NULL,
  TASA_CAMBIO       NUMBER(15,6),
  TIPO_PRODUCTO_ID  VARCHAR2(10 BYTE)           NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_702_TITULOS_CIERRE IS 'Contiene las posiciones globales de los titulos que posee un cliente al momento de efectuar cualquier transacción que afecte su posición en custodia';

COMMENT ON COLUMN ADM_INFI.INFI_TB_702_TITULOS_CIERRE.TITULO_ID IS 'Id del título';

COMMENT ON COLUMN ADM_INFI.INFI_TB_702_TITULOS_CIERRE.CLIENT_ID IS 'Id del cliente que posee el título';

COMMENT ON COLUMN ADM_INFI.INFI_TB_702_TITULOS_CIERRE.FECHA_CIERRE IS 'Fecha en que se cerro el mes';

COMMENT ON COLUMN ADM_INFI.INFI_TB_702_TITULOS_CIERRE.TITCUS_CANTIDAD IS 'Posición global al cierre de mes';

COMMENT ON COLUMN ADM_INFI.INFI_TB_702_TITULOS_CIERRE.TIPO_PRODUCTO_ID IS 'Tipo de producto asociado';

--
-- INX_702_FECHA_CIERRE  (Index) 
--
CREATE INDEX ADM_INFI.INX_702_FECHA_CIERRE ON ADM_INFI.INFI_TB_702_TITULOS_CIERRE
(FECHA_CIERRE)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INX_702_01_FECHA_CIERRE  (Index) 
--
CREATE INDEX ADM_INFI.INX_702_01_FECHA_CIERRE ON ADM_INFI.INFI_TB_702_TITULOS_CIERRE
(CLIENT_ID, TITULO_ID, TIPO_PRODUCTO_ID, FECHA_CIERRE)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_702_TITULOS_CIERRE  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_702_TITULOS_CIERRE FOR ADM_INFI.INFI_TB_702_TITULOS_CIERRE;

GRANT DELETE ON  ADM_INFI.INFI_TB_702_TITULOS_CIERRE TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_702_TITULOS_CIERRE TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_702_TITULOS_CIERRE TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_702_TITULOS_CIERRE TO USU_INFI;

