--
-- INFI_TB_032_TRNF_FIJAS_VEHICU  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU
(
  TRNFIN_ID              NUMBER(2)              NOT NULL,
  VEHICU_ID              VARCHAR2(25 BYTE)      NOT NULL,
  COD_OPERACION_CTE_DEB  VARCHAR2(10 BYTE),
  COD_OPERACION_CTE_CRE  VARCHAR2(10 BYTE),
  COD_OPERACION_CTE_BLO  VARCHAR2(10 BYTE),
  COD_OPERACION_VEH_CRE  VARCHAR2(10 BYTE),
  COD_OPERACION_VEH_DEB  VARCHAR2(10 BYTE),
  INSFIN_ID              VARCHAR2(25 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU IS 'Contiene las transacciones invariables que INFI usa en cada proceso relacionadas a un determinado vehículo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU.TRNFIN_ID IS 'Id de la transacción';

COMMENT ON COLUMN ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU.VEHICU_ID IS 'Id del vehículo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU.INSFIN_ID IS 'Instrumento financiero relacionado';

--
-- IDX_032_TRNFIN_VEHICU_INSFIN  (Index) 
--
CREATE INDEX ADM_INFI.IDX_032_TRNFIN_VEHICU_INSFIN ON ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU
(TRNFIN_ID, VEHICU_ID, INSFIN_ID)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_032_TRNF_FIJAS_VEHICU  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_032_TRNF_FIJAS_VEHICU FOR ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU;

GRANT DELETE ON  ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU TO USU_INFI;

-- 
-- Foreign Key Constraints for Table INFI_TB_032_TRNF_FIJAS_VEHICU 
-- 
ALTER TABLE ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU ADD (
  CONSTRAINT FK_032_032_FI 
 FOREIGN KEY (TRNFIN_ID) 
 REFERENCES ADM_INFI.INFI_TB_032_TRNF_FIJAS (TRNFIN_ID));

ALTER TABLE ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU ADD (
  CONSTRAINT FK_032_018 
 FOREIGN KEY (VEHICU_ID) 
 REFERENCES ADM_INFI.INFI_TB_018_VEHICULOS (VEHICU_ID)
    ON DELETE CASCADE);

ALTER TABLE ADM_INFI.INFI_TB_032_TRNF_FIJAS_VEHICU ADD (
  CONSTRAINT FK_032_101 
 FOREIGN KEY (INSFIN_ID) 
 REFERENCES ADM_INFI.INFI_TB_101_INST_FINANCIEROS (INSFIN_ID));


