--
-- INFI_TB_700_TIPO_BLOQUEO  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_700_TIPO_BLOQUEO
(
  TIPBLO_ID           VARCHAR2(25 BYTE)         NOT NULL,
  TIPBLO_DESCRIPCION  VARCHAR2(200 BYTE),
  TIPBLO_STATUS       NUMBER(1)                 NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_700_TIPO_BLOQUEO IS 'Define los diferentes tipos de Bloqueo a los titulos en Custodia. Si un orden de Venta Masiva 
es puesta con Financiamiento, se coloca bloqueado el Titulo en forma automatica. FALTA COLOCAR EL INDICADOR 
QUE DIGA CUAL ES EL QUE SE VA A USAR.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_700_TIPO_BLOQUEO.TIPBLO_ID IS 'Id tipo de bloqueo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_700_TIPO_BLOQUEO.TIPBLO_DESCRIPCION IS 'Descripción de tipo de bloqueo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_700_TIPO_BLOQUEO.TIPBLO_STATUS IS 'Status';

--
-- PK_700  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_700 ON ADM_INFI.INFI_TB_700_TIPO_BLOQUEO
(TIPBLO_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_700_TIPO_BLOQUEO  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_700_TIPO_BLOQUEO FOR ADM_INFI.INFI_TB_700_TIPO_BLOQUEO;

GRANT DELETE ON  ADM_INFI.INFI_TB_700_TIPO_BLOQUEO TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_700_TIPO_BLOQUEO TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_700_TIPO_BLOQUEO TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_700_TIPO_BLOQUEO TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_700_TIPO_BLOQUEO 
-- 
ALTER TABLE ADM_INFI.INFI_TB_700_TIPO_BLOQUEO ADD (
  CONSTRAINT PK_700
 PRIMARY KEY
 (TIPBLO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


