--
-- INFI_TB_003_GRP_TRANSACCIONES  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_003_GRP_TRANSACCIONES
(
  GRUPO_ID    NUMBER(2)                         NOT NULL,
  DESC_GRUPO  VARCHAR2(25 BYTE)                 NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_003_GRP_TRANSACCIONES IS 'Tabla para registrar los grupos a los que puede pertenecer una transacción de negocio.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_003_GRP_TRANSACCIONES.GRUPO_ID IS 'Id de grupo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_003_GRP_TRANSACCIONES.DESC_GRUPO IS 'Descripción del grupo';

--
-- PK_003  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_003 ON ADM_INFI.INFI_TB_003_GRP_TRANSACCIONES
(GRUPO_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_003_GRP_TRANSACCIONES  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_003_GRP_TRANSACCIONES FOR ADM_INFI.INFI_TB_003_GRP_TRANSACCIONES;

GRANT DELETE ON  ADM_INFI.INFI_TB_003_GRP_TRANSACCIONES TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_003_GRP_TRANSACCIONES TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_003_GRP_TRANSACCIONES TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_003_GRP_TRANSACCIONES TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_003_GRP_TRANSACCIONES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_003_GRP_TRANSACCIONES ADD (
  CONSTRAINT PK_003
 PRIMARY KEY
 (GRUPO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


