--
-- INFI_TB_911_CREDENCIALES  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_911_CREDENCIALES
(
  SISTEMA  VARCHAR2(20 BYTE),
  CLAVE    VARCHAR2(50 BYTE),
  USUARIO  VARCHAR2(50 BYTE),
  ACTIVO   NUMBER,
  INTERNO  NUMBER
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ADM_INFI.INFI_TB_911_CREDENCIALES.SISTEMA IS 'Permite identificar cual es el sistema al que se le esta guardando la clave puede ser WS u otra cosa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_911_CREDENCIALES.CLAVE IS 'La clave que se guarda, puede estar o no encriptada';

COMMENT ON COLUMN ADM_INFI.INFI_TB_911_CREDENCIALES.USUARIO IS 'El usuario que se guarda, puede estar encriptado o no';

COMMENT ON COLUMN ADM_INFI.INFI_TB_911_CREDENCIALES.ACTIVO IS 'Permite saber si el registro esta activo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_911_CREDENCIALES.INTERNO IS 'Permite saber si el registro es un parametro interno, el cual no se va a mostrar al usuario.';

--
-- INFI_TB_911_CREDENCIALES_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.INFI_TB_911_CREDENCIALES_PK ON ADM_INFI.INFI_TB_911_CREDENCIALES
(SISTEMA)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_911_CREDENCIALES  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_911_CREDENCIALES FOR ADM_INFI.INFI_TB_911_CREDENCIALES;

GRANT DELETE ON  ADM_INFI.INFI_TB_911_CREDENCIALES TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_911_CREDENCIALES TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_911_CREDENCIALES TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_911_CREDENCIALES TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_911_CREDENCIALES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_911_CREDENCIALES ADD (
  CONSTRAINT INFI_TB_911_CREDENCIALES_PK
 PRIMARY KEY
 (SISTEMA)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


