--
-- INFI_TB_115_UI_DOC  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_115_UI_DOC
(
  UNDINV_ID     NUMBER(7)                       NOT NULL,
  TIPCAR_ID     NUMBER(2)                       NOT NULL,
  TIPPER_ID     VARCHAR2(1 BYTE)                NOT NULL,
  BLOTER_ID     VARCHAR2(25 BYTE)               NOT NULL,
  DOCUMENTO_ID  NUMBER                          NOT NULL,
  UIDOC_UNICO   NUMBER(7)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_115_UI_DOC IS 'Documentos relacionados a la unidad de inversión segun blotter y tipo de persona';

COMMENT ON COLUMN ADM_INFI.INFI_TB_115_UI_DOC.UNDINV_ID IS 'Id de unidad de inversión';

COMMENT ON COLUMN ADM_INFI.INFI_TB_115_UI_DOC.TIPCAR_ID IS 'Id de tipo de carta';

COMMENT ON COLUMN ADM_INFI.INFI_TB_115_UI_DOC.TIPPER_ID IS 'Id de tipo de persona';

COMMENT ON COLUMN ADM_INFI.INFI_TB_115_UI_DOC.BLOTER_ID IS 'Id de blotter';

COMMENT ON COLUMN ADM_INFI.INFI_TB_115_UI_DOC.DOCUMENTO_ID IS 'Id de documento';

--
-- PK_115  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_115 ON ADM_INFI.INFI_TB_115_UI_DOC
(UNDINV_ID, TIPCAR_ID, TIPPER_ID, BLOTER_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_115_UI_DOC  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_115_UI_DOC FOR ADM_INFI.INFI_TB_115_UI_DOC;

GRANT DELETE ON  ADM_INFI.INFI_TB_115_UI_DOC TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_115_UI_DOC TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_115_UI_DOC TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_115_UI_DOC TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_115_UI_DOC 
-- 
ALTER TABLE ADM_INFI.INFI_TB_115_UI_DOC ADD (
  CONSTRAINT PK_115
 PRIMARY KEY
 (UNDINV_ID, TIPCAR_ID, TIPPER_ID, BLOTER_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_115_UI_DOC 
-- 
ALTER TABLE ADM_INFI.INFI_TB_115_UI_DOC ADD (
  CONSTRAINT FK_115_102 
 FOREIGN KEY (BLOTER_ID) 
 REFERENCES ADM_INFI.INFI_TB_102_BLOTER (BLOTER_ID));

ALTER TABLE ADM_INFI.INFI_TB_115_UI_DOC ADD (
  CONSTRAINT FK_115_200 
 FOREIGN KEY (TIPPER_ID) 
 REFERENCES ADM_INFI.INFI_TB_200_TIPO_PERSONAS (TIPPER_ID));

ALTER TABLE ADM_INFI.INFI_TB_115_UI_DOC ADD (
  CONSTRAINT FK_115_106 
 FOREIGN KEY (UNDINV_ID) 
 REFERENCES ADM_INFI.INFI_TB_106_UNIDAD_INVERSION (UNDINV_ID)
    ON DELETE CASCADE);


