--
-- INFI_TB_040_COM_CUSTODIA  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_040_COM_CUSTODIA
(
  COMISION_ID          NUMBER(7)                NOT NULL,
  COMISION_NOMBRE      VARCHAR2(50 BYTE)        NOT NULL,
  USUARIO_ID           NUMBER(7)                NOT NULL,
  FECHA_ULT_ACT        DATE                     NOT NULL,
  COMISION_IN_GENERAL  NUMBER(1)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ADM_INFI.INFI_TB_040_COM_CUSTODIA.COMISION_IN_GENERAL IS 'Indicador para saber si la comision sera General (1) o Especifica (0)';

--
-- INFI_TB_040_COM_CUSTODIA  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_040_COM_CUSTODIA FOR ADM_INFI.INFI_TB_040_COM_CUSTODIA;

GRANT DELETE ON  ADM_INFI.INFI_TB_040_COM_CUSTODIA TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_040_COM_CUSTODIA TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_040_COM_CUSTODIA TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_040_COM_CUSTODIA TO USU_INFI;

