--
-- INFI_TB_025_DOCUMENTOS_STATUS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_025_DOCUMENTOS_STATUS
(
  STATUS_DOCUMENTO    CHAR(1 BYTE)              NOT NULL,
  DESCRIPCION_STATUS  VARCHAR2(15 BYTE)         NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_025_DOCUMENTOS_STATUS IS 'Status de los documentos Aprobado, Creado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_025_DOCUMENTOS_STATUS.STATUS_DOCUMENTO IS 'Id de status de documento';

COMMENT ON COLUMN ADM_INFI.INFI_TB_025_DOCUMENTOS_STATUS.DESCRIPCION_STATUS IS 'Descripción del status';

--
-- PK_025  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_025 ON ADM_INFI.INFI_TB_025_DOCUMENTOS_STATUS
(STATUS_DOCUMENTO)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_025_DOCUMENTOS_STATUS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_025_DOCUMENTOS_STATUS FOR ADM_INFI.INFI_TB_025_DOCUMENTOS_STATUS;

GRANT DELETE ON  ADM_INFI.INFI_TB_025_DOCUMENTOS_STATUS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_025_DOCUMENTOS_STATUS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_025_DOCUMENTOS_STATUS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_025_DOCUMENTOS_STATUS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_025_DOCUMENTOS_STATUS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_025_DOCUMENTOS_STATUS ADD (
  CONSTRAINT PK_025
 PRIMARY KEY
 (STATUS_DOCUMENTO)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


