--
-- INFI_TB_047_EQUIV_PORTAFOLIO  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO
(
  SEGMENTO_ID           VARCHAR2(4 BYTE),
  SEGMENTO_DESCRIPCION  VARCHAR2(20 BYTE),
  PORTAFOLIO            VARCHAR2(4 BYTE),
  USUARIO_ID            NUMBER(7),
  FECHA_ULT_ACT         DATE
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO IS 'Contiene la equivalencia del segmento al que pertenece el cliente y el portafolio que debe enviarse en OPICS';

COMMENT ON COLUMN ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO.SEGMENTO_ID IS 'Id del segmento';

COMMENT ON COLUMN ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO.SEGMENTO_DESCRIPCION IS 'Descripción del segmento';

COMMENT ON COLUMN ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO.PORTAFOLIO IS 'Id del portafolio a enviar en OPICS';

COMMENT ON COLUMN ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO.USUARIO_ID IS 'Id del usuario que modificó el registro';

COMMENT ON COLUMN ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO.FECHA_ULT_ACT IS 'Fecha de última actualización del registro';

--
-- PK_047  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_047 ON ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO
(SEGMENTO_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_047_EQUIV_PORTAFOLIO  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_047_EQUIV_PORTAFOLIO FOR ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO;

GRANT DELETE ON  ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_047_EQUIV_PORTAFOLIO 
-- 
ALTER TABLE ADM_INFI.INFI_TB_047_EQUIV_PORTAFOLIO ADD (
  CONSTRAINT PK_047
 PRIMARY KEY
 (SEGMENTO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


