--
-- INFI_TB_QUARZ_SCHEDULER  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_QUARZ_SCHEDULER
(
  ID               NUMBER(2)                    NOT NULL,
  NAME             VARCHAR2(50 BYTE)            NOT NULL,
  GRUPO            VARCHAR2(50 BYTE),
  JOB_CLASS        VARCHAR2(100 BYTE)           NOT NULL,
  NAME_TRIGGER     VARCHAR2(50 BYTE),
  GROUP_TRIGGER    VARCHAR2(50 BYTE),
  JOB_NAME         VARCHAR2(50 BYTE)            NOT NULL,
  JOB_GROUP        VARCHAR2(50 BYTE)            NOT NULL,
  CRON_EXPRESSION  VARCHAR2(50 BYTE),
  DESCRIPTION      VARCHAR2(100 BYTE),
  ESTADO           NUMBER(1)                    DEFAULT 1                     NOT NULL,
  VALUE_SCREEN     VARCHAR2(25 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_QUARZ_SCHEDULER IS 'Tabla donde se encuentran las Tareas que pueden ser programadas para ser levantadas a través del SCHEDULER (Programador de Tareas)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_QUARZ_SCHEDULER.ID IS 'Id unico';

COMMENT ON COLUMN ADM_INFI.INFI_TB_QUARZ_SCHEDULER.NAME IS 'Nombre de la tarea a ejecutar';

COMMENT ON COLUMN ADM_INFI.INFI_TB_QUARZ_SCHEDULER.GRUPO IS 'Grupo al que pertenece la tarea';

COMMENT ON COLUMN ADM_INFI.INFI_TB_QUARZ_SCHEDULER.JOB_CLASS IS 'Paquete donde se encuentra la clase que sera levantada por el SCHEDULER';

COMMENT ON COLUMN ADM_INFI.INFI_TB_QUARZ_SCHEDULER.NAME_TRIGGER IS 'Nombre del trigger para la ejecucion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_QUARZ_SCHEDULER.GROUP_TRIGGER IS 'Grupo del Trigger';

COMMENT ON COLUMN ADM_INFI.INFI_TB_QUARZ_SCHEDULER.JOB_NAME IS 'Nombre de la tarea a ejecutar es igual al NAME';

COMMENT ON COLUMN ADM_INFI.INFI_TB_QUARZ_SCHEDULER.JOB_GROUP IS 'Grupo de la tarea es igual a GROUP';

COMMENT ON COLUMN ADM_INFI.INFI_TB_QUARZ_SCHEDULER.CRON_EXPRESSION IS 'Este campo guarda como y cuando se va ejecutar la tarea programada';

COMMENT ON COLUMN ADM_INFI.INFI_TB_QUARZ_SCHEDULER.DESCRIPTION IS 'Descripcion de la Tarea';

COMMENT ON COLUMN ADM_INFI.INFI_TB_QUARZ_SCHEDULER.ESTADO IS 'Indica si la tarea se encuentra en estatus activo o inactivo';

--
-- PK_QUARTZ  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_QUARTZ ON ADM_INFI.INFI_TB_QUARZ_SCHEDULER
(ID, JOB_CLASS)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_QUARZ_SCHEDULER  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_QUARZ_SCHEDULER FOR ADM_INFI.INFI_TB_QUARZ_SCHEDULER;

GRANT DELETE ON  ADM_INFI.INFI_TB_QUARZ_SCHEDULER TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_QUARZ_SCHEDULER TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_QUARZ_SCHEDULER TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_QUARZ_SCHEDULER TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_QUARZ_SCHEDULER 
-- 
ALTER TABLE ADM_INFI.INFI_TB_QUARZ_SCHEDULER ADD (
  CONSTRAINT PK_QUARTZ
 PRIMARY KEY
 (ID, JOB_CLASS)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


