--
-- INFI_TB_041_COM_TRANSACCION  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_041_COM_TRANSACCION
(
  COMISION_ID              NUMBER(7)            NOT NULL,
  PCT_TRANS_INTERNA        NUMBER(5,3),
  PCT_TRANS_EXTERNA        NUMBER(5,3),
  MTO_TRANS_INTERNA        NUMBER(10,3),
  MONEDA_TRANS_INTERNA     VARCHAR2(3 BYTE),
  MTO_TRANS_EXTERNA        NUMBER(10,3),
  MONEDA_TRANS_EXTERNA     VARCHAR2(3 BYTE),
  PCT_ANUAL_NACIONAL       NUMBER(5,3),
  PCT_ANUAL_EXTRANJERA     NUMBER(5,3),
  MTO_ANUAL_NACIONAL       NUMBER(10,3),
  MONEDA_ANUAL_NACIONAL    VARCHAR2(3 BYTE),
  MTO_ANUAL_EXTRANJERA     NUMBER(10,3),
  MONEDA_ANUAL_EXTRANJERA  VARCHAR2(3 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- INFI_TB_041_COM_TRANSACCION  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_041_COM_TRANSACCION FOR ADM_INFI.INFI_TB_041_COM_TRANSACCION;

GRANT DELETE ON  ADM_INFI.INFI_TB_041_COM_TRANSACCION TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_041_COM_TRANSACCION TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_041_COM_TRANSACCION TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_041_COM_TRANSACCION TO USU_INFI;

