--
-- INFI_TB_212_ORDENES_DATAEXT  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_212_ORDENES_DATAEXT
(
  ORDENE_ID     NUMBER(10)                      NOT NULL,
  DTAEXT_ID     VARCHAR2(25 BYTE),
  DTAEXT_VALOR  VARCHAR2(100 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_212_ORDENES_DATAEXT IS 'Data extendida asociada a una orden. Se pueden almacenar cualquier data adicional que se considere necesario para una orden';

COMMENT ON COLUMN ADM_INFI.INFI_TB_212_ORDENES_DATAEXT.ORDENE_ID IS 'Id de la orden';

COMMENT ON COLUMN ADM_INFI.INFI_TB_212_ORDENES_DATAEXT.DTAEXT_ID IS 'Id de la data extendida';

COMMENT ON COLUMN ADM_INFI.INFI_TB_212_ORDENES_DATAEXT.DTAEXT_VALOR IS 'Valor de la data extendida';

--
-- PK_212_1  (Index) 
--
CREATE INDEX ADM_INFI.PK_212_1 ON ADM_INFI.INFI_TB_212_ORDENES_DATAEXT
(DTAEXT_ID, DTAEXT_VALOR)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- PK_212  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_212 ON ADM_INFI.INFI_TB_212_ORDENES_DATAEXT
(ORDENE_ID, DTAEXT_ID, DTAEXT_VALOR)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_212_ORDENES_DATAEXT  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_212_ORDENES_DATAEXT FOR ADM_INFI.INFI_TB_212_ORDENES_DATAEXT;

GRANT DELETE ON  ADM_INFI.INFI_TB_212_ORDENES_DATAEXT TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_212_ORDENES_DATAEXT TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_212_ORDENES_DATAEXT TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_212_ORDENES_DATAEXT TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_212_ORDENES_DATAEXT 
-- 
ALTER TABLE ADM_INFI.INFI_TB_212_ORDENES_DATAEXT ADD (
  CONSTRAINT PK_212
 PRIMARY KEY
 (ORDENE_ID, DTAEXT_ID, DTAEXT_VALOR)
    USING INDEX 
    TABLESPACE INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_212_ORDENES_DATAEXT 
-- 
ALTER TABLE ADM_INFI.INFI_TB_212_ORDENES_DATAEXT ADD (
  CONSTRAINT FK_212_027 
 FOREIGN KEY (DTAEXT_ID) 
 REFERENCES ADM_INFI.INFI_TB_027_DATAEXT (DTAEXT_ID));

ALTER TABLE ADM_INFI.INFI_TB_212_ORDENES_DATAEXT ADD (
  CONSTRAINT FK_212_204 
 FOREIGN KEY (ORDENE_ID) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));


