--
-- INFI_TB_048_SECTOR_PRODUCTIVO  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_048_SECTOR_PRODUCTIVO
(
  SECTOR_ID    NUMBER(5)                        NOT NULL,
  DESCRIPCION  VARCHAR2(100 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_048_SECTOR_PRODUCTIVO IS 'Tabla de sector productivos para reportar información diaria de las operaciones realizadas a través del SITME';


--
-- INFI_TB_048_SECTOR_PRODUCTIVO  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_048_SECTOR_PRODUCTIVO FOR ADM_INFI.INFI_TB_048_SECTOR_PRODUCTIVO;

GRANT DELETE ON  ADM_INFI.INFI_TB_048_SECTOR_PRODUCTIVO TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_048_SECTOR_PRODUCTIVO TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_048_SECTOR_PRODUCTIVO TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_048_SECTOR_PRODUCTIVO TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_048_SECTOR_PRODUCTIVO 
-- 
ALTER TABLE ADM_INFI.INFI_TB_048_SECTOR_PRODUCTIVO ADD (
  PRIMARY KEY
 (SECTOR_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


