--
-- INFI_TB_011_INDICADORES  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_011_INDICADORES
(
  INDICA_ID            VARCHAR2(3 BYTE)         NOT NULL,
  INDICA_DESCRIPCION   VARCHAR2(200 BYTE)       NOT NULL,
  INDICA_IN_REQUERIDO  NUMBER(1)                NOT NULL,
  INDICA_IN_REQUISITO  NUMBER(1)                DEFAULT 0                     NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_011_INDICADORES IS 'Indicadores de cotejo en el momento de la toma de una orden';

COMMENT ON COLUMN ADM_INFI.INFI_TB_011_INDICADORES.INDICA_ID IS 'Id del indicador';

COMMENT ON COLUMN ADM_INFI.INFI_TB_011_INDICADORES.INDICA_DESCRIPCION IS 'Descripción del indicador';

COMMENT ON COLUMN ADM_INFI.INFI_TB_011_INDICADORES.INDICA_IN_REQUISITO IS 'Indica si es un requisito que debe solicitarse en la toma de orden';

--
-- PK_011  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_011 ON ADM_INFI.INFI_TB_011_INDICADORES
(INDICA_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_011_INDICADORES  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_011_INDICADORES FOR ADM_INFI.INFI_TB_011_INDICADORES;

GRANT DELETE ON  ADM_INFI.INFI_TB_011_INDICADORES TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_011_INDICADORES TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_011_INDICADORES TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_011_INDICADORES TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_011_INDICADORES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_011_INDICADORES ADD (
  CONSTRAINT PK_011
 PRIMARY KEY
 (INDICA_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


