--
-- INFI_TB_202_CTES_CUENTAS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_202_CTES_CUENTAS
(
  CTES_CUENTAS_ID            NUMBER(9)          NOT NULL,
  CLIENT_ID                  NUMBER(8)          NOT NULL,
  TIPO_INSTRUCCION_ID        NUMBER(1),
  CTECTA_USO                 VARCHAR2(5 BYTE),
  CTECTA_NUMERO              VARCHAR2(34 BYTE),
  CTECTA_NOMBRE              VARCHAR2(100 BYTE),
  CTECTA_BCOCTA_BCO          VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_DIRECCION    VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_SWIFT        VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_BIC          VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_TELEFONO     VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_ABA          VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_PAIS         VARCHAR2(25 BYTE),
  CTECTA_BCOINT_BCO          VARCHAR2(50 BYTE),
  CTECTA_BCOINT_DIRECCION    VARCHAR2(50 BYTE),
  CTECTA_BCOINT_SWIFT        VARCHAR2(50 BYTE),
  CTECTA_BCOINT_BIC          VARCHAR2(50 BYTE),
  CTECTA_BCOINT_TELEFONO     VARCHAR2(50 BYTE),
  CTECTA_BCOINT_ABA          VARCHAR2(50 BYTE),
  CTECTA_BCOINT_PAIS         VARCHAR2(25 BYTE),
  CTECTA_OBSERVACION         VARCHAR2(210 BYTE),
  CTECTA_BCOINT_OBSERVACION  VARCHAR2(210 BYTE),
  CEDULA_BENEFICIARIO        VARCHAR2(10 BYTE),
  NOMBRE_BENEFICIARIO        VARCHAR2(100 BYTE),
  COD_PAIS_DESTINO           VARCHAR2(20 BYTE),
  DESC_PAIS_DESTINO          VARCHAR2(100 BYTE),
  COD_PAIS_ORIGEN            VARCHAR2(20 BYTE),
  DESC_PAIS_ORIGEN           VARCHAR2(100 BYTE),
  COD_CIUDAD_ORIGEN          VARCHAR2(20 BYTE),
  DESC_CIUDAD_ORIGEN         VARCHAR2(100 BYTE),
  COD_ESTADO_ORIGEN          VARCHAR2(20 BYTE),
  DESC_ESTADO_ORIGEN         VARCHAR2(100 BYTE),
  ULT_FECHA_ACTUALIZACION    DATE
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_202_CTES_CUENTAS IS 'Permite definir las instrucciones de pago y cobro a un cliente en los eventos de cupones, amortizaciones y cobro de comisiones';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTES_CUENTAS_ID IS 'Id único que identifica la instrucción';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CLIENT_ID IS 'ID del Cliente. FK con TB201.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.TIPO_INSTRUCCION_ID IS 'Id de la instrucción seleccionada';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_USO IS 'Descriptivo, de para que se debe utilizar la cuenta. Permite describir, si se desea utilizar la cuenta para que se le abone los Pagos de Cupones, o si se usa para los Abonos de Pago de Capital, etc. ';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_NUMERO IS 'Numero de Cuenta del Cliente. Aplica solo para Cuentas Internacionales. No aplica para las Cuentas de ALTAIR. Las cuentas de ALTAIR se mantienen en ALTAIR y se obtienen a través de los Servicios, al momento de ser requeridas.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_NOMBRE IS 'Nombre de Referecia de la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOCTA_BCO IS 'Nombre del Banco donde se posee la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOCTA_DIRECCION IS 'Direccion del Banco donde se posee la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOCTA_SWIFT IS 'Código SWIFT del Banco donde se posee la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOCTA_BIC IS 'Código BIC del Banco donde se posee la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOCTA_TELEFONO IS 'Télefono del Banco donde se posee la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOCTA_ABA IS 'Código ABA del Banco donde se posee la Cuenta. Este código solo aplica a cuentas de Bancos en EEUU.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOCTA_PAIS IS 'País de donde es la Dirección de la sucursal donde se abrió la Cuenta.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOINT_BCO IS 'Nombre del Banco donde que fungirá como Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOINT_DIRECCION IS 'Direccion del Banco Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOINT_SWIFT IS 'Código SWIFT del Banco Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOINT_BIC IS 'Código BIC del Banco Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOINT_TELEFONO IS 'Télefono del Banco Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOINT_ABA IS 'Código ABA del Banco Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOINT_PAIS IS 'País de donde es la Dirección del Banco Intermediario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_OBSERVACION IS 'Observaciones a cuenta final';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CTECTA_BCOINT_OBSERVACION IS 'Observaciones a cuenta con banco intermediario';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.CEDULA_BENEFICIARIO IS 'Cédula del beneficiario';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.NOMBRE_BENEFICIARIO IS 'Nombre del beneficiario';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.DESC_ESTADO_ORIGEN IS 'Descripción de ciudad de origen del cliente registrada en la solicitud';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.COD_PAIS_ORIGEN IS 'Código de país de origen del cliente registrada en la solicitud ';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.DESC_CIUDAD_ORIGEN IS 'Descripción de ciudad de origen del cliente registrada en la solicitud';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.DESC_PAIS_ORIGEN IS 'Descripción de país de origen del cliente registrada en la solicitud ';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.COD_CIUDAD_ORIGEN IS 'Código de ciudad de origen del cliente registrada en la solicitud';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.COD_ESTADO_ORIGEN IS 'Código de estado de origen del cliente registrada en la solicitud';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.ULT_FECHA_ACTUALIZACION IS 'Fecha de última actualización de la instrucción de pago del cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.COD_PAIS_DESTINO IS 'Código de país de destino de viaje del cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_202_CTES_CUENTAS.DESC_PAIS_DESTINO IS 'Descripción del país de destino de viaje del cliente';

--
-- PK_202  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_202 ON ADM_INFI.INFI_TB_202_CTES_CUENTAS
(CTES_CUENTAS_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- IDX_CLIENT_ID  (Index) 
--
CREATE INDEX ADM_INFI.IDX_CLIENT_ID ON ADM_INFI.INFI_TB_202_CTES_CUENTAS
(CLIENT_ID)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- IDX_CTECTA_USO  (Index) 
--
CREATE INDEX ADM_INFI.IDX_CTECTA_USO ON ADM_INFI.INFI_TB_202_CTES_CUENTAS
(CTECTA_USO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_202_CTES_CUENTAS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_202_CTES_CUENTAS FOR ADM_INFI.INFI_TB_202_CTES_CUENTAS;

GRANT DELETE ON  ADM_INFI.INFI_TB_202_CTES_CUENTAS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_202_CTES_CUENTAS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_202_CTES_CUENTAS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_202_CTES_CUENTAS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_202_CTES_CUENTAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_202_CTES_CUENTAS ADD (
  CONSTRAINT PK_202
 PRIMARY KEY
 (CTES_CUENTAS_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_202_CTES_CUENTAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_202_CTES_CUENTAS ADD (
  CONSTRAINT FK_202_045 
 FOREIGN KEY (TIPO_INSTRUCCION_ID) 
 REFERENCES ADM_INFI.INFI_TB_045_TIPO_INSTRUCCION (TIPO_INSTRUCCION_ID));

ALTER TABLE ADM_INFI.INFI_TB_202_CTES_CUENTAS ADD (
  CONSTRAINT FK_202_201 
 FOREIGN KEY (CLIENT_ID) 
 REFERENCES ADM_INFI.INFI_TB_201_CTES (CLIENT_ID));


