--
-- INFI_TB_813_PROCESO_OPERACION  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_813_PROCESO_OPERACION
(
  PROCESO_ID           NUMBER(8)                NOT NULL,
  ORDENE_OPERACION_ID  NUMBER(9)                NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- INFI_TB_813_PROCESO_OPERACION  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_813_PROCESO_OPERACION FOR ADM_INFI.INFI_TB_813_PROCESO_OPERACION;

GRANT DELETE ON  ADM_INFI.INFI_TB_813_PROCESO_OPERACION TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_813_PROCESO_OPERACION TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_813_PROCESO_OPERACION TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_813_PROCESO_OPERACION TO USU_INFI;

