--
-- INFI_TB_707_MOVIMIENTO_CUPONES  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_707_MOVIMIENTO_CUPONES
(
  ORDENE_ID                   NUMBER(10),
  TIPBLO_ID                   VARCHAR2(25 BYTE),
  FECHA_MOVIMIENTO            DATE,
  CLIENT_ID                   NUMBER(8),
  ORDENE_USR_TERMINAL         VARCHAR2(50 BYTE),
  ORDENE_USR_NOMBRE           VARCHAR2(50 BYTE),
  TIPO_OPERACION              VARCHAR2(25 BYTE) NOT NULL,
  MOVIMIENTO_ID               NUMBER(10),
  POSICION_A_LA_FECHA         NUMBER(15,5)      DEFAULT 0,
  OBSERVACION                 VARCHAR2(150 BYTE),
  ID_ORDEN_PAGO               NUMBER(10),
  MONTO_COMISION_CANCELACION  NUMBER(15,5)      DEFAULT 0,
  MONTO_MOVIMIENTO            NUMBER(15,5)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


-- 
-- Non Foreign Key Constraints for Table INFI_TB_707_MOVIMIENTO_CUPONES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_707_MOVIMIENTO_CUPONES ADD (
  PRIMARY KEY
 (MOVIMIENTO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_707_MOVIMIENTO_CUPONES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_707_MOVIMIENTO_CUPONES ADD (
  FOREIGN KEY (ORDENE_ID) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));

ALTER TABLE ADM_INFI.INFI_TB_707_MOVIMIENTO_CUPONES ADD (
  FOREIGN KEY (CLIENT_ID) 
 REFERENCES ADM_INFI.INFI_TB_201_CTES (CLIENT_ID));


