--
-- INFI_TB_114_UI_CAMPOS_DINAMIC  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_114_UI_CAMPOS_DINAMIC
(
  UNDINV_ID  NUMBER(7)                          NOT NULL,
  CAMPO_ID   NUMBER(4)                          NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- PK_114  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_114 ON ADM_INFI.INFI_TB_114_UI_CAMPOS_DINAMIC
(UNDINV_ID, CAMPO_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_114_UI_CAMPOS_DINAMIC  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_114_UI_CAMPOS_DINAMIC FOR ADM_INFI.INFI_TB_114_UI_CAMPOS_DINAMIC;

GRANT DELETE ON  ADM_INFI.INFI_TB_114_UI_CAMPOS_DINAMIC TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_114_UI_CAMPOS_DINAMIC TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_114_UI_CAMPOS_DINAMIC TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_114_UI_CAMPOS_DINAMIC TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_114_UI_CAMPOS_DINAMIC 
-- 
ALTER TABLE ADM_INFI.INFI_TB_114_UI_CAMPOS_DINAMIC ADD (
  CONSTRAINT PK_114
 PRIMARY KEY
 (UNDINV_ID, CAMPO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_114_UI_CAMPOS_DINAMIC 
-- 
ALTER TABLE ADM_INFI.INFI_TB_114_UI_CAMPOS_DINAMIC ADD (
  CONSTRAINT FK_114_036 
 FOREIGN KEY (CAMPO_ID) 
 REFERENCES ADM_INFI.INFI_TB_036_CAMPOS_DINAMICOS (CAMPO_ID));

ALTER TABLE ADM_INFI.INFI_TB_114_UI_CAMPOS_DINAMIC ADD (
  CONSTRAINT FK_114_106 
 FOREIGN KEY (UNDINV_ID) 
 REFERENCES ADM_INFI.INFI_TB_106_UNIDAD_INVERSION (UNDINV_ID)
    ON DELETE CASCADE);


