--
-- INFI_TB_703_TITULOS_CUPONES  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_703_TITULOS_CUPONES
(
  TITULO_ID        VARCHAR2(25 BYTE)            NOT NULL,
  CLIENT_ID        NUMBER(8)                    NOT NULL,
  TITULO_CUPON_ID  NUMBER(7)                    NOT NULL,
  ORDENE_ID        NUMBER(10)                   NOT NULL,
  TITULO_TIPO      VARCHAR2(3 BYTE)             NOT NULL,
  FECHA            DATE                         NOT NULL,
  TASA_APLICADA    NUMBER(5,2)                  NOT NULL,
  MONTO_PAGADO     NUMBER(15,5)                 NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_703_TITULOS_CUPONES IS 'Tabla que contiene los cupones y comisiones pagadas por titulo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_703_TITULOS_CUPONES.TITULO_ID IS 'Id del título';

COMMENT ON COLUMN ADM_INFI.INFI_TB_703_TITULOS_CUPONES.CLIENT_ID IS 'Id del cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_703_TITULOS_CUPONES.TITULO_CUPON_ID IS 'Id unico del registro para conformar la clave primaria';

COMMENT ON COLUMN ADM_INFI.INFI_TB_703_TITULOS_CUPONES.ORDENE_ID IS 'Relación entre la orden que generó la transacción';

COMMENT ON COLUMN ADM_INFI.INFI_TB_703_TITULOS_CUPONES.TITULO_TIPO IS 'Indica el tipo (COMISION, CUPON)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_703_TITULOS_CUPONES.FECHA IS 'Fecha de ejecución';

COMMENT ON COLUMN ADM_INFI.INFI_TB_703_TITULOS_CUPONES.TASA_APLICADA IS 'Tasa aplicada para el cálculo de los cupones';

COMMENT ON COLUMN ADM_INFI.INFI_TB_703_TITULOS_CUPONES.MONTO_PAGADO IS 'Monto pagado';

--
-- PK_703  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_703 ON ADM_INFI.INFI_TB_703_TITULOS_CUPONES
(TITULO_ID, CLIENT_ID, TITULO_CUPON_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_703_TITULOS_CUPONES  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_703_TITULOS_CUPONES FOR ADM_INFI.INFI_TB_703_TITULOS_CUPONES;

GRANT DELETE ON  ADM_INFI.INFI_TB_703_TITULOS_CUPONES TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_703_TITULOS_CUPONES TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_703_TITULOS_CUPONES TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_703_TITULOS_CUPONES TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_703_TITULOS_CUPONES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_703_TITULOS_CUPONES ADD (
  CONSTRAINT PK_703
 PRIMARY KEY
 (TITULO_ID, CLIENT_ID, TITULO_CUPON_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_703_TITULOS_CUPONES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_703_TITULOS_CUPONES ADD (
  CONSTRAINT FK_703_201 
 FOREIGN KEY (CLIENT_ID) 
 REFERENCES ADM_INFI.INFI_TB_201_CTES (CLIENT_ID));


