--
-- INFI_TB_801_TRF_SISTEMA  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_801_TRF_SISTEMA
(
  TRNFIN_ID             VARCHAR2(6 BYTE)        NOT NULL,
  SISTEMA_ID            VARCHAR2(10 BYTE)       NOT NULL,
  CODIGO_TRNF           VARCHAR2(10 BYTE)       NOT NULL,
  BLOTER_ID             VARCHAR2(25 BYTE),
  CENTRO_CONTABLE       VARCHAR2(10 BYTE),
  CODIGO_OPERACION      VARCHAR2(10 BYTE),
  CODIGO_UNICO          NUMBER(20),
  UNDINV_ID             NUMBER(7),
  CODIGO_OPERACION_CRE  VARCHAR2(10 BYTE),
  CODIGO_OPERACION_BLO  VARCHAR2(10 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_801_TRF_SISTEMA IS 'Los códigos relacionados a un determinado sistema para una determinada transacción financiera.
Por ejemplo, para pago de capital a ALTAIR puede ser 600, pero para SWIF 500';

COMMENT ON COLUMN ADM_INFI.INFI_TB_801_TRF_SISTEMA.TRNFIN_ID IS 'Id de la transacción financiera';

COMMENT ON COLUMN ADM_INFI.INFI_TB_801_TRF_SISTEMA.SISTEMA_ID IS 'Id del sistema';

COMMENT ON COLUMN ADM_INFI.INFI_TB_801_TRF_SISTEMA.CODIGO_TRNF IS 'Código que debe enviarse al sistema cuando aparece una operación determinada';

--
-- INFI_TB_801_TRF_SISTEMA  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_801_TRF_SISTEMA FOR ADM_INFI.INFI_TB_801_TRF_SISTEMA;

GRANT DELETE ON  ADM_INFI.INFI_TB_801_TRF_SISTEMA TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_801_TRF_SISTEMA TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_801_TRF_SISTEMA TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_801_TRF_SISTEMA TO USU_INFI;

-- 
-- Foreign Key Constraints for Table INFI_TB_801_TRF_SISTEMA 
-- 
ALTER TABLE ADM_INFI.INFI_TB_801_TRF_SISTEMA ADD (
  CONSTRAINT FK_801_802 
 FOREIGN KEY (SISTEMA_ID) 
 REFERENCES ADM_INFI.INFI_TB_802_SISTEMA (SISTEMA_ID));


