--
-- INFI_TB_CIUDAD  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_CIUDAD
(
  COD_CIUDAD   VARCHAR2(15 BYTE),
  DESC_CIUDAD  VARCHAR2(60 BYTE),
  COD_ESTADO   VARCHAR2(15 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- INFI_TB_CIUDAD_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.INFI_TB_CIUDAD_PK ON ADM_INFI.INFI_TB_CIUDAD
(COD_CIUDAD)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_CIUDAD  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_CIUDAD FOR ADM_INFI.INFI_TB_CIUDAD;

GRANT DELETE ON  ADM_INFI.INFI_TB_CIUDAD TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_CIUDAD TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_CIUDAD TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_CIUDAD TO USU_INFI;

