--
-- INFI_TB_008_CTAS_BIC_TRANSA  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA
(
  ID_CUENTA              NUMBER(6),
  TRANSA_ID              VARCHAR2(25 BYTE)      NOT NULL,
  FE_ULT_ACTUALIZACION   DATE,
  USR_ULT_ACTUALIZACION  VARCHAR2(25 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA IS 'Asociación de transacciones con los números de cuentas';

COMMENT ON COLUMN ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA.ID_CUENTA IS 'Id de la cuenta';

COMMENT ON COLUMN ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA.TRANSA_ID IS 'Id de la transacción';

--
-- PK_008  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_008 ON ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA
(TRANSA_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_008_CTAS_BIC_TRANSA  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_008_CTAS_BIC_TRANSA FOR ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA;

GRANT DELETE ON  ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_008_CTAS_BIC_TRANSA 
-- 
ALTER TABLE ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA ADD (
  CONSTRAINT PK_008
 PRIMARY KEY
 (TRANSA_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_008_CTAS_BIC_TRANSA 
-- 
ALTER TABLE ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA ADD (
  CONSTRAINT FK_008_007 
 FOREIGN KEY (ID_CUENTA) 
 REFERENCES ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO (ID_CUENTA));

ALTER TABLE ADM_INFI.INFI_TB_008_CTAS_BIC_TRANSA ADD (
  CONSTRAINT FK_008_012 
 FOREIGN KEY (TRANSA_ID) 
 REFERENCES ADM_INFI.INFI_TB_012_TRANSACCIONES (TRANSA_ID));


