--
-- INFI_TB_033_OPERACION_STATUS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_033_OPERACION_STATUS
(
  STATUS_OPERACION       VARCHAR2(25 BYTE)      NOT NULL,
  STATUS_OPERACION_NOMB  VARCHAR2(50 BYTE)      NOT NULL,
  STATUS_OPERACION_DESC  VARCHAR2(100 BYTE)     NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_033_OPERACION_STATUS IS 'Status de las operaciones financieras';

COMMENT ON COLUMN ADM_INFI.INFI_TB_033_OPERACION_STATUS.STATUS_OPERACION IS 'Id del status de operación';

COMMENT ON COLUMN ADM_INFI.INFI_TB_033_OPERACION_STATUS.STATUS_OPERACION_NOMB IS 'Nombre del status';

COMMENT ON COLUMN ADM_INFI.INFI_TB_033_OPERACION_STATUS.STATUS_OPERACION_DESC IS 'Descripción del status';

--
-- PK_033  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_033 ON ADM_INFI.INFI_TB_033_OPERACION_STATUS
(STATUS_OPERACION)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_033_OPERACION_STATUS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_033_OPERACION_STATUS FOR ADM_INFI.INFI_TB_033_OPERACION_STATUS;

GRANT DELETE ON  ADM_INFI.INFI_TB_033_OPERACION_STATUS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_033_OPERACION_STATUS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_033_OPERACION_STATUS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_033_OPERACION_STATUS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_033_OPERACION_STATUS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_033_OPERACION_STATUS ADD (
  CONSTRAINT PK_033
 PRIMARY KEY
 (STATUS_OPERACION)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


