--
-- INFI_TB_113_UI_COMISION_REGLAS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS
(
  COMISION_ID        NUMBER(7)                  NOT NULL,
  COMISION_ID_REGLA  NUMBER(7)                  NOT NULL,
  BLOTER_ID          VARCHAR2(25 BYTE),
  TIPPER_ID          VARCHAR2(1 BYTE),
  REGLA_MONTO_FIJO   NUMBER(10,2),
  REGLA_PCT          NUMBER(8,4),
  RANGO_MIN          NUMBER(10)                 DEFAULT 0                     NOT NULL,
  RANGO_MAX          NUMBER(10)                 DEFAULT 9999999999            NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS IS 'Contiene las reglas específicas asociadas a una comisión. Jugando con los valores de esta tabla se puden crear reglas específicas para el cobro de comisiones, pudiendo colocar rangos de inversión, tipos de persona o blotter';

COMMENT ON COLUMN ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS.COMISION_ID IS 'Id de la comisión de asociación';

COMMENT ON COLUMN ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS.COMISION_ID_REGLA IS 'Id de la regla';

COMMENT ON COLUMN ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS.BLOTER_ID IS 'Id del blotter';

COMMENT ON COLUMN ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS.TIPPER_ID IS 'Id del tipo de persona asociado al blotter';

COMMENT ON COLUMN ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS.REGLA_MONTO_FIJO IS 'Monto fijo a cobrar';

COMMENT ON COLUMN ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS.REGLA_PCT IS 'Porcentaje a cobrar sobre el monto invertido';

COMMENT ON COLUMN ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS.RANGO_MIN IS 'Monto mínimo de inversión para la aplicación de la regla';

COMMENT ON COLUMN ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS.RANGO_MAX IS 'Monto máximo de inversión para la aplicación de la regla';

--
-- PK_113  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_113 ON ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS
(COMISION_ID, COMISION_ID_REGLA)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_113_UI_COMISION_REGLAS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_113_UI_COMISION_REGLAS FOR ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS;

GRANT DELETE ON  ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_113_UI_COMISION_REGLAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS ADD (
  CONSTRAINT PK_113
 PRIMARY KEY
 (COMISION_ID, COMISION_ID_REGLA)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_113_UI_COMISION_REGLAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS ADD (
  CONSTRAINT FK_113_102 
 FOREIGN KEY (BLOTER_ID) 
 REFERENCES ADM_INFI.INFI_TB_102_BLOTER (BLOTER_ID));

ALTER TABLE ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS ADD (
  CONSTRAINT FK_113_200 
 FOREIGN KEY (TIPPER_ID) 
 REFERENCES ADM_INFI.INFI_TB_200_TIPO_PERSONAS (TIPPER_ID));

ALTER TABLE ADM_INFI.INFI_TB_113_UI_COMISION_REGLAS ADD (
  CONSTRAINT FK_113_112 
 FOREIGN KEY (COMISION_ID) 
 REFERENCES ADM_INFI.INFI_TB_112_UI_COMISION (COMISION_ID)
    ON DELETE CASCADE);


