--
-- INFI_TB_220_ORDENE_DETALLES  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_220_ORDENE_DETALLES
(
  ORDEN_DETALLE_ID         NUMBER(10),
  ORDENE_ID                NUMBER(10)           NOT NULL,
  FECHA_VIAJE              DATE,
  FECHA_RETORNO            DATE,
  NUMERO_PASAPORTE         VARCHAR2(50 BYTE),
  ID_TICKET_CLAVENET       NUMBER(12),
  ULT_FECHA_ACTUALIZACION  DATE                 NOT NULL,
  OBSERVACION              VARCHAR2(150 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_220_ORDENE_DETALLES IS 'Permite definir datos adicionales a las instrucciones de pago y cobro a un cliente en  Ventas y Recompras de los modelos de Subasata Y SITME';

COMMENT ON COLUMN ADM_INFI.INFI_TB_220_ORDENE_DETALLES.OBSERVACION IS 'Observacion para notificacion de los Rechazos';

COMMENT ON COLUMN ADM_INFI.INFI_TB_220_ORDENE_DETALLES.ORDEN_DETALLE_ID IS 'Secuencia identificador del registro';

COMMENT ON COLUMN ADM_INFI.INFI_TB_220_ORDENE_DETALLES.ORDENE_ID IS 'secuencia referencia de la tabla infi_tb_204_ordenes';

COMMENT ON COLUMN ADM_INFI.INFI_TB_220_ORDENE_DETALLES.FECHA_VIAJE IS 'Fecha de salida de Viaje de las solicitudes SITME';

COMMENT ON COLUMN ADM_INFI.INFI_TB_220_ORDENE_DETALLES.FECHA_RETORNO IS 'Fecha de retorno de Viaje de las solicitudes SITME';

COMMENT ON COLUMN ADM_INFI.INFI_TB_220_ORDENE_DETALLES.NUMERO_PASAPORTE IS 'Numero de Pasaporte';

COMMENT ON COLUMN ADM_INFI.INFI_TB_220_ORDENE_DETALLES.ID_TICKET_CLAVENET IS 'Secuencia de las solicitudes de Clavenet Personal';

COMMENT ON COLUMN ADM_INFI.INFI_TB_220_ORDENE_DETALLES.ULT_FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';

--
-- INFI_TB_220_ORDENE_DETALLES_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.INFI_TB_220_ORDENE_DETALLES_PK ON ADM_INFI.INFI_TB_220_ORDENE_DETALLES
(ORDEN_DETALLE_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_220_ORDENE_ID  (Index) 
--
CREATE INDEX ADM_INFI.INFI_TB_220_ORDENE_ID ON ADM_INFI.INFI_TB_220_ORDENE_DETALLES
(ORDENE_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_220_ORDENE_DETALLES  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_220_ORDENE_DETALLES FOR ADM_INFI.INFI_TB_220_ORDENE_DETALLES;

GRANT DELETE ON  ADM_INFI.INFI_TB_220_ORDENE_DETALLES TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_220_ORDENE_DETALLES TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_220_ORDENE_DETALLES TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_220_ORDENE_DETALLES TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_220_ORDENE_DETALLES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_220_ORDENE_DETALLES ADD (
  CONSTRAINT INFI_TB_220_ORDENE_DETALLES_PK
 PRIMARY KEY
 (ORDEN_DETALLE_ID)
    USING INDEX 
    TABLESPACE INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_220_ORDENE_DETALLES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_220_ORDENE_DETALLES ADD (
  CONSTRAINT ORDENE_ID_FK 
 FOREIGN KEY (ORDENE_ID) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));


