--
-- INFI_TB_037_LISTAS_DINAMICAS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_037_LISTAS_DINAMICAS
(
  CAMPO_DINAMICO_ID  NUMBER(4)                  NOT NULL,
  ID_ITEM            VARCHAR2(60 BYTE)          NOT NULL,
  DESCRIPCION        VARCHAR2(500 BYTE)         NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- INFI_TB_037_LISTAS_DINAMICAS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_037_LISTAS_DINAMICAS FOR ADM_INFI.INFI_TB_037_LISTAS_DINAMICAS;

GRANT DELETE ON  ADM_INFI.INFI_TB_037_LISTAS_DINAMICAS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_037_LISTAS_DINAMICAS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_037_LISTAS_DINAMICAS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_037_LISTAS_DINAMICAS TO USU_INFI;

-- 
-- Foreign Key Constraints for Table INFI_TB_037_LISTAS_DINAMICAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_037_LISTAS_DINAMICAS ADD (
  FOREIGN KEY (CAMPO_DINAMICO_ID) 
 REFERENCES ADM_INFI.INFI_TB_036_CAMPOS_DINAMICOS (CAMPO_ID));


