--
-- INFI_TB_119_TITULOS_PREC_HIST  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST
(
  TITULO_ID                VARCHAR2(25 BYTE)    NOT NULL,
  TITULOS_PRECIO_NOMINAL   NUMBER(14,6)         NOT NULL,
  TITULOS_PRECIO_MERCADO   NUMBER(14,6)         NOT NULL,
  TITULOS_PRECIO_RECOMPRA  NUMBER(14,6)         NOT NULL,
  FECHA_ACT                DATE                 NOT NULL,
  USUARIO_ID               VARCHAR2(15 BYTE)    NOT NULL,
  USUARIO_ID_APROBADOR     VARCHAR2(15 BYTE),
  FECHA_APROBACION         DATE,
  TIPO_PRODUCTO_ID         VARCHAR2(10 BYTE)    NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST IS 'Tabla que contine el histórico de cambios relacionados a los precios asociados al título';

COMMENT ON COLUMN ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST.TITULO_ID IS 'Id del título';

COMMENT ON COLUMN ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST.TITULOS_PRECIO_NOMINAL IS 'Precio nominal del título';

COMMENT ON COLUMN ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST.TITULOS_PRECIO_MERCADO IS 'Precio de mercado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST.TITULOS_PRECIO_RECOMPRA IS 'Precio de recompra';

COMMENT ON COLUMN ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST.FECHA_ACT IS 'Fecha de actualización';

COMMENT ON COLUMN ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST.USUARIO_ID IS 'Id del usuario que modifica el registro';

--
-- INX_119_FECHA_APROBACION  (Index) 
--
CREATE INDEX ADM_INFI.INX_119_FECHA_APROBACION ON ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST
(FECHA_APROBACION)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INX_119_TPF  (Index) 
--
CREATE INDEX ADM_INFI.INX_119_TPF ON ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST
(FECHA_APROBACION, TITULO_ID, TIPO_PRODUCTO_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_119_TITULOS_PREC_HIST  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_119_TITULOS_PREC_HIST FOR ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST;

GRANT DELETE ON  ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_119_TITULOS_PREC_HIST TO USU_INFI;

