--
-- INFI_TB_Z50_CTES  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_Z50_CTES
(
  Z50_CLIENTE_ID        NUMBER(7),
  Z50_TIPOPERSONA       VARCHAR2(2 BYTE),
  Z50_CEDRIF            NUMBER(10),
  Z50_CEDRIF_COMPLETO   VARCHAR2(12 BYTE),
  Z50_NOMBRE            VARCHAR2(50 BYTE),
  Z50_CTA_CUSTOD_ID     NUMBER(7),
  Z50_CTA_CUSTOD_FECHA  DATE
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_Z50_CTES IS 'Tabla temporal para la carga inicial de clientes';

--
-- INFI_TB_Z50_CTES  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_Z50_CTES FOR ADM_INFI.INFI_TB_Z50_CTES;

GRANT DELETE ON  ADM_INFI.INFI_TB_Z50_CTES TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_Z50_CTES TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_Z50_CTES TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_Z50_CTES TO USU_INFI;

