--
-- INFI_TB_042_COM_DEPOSITARIO  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_042_COM_DEPOSITARIO
(
  COMISION_ID      NUMBER(7)                    NOT NULL,
  EMPRES_ID        VARCHAR2(25 BYTE)            NOT NULL,
  MTO_COMISION     NUMBER(10,3),
  MONEDA_COMISION  VARCHAR2(3 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- INFI_TB_042_COM_DEPOSITARIO  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_042_COM_DEPOSITARIO FOR ADM_INFI.INFI_TB_042_COM_DEPOSITARIO;

GRANT DELETE ON  ADM_INFI.INFI_TB_042_COM_DEPOSITARIO TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_042_COM_DEPOSITARIO TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_042_COM_DEPOSITARIO TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_042_COM_DEPOSITARIO TO USU_INFI;

