--
-- INFI_TB_029_TRANSACC_TRNFIN  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN
(
  TRANSA_ID           VARCHAR2(25 BYTE)         NOT NULL,
  TRNFIN_ID           VARCHAR2(6 BYTE)          NOT NULL,
  UNDINV_ID           NUMBER(7),
  MONEDA_ID           VARCHAR2(3 BYTE),
  BLOTER_ID           VARCHAR2(25 BYTE),
  TIPPER_ID           VARCHAR2(1 BYTE),
  EMPRES_ID           VARCHAR2(25 BYTE),
  PORCENTAJE          NUMBER(5,2),
  MONTO               NUMBER(10,2),
  TRANSACC_TRNFIN_ID  NUMBER                    NOT NULL,
  RANGO_MIN           NUMBER(10,2)              DEFAULT 0                     NOT NULL,
  RANGO_MAX           NUMBER(10,2)              DEFAULT 99999999              NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN IS 'Comisiones configuradas por transacción. Se puede jugar con la combinación de los campos para definir las comisiones que se deben cobrar en un proceso determinado sobre una orden';

COMMENT ON COLUMN ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN.TRANSA_ID IS 'Id de la transacción';

COMMENT ON COLUMN ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN.TRNFIN_ID IS 'Id de la transacción financiera que se debe aplicar';

COMMENT ON COLUMN ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN.UNDINV_ID IS 'Id de la unidad de inversión';

COMMENT ON COLUMN ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN.MONEDA_ID IS 'Id de la moneda';

COMMENT ON COLUMN ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN.BLOTER_ID IS 'Id de bloter';

COMMENT ON COLUMN ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN.TIPPER_ID IS 'Id de tipo de persona';

COMMENT ON COLUMN ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN.EMPRES_ID IS 'Id de empresa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN.PORCENTAJE IS 'Si la comision es cerrada permite colocar un porcentaje para el cliente. Debe estar el campo de cliente lleno';

COMMENT ON COLUMN ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN.MONTO IS 'Si la comision es cerrada permite colocar un monto fijo a cobrar para el cliente. Porcentaje o monto ambos no';

COMMENT ON COLUMN ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN.TRANSACC_TRNFIN_ID IS 'Id de la regla de Transacción Financiera';

--
-- TRANSACC_TRNFIN_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.TRANSACC_TRNFIN_PK ON ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN
(TRANSACC_TRNFIN_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_029_TRANSACC_TRNFIN  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_029_TRANSACC_TRNFIN FOR ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN;

GRANT DELETE ON  ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_029_TRANSACC_TRNFIN 
-- 
ALTER TABLE ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN ADD (
  CONSTRAINT TRANSACC_TRNFIN_PK
 PRIMARY KEY
 (TRANSACC_TRNFIN_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_029_TRANSACC_TRNFIN 
-- 
ALTER TABLE ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN ADD (
  CONSTRAINT FK_029_012 
 FOREIGN KEY (TRANSA_ID) 
 REFERENCES ADM_INFI.INFI_TB_012_TRANSACCIONES (TRANSA_ID));

ALTER TABLE ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN ADD (
  CONSTRAINT FK_029_016 
 FOREIGN KEY (EMPRES_ID) 
 REFERENCES ADM_INFI.INFI_TB_016_EMPRESAS (EMPRES_ID));

ALTER TABLE ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN ADD (
  CONSTRAINT FK_029_102 
 FOREIGN KEY (BLOTER_ID) 
 REFERENCES ADM_INFI.INFI_TB_102_BLOTER (BLOTER_ID));

ALTER TABLE ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN ADD (
  CONSTRAINT FK_029_106 
 FOREIGN KEY (UNDINV_ID) 
 REFERENCES ADM_INFI.INFI_TB_106_UNIDAD_INVERSION (UNDINV_ID));

ALTER TABLE ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN ADD (
  CONSTRAINT FK_029_200 
 FOREIGN KEY (TIPPER_ID) 
 REFERENCES ADM_INFI.INFI_TB_200_TIPO_PERSONAS (TIPPER_ID));

ALTER TABLE ADM_INFI.INFI_TB_029_TRANSACC_TRNFIN ADD (
  CONSTRAINT FK_029_800 
 FOREIGN KEY (TRNFIN_ID) 
 REFERENCES ADM_INFI.INFI_TB_800_TRN_FINANCIERAS (TRNFIN_ID));


