--
-- INFI_TB_027_DATAEXT  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_027_DATAEXT
(
  DTAEXT_ID           VARCHAR2(25 BYTE)         NOT NULL,
  DTAEXT_DESCRIPCION  VARCHAR2(50 BYTE)         NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_027_DATAEXT IS 'Configuración de la data extendida, usada para incorporar valores adicionales en una orden';

COMMENT ON COLUMN ADM_INFI.INFI_TB_027_DATAEXT.DTAEXT_ID IS 'Id de la data';

COMMENT ON COLUMN ADM_INFI.INFI_TB_027_DATAEXT.DTAEXT_DESCRIPCION IS 'Descripción';

--
-- PK_027  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_027 ON ADM_INFI.INFI_TB_027_DATAEXT
(DTAEXT_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_027_DATAEXT  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_027_DATAEXT FOR ADM_INFI.INFI_TB_027_DATAEXT;

GRANT DELETE ON  ADM_INFI.INFI_TB_027_DATAEXT TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_027_DATAEXT TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_027_DATAEXT TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_027_DATAEXT TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_027_DATAEXT 
-- 
ALTER TABLE ADM_INFI.INFI_TB_027_DATAEXT ADD (
  CONSTRAINT PK_027
 PRIMARY KEY
 (DTAEXT_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


