--
-- INFI_TB_208_ORDENES_DOCUMENTOS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS
(
  ORDENE_ID      NUMBER(10)                     NOT NULL,
  ORDENE_DOC_ID  NUMBER(7)                      NOT NULL,
  DOCUMENTO      BLOB,
  NOMBRE         VARCHAR2(80 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (DOCUMENTO) STORE AS 
      ( TABLESPACE  DATA 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS IS 'Tabla que contiene los documentos asociados a la orden que se genera';

COMMENT ON COLUMN ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS.ORDENE_ID IS 'Id de la orden';

COMMENT ON COLUMN ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS.ORDENE_DOC_ID IS 'Id necesario para establecer una clave primaria';

COMMENT ON COLUMN ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS.DOCUMENTO IS 'Contenido del archivo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS.NOMBRE IS 'Nombre del archivo';

--
-- PK_208  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_208 ON ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS
(ORDENE_ID, ORDENE_DOC_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_208_ORDENES_DOCUMENTOS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_208_ORDENES_DOCUMENTOS FOR ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS;

GRANT DELETE ON  ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_208_ORDENES_DOCUMENTOS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS ADD (
  CONSTRAINT PK_208
 PRIMARY KEY
 (ORDENE_ID, ORDENE_DOC_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_208_ORDENES_DOCUMENTOS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_208_ORDENES_DOCUMENTOS ADD (
  CONSTRAINT FK_208_204 
 FOREIGN KEY (ORDENE_ID) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));


