--
-- INFI_TB_101_INST_FINANCIEROS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_101_INST_FINANCIEROS
(
  INSFIN_ID                 VARCHAR2(25 BYTE)   NOT NULL,
  INSFIN_DESCRIPCION        VARCHAR2(200 BYTE)  NOT NULL,
  INSFIN_FORMA_ORDEN        VARCHAR2(15 BYTE)   NOT NULL,
  INSFIN_METODO_CUPONES     VARCHAR2(15 BYTE)   NOT NULL,
  INSFIN_MULTIPLES_ORDENES  NUMBER(1)           NOT NULL,
  INSFIN_IN_INVENTARIO      NUMBER(1)           NOT NULL,
  TIPO_PRODUCTO_ID          VARCHAR2(10 BYTE),
  MANEJO_PRODUCTOS          NUMBER(2)           DEFAULT 0
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_101_INST_FINANCIEROS IS 'Define los diferentes Instrumentos Financieros y sus atributos.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_101_INST_FINANCIEROS.INSFIN_ID IS 'Id del instrumento';

COMMENT ON COLUMN ADM_INFI.INFI_TB_101_INST_FINANCIEROS.INSFIN_DESCRIPCION IS 'Descripción del instrumento financiero';

COMMENT ON COLUMN ADM_INFI.INFI_TB_101_INST_FINANCIEROS.INSFIN_FORMA_ORDEN IS 'Indica como se procesa la Orden para este Instrumento. Se refiere a: Subasta, Subasta Competitiva o Inventario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_101_INST_FINANCIEROS.INSFIN_METODO_CUPONES IS 'Define, si el calculo de pago de cupones, es por Rendimiento o por Tasa.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_101_INST_FINANCIEROS.INSFIN_MULTIPLES_ORDENES IS 'Define, si en las Unidades de Inversión de este tipo de Instrumento, se permite una solo orden por Cliente, o se permiten multiples ordenes. 1=Se permite mas de una orden. 0=Solo se permite una orden por Cliente.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_101_INST_FINANCIEROS.INSFIN_IN_INVENTARIO IS 'Define, si el Instrumento Financiero se maneja por Inventario o no. 1= Manejo por Inventario. 0=Manejo no es por Inventario.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_101_INST_FINANCIEROS.MANEJO_PRODUCTOS IS 'CAMPO INDICARDOR MANEJO PRODUCTOS MIXTOS (1) O UNICO (0)';

--
-- PK_101  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_101 ON ADM_INFI.INFI_TB_101_INST_FINANCIEROS
(INSFIN_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- I_101_INSFIN_DESCRIPCION  (Index) 
--
CREATE INDEX ADM_INFI.I_101_INSFIN_DESCRIPCION ON ADM_INFI.INFI_TB_101_INST_FINANCIEROS
(INSFIN_DESCRIPCION)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_101_INST_FINANCIEROS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_101_INST_FINANCIEROS FOR ADM_INFI.INFI_TB_101_INST_FINANCIEROS;

GRANT DELETE ON  ADM_INFI.INFI_TB_101_INST_FINANCIEROS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_101_INST_FINANCIEROS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_101_INST_FINANCIEROS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_101_INST_FINANCIEROS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_101_INST_FINANCIEROS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_101_INST_FINANCIEROS ADD (
  CONSTRAINT PK_101
 PRIMARY KEY
 (INSFIN_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


