--
-- INFI_TB_012_TRANSACCIONES  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_012_TRANSACCIONES
(
  TRANSA_ID            VARCHAR2(25 BYTE)        NOT NULL,
  TRANSA_DESCRIPCION   VARCHAR2(50 BYTE)        NOT NULL,
  TRANSA_DESC_FUNCION  VARCHAR2(50 BYTE),
  TRANSA_IN_MOSTRAR    NUMBER(1),
  GRUPO_ID             NUMBER(2)                NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_012_TRANSACCIONES IS 'Contiene la lista de transacciones validas en el Sistema. Utilizada momento de registrar los procesos de Eventos Corporativos, o al momento de asociar documentos para su impresion.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_012_TRANSACCIONES.TRANSA_ID IS 'Id de la transacción';

COMMENT ON COLUMN ADM_INFI.INFI_TB_012_TRANSACCIONES.TRANSA_DESCRIPCION IS 'Descripción de la transacción';

COMMENT ON COLUMN ADM_INFI.INFI_TB_012_TRANSACCIONES.TRANSA_DESC_FUNCION IS 'Función que se va a levantar al final del proceso para llenar los documentos encontrados por una transacción';

--
-- PK_012  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_012 ON ADM_INFI.INFI_TB_012_TRANSACCIONES
(TRANSA_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_012_TRANSACCIONES  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_012_TRANSACCIONES FOR ADM_INFI.INFI_TB_012_TRANSACCIONES;

GRANT DELETE ON  ADM_INFI.INFI_TB_012_TRANSACCIONES TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_012_TRANSACCIONES TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_012_TRANSACCIONES TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_012_TRANSACCIONES TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_012_TRANSACCIONES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_012_TRANSACCIONES ADD (
  CONSTRAINT PK_012
 PRIMARY KEY
 (TRANSA_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_012_TRANSACCIONES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_012_TRANSACCIONES ADD (
  CONSTRAINT FK_012_003 
 FOREIGN KEY (GRUPO_ID) 
 REFERENCES ADM_INFI.INFI_TB_003_GRP_TRANSACCIONES (GRUPO_ID));


