--
-- INFI_TB_017_ROLES  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_017_ROLES
(
  ROLES_ID              VARCHAR2(15 BYTE)       NOT NULL,
  ROLES_DESCRIPCION     VARCHAR2(50 BYTE)       NOT NULL,
  ROLES_IN_TOMADOR      NUMBER(1)               NOT NULL,
  ROLES_IN_COLOCADOR    NUMBER(1)               NOT NULL,
  ROLES_IN_RECOMPRADOR  NUMBER(1)               NOT NULL,
  ROLES_STATUS          NUMBER(1)               NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_017_ROLES IS 'Permite definir los diferentes roles que puede tomar una Empresa o Vehiculo dentro de una Unidad de Inversion.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_017_ROLES.ROLES_ID IS 'Id del rol';

COMMENT ON COLUMN ADM_INFI.INFI_TB_017_ROLES.ROLES_DESCRIPCION IS 'Descripción del rol';

COMMENT ON COLUMN ADM_INFI.INFI_TB_017_ROLES.ROLES_IN_TOMADOR IS 'Indica que es tomador';

COMMENT ON COLUMN ADM_INFI.INFI_TB_017_ROLES.ROLES_IN_COLOCADOR IS 'Indica que es colocador';

COMMENT ON COLUMN ADM_INFI.INFI_TB_017_ROLES.ROLES_IN_RECOMPRADOR IS 'Indica que es recomprador';

COMMENT ON COLUMN ADM_INFI.INFI_TB_017_ROLES.ROLES_STATUS IS 'Status. 1=activo, 0=inactivo';

--
-- PK_017  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_017 ON ADM_INFI.INFI_TB_017_ROLES
(ROLES_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_017_ROLES  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_017_ROLES FOR ADM_INFI.INFI_TB_017_ROLES;

GRANT DELETE ON  ADM_INFI.INFI_TB_017_ROLES TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_017_ROLES TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_017_ROLES TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_017_ROLES TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_017_ROLES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_017_ROLES ADD (
  CONSTRAINT PK_017
 PRIMARY KEY
 (ROLES_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


