--
-- INFI_TB_850_CUENTA_CONTABLE  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_850_CUENTA_CONTABLE
(
  CUENTA_ID       NUMBER(10),
  CUENTA_NRO      VARCHAR2(30 BYTE),
  TIPO            VARCHAR2(25 BYTE),
  DESCRIPCION     VARCHAR2(100 BYTE),
  FECHA_CREACION  DATE,
  USER_CREACION   VARCHAR2(25 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_850_CUENTA_CONTABLE IS 'Tabla que contiene las cuentas contables';

COMMENT ON COLUMN ADM_INFI.INFI_TB_850_CUENTA_CONTABLE.CUENTA_NRO IS 'Número de la cuenta contable';

COMMENT ON COLUMN ADM_INFI.INFI_TB_850_CUENTA_CONTABLE.TIPO IS 'Tipo de cuenta (Opcional)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_850_CUENTA_CONTABLE.CUENTA_ID IS 'Id de cuenta contable';

COMMENT ON COLUMN ADM_INFI.INFI_TB_850_CUENTA_CONTABLE.DESCRIPCION IS 'Descripcion de la cuenta';

COMMENT ON COLUMN ADM_INFI.INFI_TB_850_CUENTA_CONTABLE.FECHA_CREACION IS 'Fecha de creación de la cuenta';

COMMENT ON COLUMN ADM_INFI.INFI_TB_850_CUENTA_CONTABLE.USER_CREACION IS 'Usuario que creó la cuenta';

--
-- INFI_TB_850_CUENTA_CONTABLE_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.INFI_TB_850_CUENTA_CONTABLE_PK ON ADM_INFI.INFI_TB_850_CUENTA_CONTABLE
(CUENTA_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_850_CUENTA_CONTABLE 
-- 
ALTER TABLE ADM_INFI.INFI_TB_850_CUENTA_CONTABLE ADD (
  CONSTRAINT CK_850_CUENTA_NRO
 CHECK (CUENTA_NRO is NOT NULL));

ALTER TABLE ADM_INFI.INFI_TB_850_CUENTA_CONTABLE ADD (
  CONSTRAINT CK_850_USER_CREACION
 CHECK (USER_CREACION is NOT NULL));

ALTER TABLE ADM_INFI.INFI_TB_850_CUENTA_CONTABLE ADD (
  CONSTRAINT CK_850_CUENTA_ID
 CHECK (CUENTA_ID is NOT NULL));

ALTER TABLE ADM_INFI.INFI_TB_850_CUENTA_CONTABLE ADD (
  CONSTRAINT PK_850
 PRIMARY KEY
 (CUENTA_ID));


