--
-- INFI_TB_223_PLANTILLA_MAIL  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_223_PLANTILLA_MAIL
(
  PLANTILLA_MAIL_ID         NUMBER(4)           NOT NULL,
  PLANTILLA_MAIL_NAME       VARCHAR2(100 BYTE),
  REMITENTE                 VARCHAR2(100 BYTE),
  TIPO_DESTINATARIO         VARCHAR2(2 BYTE)    NOT NULL,
  ASUNTO                    VARCHAR2(150 BYTE),
  CUERPO                    VARCHAR2(4000 BYTE),
  USUARIO_REGISTRO          VARCHAR2(25 BYTE)   NOT NULL,
  FECHA_APROBACION          DATE,
  ESTATUS_ACTIVACION        NUMBER(1)           DEFAULT 0,
  FECHA_REGISTRO            DATE,
  USUARIO_ULT_MODIFICACION  VARCHAR2(25 BYTE),
  FECHA_ULT_MODIFICACION    DATE,
  USUARIO_APROBACION        VARCHAR2(25 BYTE),
  EVENTO_ID                 VARCHAR2(25 BYTE)   NOT NULL,
  BLOQUE_ITERADO            VARCHAR2(4000 BYTE) DEFAULT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_223_PLANTILLA_MAIL IS 'Contiene las plantillas de los correos a enviar';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.PLANTILLA_MAIL_NAME IS 'Nombre de la planilla';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.REMITENTE IS 'Remitente del correo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.TIPO_DESTINATARIO IS 'Puede ser ''Cliente'' (C) o ''Funcional'' (F). De ser ''Funcional'' estará asociada a alguna área (INFI_TB_224_PLANTILLA_MAIL_AREA)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.ASUNTO IS 'Asunto del correo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.CUERPO IS 'Cuerpo del mensaje del correo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.USUARIO_REGISTRO IS 'Usuario que registró la plantilla';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.FECHA_APROBACION IS 'Fecha en la cual el USUARIO_APROBACION aprobó la plantilla';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.ESTATUS_ACTIVACION IS 'Indica si la plantilla se encuentra activa o no';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.FECHA_REGISTRO IS 'Indica la fecha en la cual se registró la plantilla de correo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.USUARIO_ULT_MODIFICACION IS 'Indica el usuario que modificó por última vez la plantilla de correo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.FECHA_ULT_MODIFICACION IS 'Indica la fecha en la cual se modificó por última vez la plantilla de correo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.USUARIO_APROBACION IS 'Usuario aprobador de la plantilla de correo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.EVENTO_ID IS 'Evento asociado a la plantilla';

COMMENT ON COLUMN ADM_INFI.INFI_TB_223_PLANTILLA_MAIL.PLANTILLA_MAIL_ID IS 'ID de la plantilla';

--
-- PK_223  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_223 ON ADM_INFI.INFI_TB_223_PLANTILLA_MAIL
(PLANTILLA_MAIL_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TRG_223  (Trigger) 
--
CREATE OR REPLACE TRIGGER ADM_INFI.INFI_TRG_223
    BEFORE INSERT
    ON ADM_INFI.INFI_TB_223_PLANTILLA_MAIL     REFERENCING NEW AS NEW OLD AS OLD
    FOR EACH ROW
BEGIN
    -- Si no se ha indicado un ID generamos uno
    IF :NEW.PLANTILLA_MAIL_ID IS NULL THEN
        SELECT INFI_SQ_223.NEXTVAL INTO :NEW.PLANTILLA_MAIL_ID FROM DUAL;
    END IF;
    EXCEPTION
        WHEN OTHERS THEN RAISE;
END INFI_TRG_223;
/
SHOW ERRORS;


--
-- INFI_TB_223_PLANTILLA_MAIL  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_223_PLANTILLA_MAIL FOR ADM_INFI.INFI_TB_223_PLANTILLA_MAIL;

GRANT DELETE ON  ADM_INFI.INFI_TB_223_PLANTILLA_MAIL TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_223_PLANTILLA_MAIL TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_223_PLANTILLA_MAIL TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_223_PLANTILLA_MAIL TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_223_PLANTILLA_MAIL 
-- 
ALTER TABLE ADM_INFI.INFI_TB_223_PLANTILLA_MAIL ADD (
  CONSTRAINT CK_223
 CHECK (TIPO_DESTINATARIO IN ('C','c','F','f')));

ALTER TABLE ADM_INFI.INFI_TB_223_PLANTILLA_MAIL ADD (
  CONSTRAINT PK_223
 PRIMARY KEY
 (PLANTILLA_MAIL_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_223_PLANTILLA_MAIL 
-- 
ALTER TABLE ADM_INFI.INFI_TB_223_PLANTILLA_MAIL ADD (
  CONSTRAINT FK_223_230 
 FOREIGN KEY (EVENTO_ID) 
 REFERENCES ADM_INFI.INFI_TB_230_EVENTO_MAIL (EVENTO_ID));


