--
-- INFI_TB_808_CTAS_USO  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_808_CTAS_USO
(
  CTECTA_USO              VARCHAR2(5 BYTE)      NOT NULL,
  CTECTA_USO_DESCRIPCION  CHAR(30 BYTE)         NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_808_CTAS_USO IS 'Tabla que contiene los diferentes usos que se le pueden dar a las cuentas que posee un cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_808_CTAS_USO.CTECTA_USO IS 'Uso de la cuenta';

COMMENT ON COLUMN ADM_INFI.INFI_TB_808_CTAS_USO.CTECTA_USO_DESCRIPCION IS 'Descripción del uso de la cuenta';

--
-- PK_808  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_808 ON ADM_INFI.INFI_TB_808_CTAS_USO
(CTECTA_USO)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_808_CTAS_USO  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_808_CTAS_USO FOR ADM_INFI.INFI_TB_808_CTAS_USO;

GRANT DELETE ON  ADM_INFI.INFI_TB_808_CTAS_USO TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_808_CTAS_USO TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_808_CTAS_USO TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_808_CTAS_USO TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_808_CTAS_USO 
-- 
ALTER TABLE ADM_INFI.INFI_TB_808_CTAS_USO ADD (
  CONSTRAINT PK_808
 PRIMARY KEY
 (CTECTA_USO)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


