--
-- INFI_TB_229_ORDENES_CRUCES  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_229_ORDENES_CRUCES
(
  ID_CRUCE                       NUMBER(10),
  ORDENE_ID                      VARCHAR2(10 BYTE),
  UNDINV_ID                      VARCHAR2(7 BYTE),
  ORDENE_ID_BCV                  VARCHAR2(20 BYTE),
  NRO_OPERACION                  VARCHAR2(10 BYTE),
  MONTO_OPERACION                VARCHAR2(20 BYTE),
  TASA                           VARCHAR2(15 BYTE),
  PRECIO_TITULO                  VARCHAR2(15 BYTE),
  VALOR_NOMINAL                  VARCHAR2(20 BYTE),
  ISIN                           VARCHAR2(25 BYTE),
  CONTRAPARTE                    VARCHAR2(100 BYTE),
  ESTATUS                        VARCHAR2(25 BYTE),
  OBSERVACION                    VARCHAR2(1000 BYTE),
  ID_EJECUCION                   VARCHAR2(7 BYTE),
  INDICADOR_TITULO               VARCHAR2(1 BYTE) DEFAULT '0',
  CLIENT_ID                      VARCHAR2(8 BYTE),
  TITULO_ID                      VARCHAR2(25 BYTE),
  TITULO_MTO_INT_CAIDOS          VARCHAR2(20 BYTE),
  FECHA_VALOR                    VARCHAR2(10 BYTE),
  CRUCE_PROCESADO                NUMBER(1)      DEFAULT 0,
  LIQUIDACION_PROCESADA          NUMBER(1)      DEFAULT 0,
  CONTRAVALOR_BOLIVARES_CAPITAL  NUMBER(15,5)   DEFAULT 0,
  IND_TITULO_PROCESADO           VARCHAR2(1 BYTE) DEFAULT '0',
  UNDINV_ID_OFERTA               NUMBER(7)      DEFAULT 0,
  CLIENT_ID_OFERTA               VARCHAR2(8 BYTE),
  ORDENE_ID_BCV_OFERTA           VARCHAR2(20 BYTE),
  ORDENE_ESTATUS_BCV             NUMBER(1)      DEFAULT 0,
  ORDENE_ID_PACTO_BCV            VARCHAR2(20 BYTE),
  ORDENE_ID_OFERTA               VARCHAR2(10 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.ID_CRUCE IS 'IDENTIFICADOR UNICO DEL PROCESO DE CRUCE ASOCIADO A UNA SOLICITUD';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.ORDENE_ID IS 'IDENTIFICADOR DEL NUMERO DE ORDEN DE SOLICITUD';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.UNDINV_ID IS 'IDENTIFICADOR DE LA UNIDAD DE INVERSION A LA QUE ESTA ASOCIADO EL CRUCE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.ORDENE_ID_BCV IS 'NUMERO DE ORDEN ASIGNADO POR EL BCV PARA UN CRUCE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.NRO_OPERACION IS 'NUMERO DE OPERACION ASIGNADO POR EL BCV PARA UN CRUCE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.MONTO_OPERACION IS 'MONTO POR EL CUAL SE REALIZARA EL CRUCE DE LA SOLICITUD';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.TASA IS 'TASA DE CAMBIO QUE APLICA PARA EL CRUCE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.PRECIO_TITULO IS 'PRECIO ESTABLECIDO PARA EL TITULOS CRUZADO';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.VALOR_NOMINAL IS 'VALOR NOMINAL ASOCIADO A UN TITULO';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.ISIN IS 'CODIGO DE IDENTIFICACION DE UN TITULO';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.CONTRAPARTE IS 'RIF DE LA CONTRAPARTE DE LA OPERACION DE CRUCE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.ESTATUS IS 'ESTATUS DEL PRCESO DE CRUCE (INVALIDO,CRUZADO,NO_CRUZADO)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.OBSERVACION IS 'CAMPO DE OBSERVACION UTILIZADO PARA DESCRIBIR UN POSIBLE ERROR AL CARGAR UN REGISTRO DE CRUCE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.ID_EJECUCION IS 'IDENTIFICADOR DEL PROCESO QUE SE EJECUTO';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.INDICADOR_TITULO IS 'MARCA QUE INDICA SI EL REGISTRO A PROCESAR ES UN CRUCE POR TITULO (1) O POR DIVISAS (0) ';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.CLIENT_ID IS 'IDENTIFICADOR DEL CLIENTE QUE REALIZA LA SOLICITUD DE CRUCE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.TITULO_ID IS 'NOMBRE DEL TITULO ASOCIADO AL CRUCE (EN CASO QUE SEA UN REGISTRO MARCADO COMO TIPO TITULO)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.TITULO_MTO_INT_CAIDOS IS 'MONTO DE INTERESES CAIDOS ASOCIADOS AL TITULO SELECCIONADO';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.FECHA_VALOR IS 'FECHA VALOR DE LA OPERACION DE CRUCE';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.CRUCE_PROCESADO IS 'INDICADOR DE SI EL REGISTRO YA FUE PROCESADO';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.LIQUIDACION_PROCESADA IS 'Indicador de registro procesado por la Liquidacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.CONTRAVALOR_BOLIVARES_CAPITAL IS 'Columna de monto capital en bolivares';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.IND_TITULO_PROCESADO IS 'Indicador de Titulo procesado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.CLIENT_ID_OFERTA IS 'Id del cliente Ofertante';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.ORDENE_ID_BCV_OFERTA IS 'IDENTIFICADOR ENVIADO POR EL BCV ASOCIADO A LA OFERTA';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.ORDENE_ESTATUS_BCV IS '0 = Sin Verificar, 1 = Enviada y Aprobada por BCV, 2 = Enviada y Rechazada por BCV';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.ORDENE_ID_PACTO_BCV IS 'IDENTIFICADOR ENVIADO POR EL BCV ASOCIADO AL PACTO';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.ORDENE_ID_OFERTA IS 'Id de la orden de Oferta';

COMMENT ON COLUMN ADM_INFI.INFI_TB_229_ORDENES_CRUCES.UNDINV_ID_OFERTA IS 'Id de la unidad de inversion de oferta 0 valor por defecto';

--
-- INFI_TB_229_ESTATUS  (Index) 
--
CREATE INDEX ADM_INFI.INFI_TB_229_ESTATUS ON ADM_INFI.INFI_TB_229_ORDENES_CRUCES
(ESTATUS)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_229_ORDENE_ID_OFERTA  (Index) 
--
CREATE INDEX ADM_INFI.INFI_TB_229_ORDENE_ID_OFERTA ON ADM_INFI.INFI_TB_229_ORDENES_CRUCES
(ORDENE_ID_OFERTA)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--
-- INFI_TB_229_NRO_OPERACION  (Index) 
--
CREATE INDEX ADM_INFI.INFI_TB_229_NRO_OPERACION ON ADM_INFI.INFI_TB_229_ORDENES_CRUCES
(NRO_OPERACION)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_229_ORDENE_ID  (Index) 
--
CREATE INDEX ADM_INFI.INFI_TB_229_ORDENE_ID ON ADM_INFI.INFI_TB_229_ORDENES_CRUCES
(ORDENE_ID)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 8 INSTANCES 1 );

--
-- INFI_TB_229_UNDINV_ID  (Index) 
--
CREATE INDEX ADM_INFI.INFI_TB_229_UNDINV_ID ON ADM_INFI.INFI_TB_229_ORDENES_CRUCES
(UNDINV_ID)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 8 INSTANCES 1 );

--
-- INFI_TB_229_INDICADOR_TITULO  (Index) 
--
CREATE INDEX ADM_INFI.INFI_TB_229_INDICADOR_TITULO ON ADM_INFI.INFI_TB_229_ORDENES_CRUCES
(INDICADOR_TITULO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 8 INSTANCES 1 );

--
-- INFI_TB_229_ORDENE_ID_BCV  (Index) 
--
CREATE INDEX ADM_INFI.INFI_TB_229_ORDENE_ID_BCV ON ADM_INFI.INFI_TB_229_ORDENES_CRUCES
(ORDENE_ID_BCV)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_229_ORDENES_CRUCES  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_229_ORDENES_CRUCES FOR ADM_INFI.INFI_TB_229_ORDENES_CRUCES;

GRANT DELETE ON  ADM_INFI.INFI_TB_229_ORDENES_CRUCES TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_229_ORDENES_CRUCES TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_229_ORDENES_CRUCES TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_229_ORDENES_CRUCES TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_229_ORDENES_CRUCES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_229_ORDENES_CRUCES ADD (
  PRIMARY KEY
 (ID_CRUCE)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


