--
-- INFI_TB_118_TITULOS_PRECIOS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_118_TITULOS_PRECIOS
(
  TITULO_ID                VARCHAR2(25 BYTE)    NOT NULL,
  TITULOS_PRECIO_NOMINAL   NUMBER(14,6)         NOT NULL,
  TITULOS_PRECIO_MERCADO   NUMBER(14,6)         NOT NULL,
  TITULOS_PRECIO_RECOMPRA  NUMBER(14,6)         NOT NULL,
  USUARIO_ID_APROBADOR     VARCHAR2(15 BYTE),
  FECHA_APROBACION         DATE,
  TIPO_PRODUCTO_ID         VARCHAR2(10 BYTE)    NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_118_TITULOS_PRECIOS IS 'Contiene los precios por los que ha pasado un título';

COMMENT ON COLUMN ADM_INFI.INFI_TB_118_TITULOS_PRECIOS.TITULO_ID IS 'Id del título';

COMMENT ON COLUMN ADM_INFI.INFI_TB_118_TITULOS_PRECIOS.TITULOS_PRECIO_NOMINAL IS 'Precio nominal';

COMMENT ON COLUMN ADM_INFI.INFI_TB_118_TITULOS_PRECIOS.TITULOS_PRECIO_MERCADO IS 'Precio Mercado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_118_TITULOS_PRECIOS.TITULOS_PRECIO_RECOMPRA IS 'Precio Recompra';

--
-- PK_118  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_118 ON ADM_INFI.INFI_TB_118_TITULOS_PRECIOS
(TITULO_ID, TIPO_PRODUCTO_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_118_TITULOS_PRECIOS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_118_TITULOS_PRECIOS FOR ADM_INFI.INFI_TB_118_TITULOS_PRECIOS;

GRANT DELETE ON  ADM_INFI.INFI_TB_118_TITULOS_PRECIOS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_118_TITULOS_PRECIOS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_118_TITULOS_PRECIOS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_118_TITULOS_PRECIOS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_118_TITULOS_PRECIOS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_118_TITULOS_PRECIOS ADD (
  CONSTRAINT PK_118
 PRIMARY KEY
 (TITULO_ID, TIPO_PRODUCTO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


