--
-- INFI_TB_907_AUDITORIA  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_907_AUDITORIA
(
  ID_AUDITORIA  NUMBER(15)                      NOT NULL,
  DIRECCION_IP  VARCHAR2(20 BYTE),
  FECHA         DATE,
  USUARIO       VARCHAR2(15 BYTE),
  PETICION      VARCHAR2(60 BYTE),
  DETALLE       VARCHAR2(100 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_907_AUDITORIA IS 'Tabla de auditoria de procesos';

COMMENT ON COLUMN ADM_INFI.INFI_TB_907_AUDITORIA.ID_AUDITORIA IS 'Identificador del registro de auditoria';

COMMENT ON COLUMN ADM_INFI.INFI_TB_907_AUDITORIA.DIRECCION_IP IS 'Direccion IP de la maquina desde la que se realizo la peticion del proceso';

COMMENT ON COLUMN ADM_INFI.INFI_TB_907_AUDITORIA.FECHA IS 'Fecha en la cual se realizo la peticion del proceso';

COMMENT ON COLUMN ADM_INFI.INFI_TB_907_AUDITORIA.USUARIO IS 'Usuario que realiza la solicitud de ejecucion del proceso';

COMMENT ON COLUMN ADM_INFI.INFI_TB_907_AUDITORIA.PETICION IS 'El tipo de peticion o proceso que se esta ejecutando';

COMMENT ON COLUMN ADM_INFI.INFI_TB_907_AUDITORIA.DETALLE IS 'Mensaje con algun detalle pertinente al proceso que se esta ejecutando';

--
-- INFI_TB_907_AUDITORIA  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_907_AUDITORIA FOR ADM_INFI.INFI_TB_907_AUDITORIA;

GRANT DELETE ON  ADM_INFI.INFI_TB_907_AUDITORIA TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_907_AUDITORIA TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_907_AUDITORIA TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_907_AUDITORIA TO USU_INFI;

