--
-- INFI_TB_232_ORDENES_TAQUILLA  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA
(
  ORDENE_TAQ_ID                  NUMBER(10)     NOT NULL,
  ORDENE_ID                      NUMBER         NOT NULL,
  ORDENE_TAQ_CLIENT_ID           NUMBER         NOT NULL,
  ORDENE_TAQ_CLIENT_CERIF        NUMBER(10)     NOT NULL,
  ORDENE_TAQ_TIPPER_ID           VARCHAR2(1 BYTE) NOT NULL,
  ORDENE_TAQ_TIPO_OPERA          NUMBER(1)      NOT NULL,
  ORDENE_TAQ_NRO_RETEN_CAP       VARCHAR2(10 BYTE) NOT NULL,
  ORDENE_TAQ_NRO_RETEN_REV_CAP   VARCHAR2(10 BYTE),
  ORDENE_TAQ_CODIGO_OPERA_CAP    VARCHAR2(10 BYTE) NOT NULL,
  ORDENE_TAQ_NRO_RETEN_COM       VARCHAR2(10 BYTE) NOT NULL,
  ORDENE_TAQ_NRO_RETEN_REV_COM   VARCHAR2(10 BYTE),
  ORDENE_TAQ_CODIGO_OPERA_COM    VARCHAR2(10 BYTE) NOT NULL,
  ORDENE_TAQ_CLIENT_NOMBRE       VARCHAR2(100 BYTE) NOT NULL,
  ORDENE_TAQ_UNDINV_ID           NUMBER(10)     NOT NULL,
  ORDENE_TAQ_INST_FINA_ID        VARCHAR2(25 BYTE) NOT NULL,
  ORDENE_TAQ_MONTO_CAP_DIVISA    NUMBER(15,4)   NOT NULL,
  ORDENE_TAQ_MONTO_COM_DIVISA    NUMBER(15,4)   NOT NULL,
  ORDENE_TAQ_MONTO_ADJ_DIVISA    NUMBER(15,4),
  ORDENE_TAQ_MONTO_TOTAL_DIVISA  NUMBER(15,4)   NOT NULL,
  ORDENE_TAQ_MONTO_CAP_BS        NUMBER(15,4)   NOT NULL,
  ORDENE_TAQ_MONTO_COM_BS        NUMBER(15,4)   NOT NULL,
  ORDENE_TAQ_MONTO_ADJ_BS        NUMBER(15,4)   NOT NULL,
  ORDENE_TAQ_MONTO_TOTAL_BS      NUMBER(15,4)   NOT NULL,
  ORDENE_TAQ_TASA_CAMBIO         NUMBER(15,4)   NOT NULL,
  ORDENE_TAQ_CTA_DIVISAS         VARCHAR2(20 BYTE),
  ORDENE_TAQ_CTA_BS              VARCHAR2(20 BYTE) NOT NULL,
  ORDENE_TAQ_TEL_CLIENT          VARCHAR2(15 BYTE) NOT NULL,
  ORDENE_TAQ_CORREO_CLIENT       VARCHAR2(100 BYTE) NOT NULL,
  ORDENE_TAQ_FE_REGISTRO         DATE           NOT NULL,
  ORDENE_TAQ_FE_VALOR            DATE           NOT NULL,
  ORDENE_TAQ_OBSERVACION         VARCHAR2(1000 BYTE),
  ORDENE_TAQ_ESTATUS             NUMBER(1)      NOT NULL,
  ORDENE_TAQ_ESTATUS_BCV         NUMBER(1)      DEFAULT 0                     NOT NULL,
  ORDENE_TAQ_ORDENE_ID_BCV       VARCHAR2(20 BYTE),
  ORDENE_TAQ_VIGENCIA            NUMBER(1)      NOT NULL,
  ORDENE_TAQ_TIPO_DIVISA         NUMBER(1)      NOT NULL,
  ORDENE_TAQ_NRO_REFERENCIA      VARCHAR2(13 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA IS 'Tabla creada para guardar originalmente las operaciones realizadas con el producto de SIMADI-VENTA EN TAQUILLA. Pero se puede usar para guardar otro tipo de operaciones para eso esta el campo ORDENE_TAQ_TIPO_OPERA. ';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_ORDENE_ID_BCV IS 'Guarda la referencia interna suministrada por el BCV';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_ESTATUS_BCV IS '0 = Sin Verificar, 1 = Enviada y Aprobada por BCV, 2 = Enviada y Rechazada por BCV';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_ID IS 'Secuencia para para el numero de orden de taquilla';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_ID IS 'Numero de orden de la tabla 204';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_CLIENT_ID IS 'Id del cliente de la tabla 201';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_CLIENT_CERIF IS 'Rif del cliente sin incluir tipo de persona';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_TIPPER_ID IS 'Tipo de persona ejemplo V o E. ';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_TIPO_OPERA IS 'Indica el tipo de operacion 1 = Electronico, 2= Efectivo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_NRO_RETEN_CAP IS 'Indica el numero de retencion para el capital';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_NRO_RETEN_REV_CAP IS 'Indica el numero de retencion de TF, en caso que TF haga la retencion por no poder debitar luego de desbloquear para el capital';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_CODIGO_OPERA_CAP IS 'Código de operacion del bloqueo del capital';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_NRO_RETEN_COM IS 'Indica el numero de retencion para la comision';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_NRO_RETEN_REV_COM IS 'Indica el numero de retencion de TF, en caso que TF haga la retencion por no poder debitar luego de desbloquear para la comision';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_CODIGO_OPERA_COM IS 'Código de operacion del bloqueo de la comision';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_CLIENT_NOMBRE IS 'Nombre completo del cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_UNDINV_ID IS 'Id de la unidad de inversion de la tabla 106';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_INST_FINA_ID IS 'Id del instrumento financiero de la tabla 101';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_MONTO_CAP_DIVISA IS 'Monto capital en divisa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_MONTO_COM_DIVISA IS 'Monto comision en divisa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_MONTO_ADJ_DIVISA IS 'Monto adjudicado en divisa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_MONTO_TOTAL_DIVISA IS 'Monto total divisa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_MONTO_CAP_BS IS 'Monto capital en bolivares';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_MONTO_COM_BS IS 'Monto comision en bolivares';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_MONTO_ADJ_BS IS 'Monto adjudicado en bolivares';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_MONTO_TOTAL_BS IS 'Monto total en bolivares';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_TASA_CAMBIO IS 'Tasa de cambio de la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_CTA_DIVISAS IS 'Numero de cuenta en divisas del cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_CTA_BS IS 'Numero de cuenta en bolivares del cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_TEL_CLIENT IS 'Telefono del cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_CORREO_CLIENT IS 'Correo del cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_FE_REGISTRO IS 'Fecha de registro de la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_FE_VALOR IS 'Fecha valor de la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_OBSERVACION IS 'Observacion de la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_ESTATUS IS 'Estatus de la operacion. 0 = No liquidada. 1 = Liquidada X TF. 2 = Reversada X TF, 3 = Liquidada INFI';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_VIGENCIA IS 'Indica la orden se encuentra vigente 1 = Vijente, 0 = Vencida';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_TIPO_DIVISA IS 'Indica el tipo de la divisa. 1 = Dolar';

COMMENT ON COLUMN ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA.ORDENE_TAQ_NRO_REFERENCIA IS 'Indica el numero de referencia enviado por pasivos para la operacion una vez que se liquida';

--
-- PK_232_ORDENE_TAQ_ID  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_232_ORDENE_TAQ_ID ON ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA
(ORDENE_TAQ_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- IDX_CONSULTA_TAQUILLA  (Index) 
--
CREATE INDEX ADM_INFI.IDX_CONSULTA_TAQUILLA ON ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA
(ORDENE_TAQ_UNDINV_ID, TO_DATE(TO_CHAR("ORDENE_TAQ_FE_REGISTRO",'dd/MM/yyyy'),'dd/MM/yyyy'), ORDENE_TAQ_ESTATUS_BCV)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- IDX_CONSULTA_TAQUILLA_NRO_REFE  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.IDX_CONSULTA_TAQUILLA_NRO_REFE ON ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA
(ORDENE_TAQ_NRO_REFERENCIA)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- TRIG_INFI_TB_232_SEC  (Trigger) 
--
CREATE OR REPLACE TRIGGER ADM_INFI.TRIG_INFI_TB_232_SEC
BEFORE INSERT ON ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA FOR EACH ROW
BEGIN
SELECT INFI_SQ_232.NEXTVAL INTO :NEW.ORDENE_TAQ_ID FROM DUAL;
END;
/
SHOW ERRORS;


--
-- INFI_TB_232_ORDENES_TAQUILLA  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_232_ORDENES_TAQUILLA FOR ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA;

GRANT UPDATE ON  ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA TO TF_INFI;

GRANT DELETE ON  ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_232_ORDENES_TAQUILLA 
-- 
ALTER TABLE ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA ADD (
  CONSTRAINT PK_232_ORDENE_TAQ_ID
 PRIMARY KEY
 (ORDENE_TAQ_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_232_ORDENES_TAQUILLA 
-- 
ALTER TABLE ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA ADD (
  CONSTRAINT FK_232_204_ORD_ID 
 FOREIGN KEY (ORDENE_ID) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));

ALTER TABLE ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA ADD (
  CONSTRAINT FK_232_106_UNDINV_ID 
 FOREIGN KEY (ORDENE_TAQ_UNDINV_ID) 
 REFERENCES ADM_INFI.INFI_TB_106_UNIDAD_INVERSION (UNDINV_ID));

ALTER TABLE ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA ADD (
  CONSTRAINT FK_232_101_INSFN_ID 
 FOREIGN KEY (ORDENE_TAQ_INST_FINA_ID) 
 REFERENCES ADM_INFI.INFI_TB_101_INST_FINANCIEROS (INSFIN_ID));

ALTER TABLE ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA ADD (
  CONSTRAINT FK_232_201_TIPPER_CEDRIF 
 FOREIGN KEY (ORDENE_TAQ_CLIENT_CERIF, ORDENE_TAQ_TIPPER_ID) 
 REFERENCES ADM_INFI.INFI_TB_201_CTES (CLIENT_CEDRIF,TIPPER_ID));

ALTER TABLE ADM_INFI.INFI_TB_232_ORDENES_TAQUILLA ADD (
  CONSTRAINT FK_232_101_CLIENT_ID 
 FOREIGN KEY (ORDENE_TAQ_CLIENT_ID) 
 REFERENCES ADM_INFI.INFI_TB_201_CTES (CLIENT_ID));


