--
-- INFI_TB_038_INST_FORMA_ORDEN  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_038_INST_FORMA_ORDEN
(
  INSFIN_FORMA_ORDEN       VARCHAR2(15 BYTE)    NOT NULL,
  INSFIN_FORMA_ORDEN_DESC  VARCHAR2(100 BYTE)   NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- INFI_TB_038_INST_FORMA_ORDEN  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_038_INST_FORMA_ORDEN FOR ADM_INFI.INFI_TB_038_INST_FORMA_ORDEN;

GRANT DELETE ON  ADM_INFI.INFI_TB_038_INST_FORMA_ORDEN TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_038_INST_FORMA_ORDEN TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_038_INST_FORMA_ORDEN TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_038_INST_FORMA_ORDEN TO USU_INFI;

