--
-- INFI_TB_213_FACTURA  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_213_FACTURA
(
  CLIENT_ID   NUMBER(8)                         NOT NULL,
  FACTURA_ID  NUMBER(10)                        NOT NULL,
  FECHA_FACT  DATE                              NOT NULL,
  MONTO       NUMBER(10,2)                      NOT NULL,
  ORDENE_ID   NUMBER(10)                        NOT NULL,
  FECHA_MES   DATE                              NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_213_FACTURA IS 'Refleja la factura generada para el cobro de comisiones';

COMMENT ON COLUMN ADM_INFI.INFI_TB_213_FACTURA.CLIENT_ID IS 'Id del cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_213_FACTURA.FACTURA_ID IS 'Número de factura';

COMMENT ON COLUMN ADM_INFI.INFI_TB_213_FACTURA.FECHA_FACT IS 'Fecha de generación de la factura';

COMMENT ON COLUMN ADM_INFI.INFI_TB_213_FACTURA.MONTO IS 'Monto';

COMMENT ON COLUMN ADM_INFI.INFI_TB_213_FACTURA.ORDENE_ID IS 'Número de orden asociada a la facturación';

COMMENT ON COLUMN ADM_INFI.INFI_TB_213_FACTURA.FECHA_MES IS 'Fecha del mes calculado';

--
-- PK_213  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_213 ON ADM_INFI.INFI_TB_213_FACTURA
(FACTURA_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_213_FACTURA  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_213_FACTURA FOR ADM_INFI.INFI_TB_213_FACTURA;

GRANT DELETE ON  ADM_INFI.INFI_TB_213_FACTURA TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_213_FACTURA TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_213_FACTURA TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_213_FACTURA TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_213_FACTURA 
-- 
ALTER TABLE ADM_INFI.INFI_TB_213_FACTURA ADD (
  CONSTRAINT PK_213
 PRIMARY KEY
 (FACTURA_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_213_FACTURA 
-- 
ALTER TABLE ADM_INFI.INFI_TB_213_FACTURA ADD (
  CONSTRAINT FK_213_204 
 FOREIGN KEY (ORDENE_ID) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));

ALTER TABLE ADM_INFI.INFI_TB_213_FACTURA ADD (
  CONSTRAINT FK_213_201 
 FOREIGN KEY (CLIENT_ID) 
 REFERENCES ADM_INFI.INFI_TB_201_CTES (CLIENT_ID));


