--
-- INFI_TB_209_ORDENES_OPERAC_INT  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT
(
  ORDENE_ID             NUMBER(10)              NOT NULL,
  ORDENE_OPERACION_ID   NUMBER(9)               NOT NULL,
  OPERACION_INTENTO_ID  NUMBER(7)               NOT NULL,
  FECHA                 DATE                    NOT NULL,
  APLICO                CHAR(1 BYTE)            NOT NULL,
  ERROR_DESC            VARCHAR2(500 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT IS 'Indica los intentos aplicados a una operación de transacción financiera';

COMMENT ON COLUMN ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT.ORDENE_ID IS 'Id de la orden';

COMMENT ON COLUMN ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT.ORDENE_OPERACION_ID IS 'Id de relación de la operación';

COMMENT ON COLUMN ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT.OPERACION_INTENTO_ID IS 'Id que identifica el registro';

COMMENT ON COLUMN ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT.FECHA IS 'Fecha del intento de operación';

COMMENT ON COLUMN ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT.APLICO IS '0 Indica no aplicó, 1 si la operación fue existosa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT.ERROR_DESC IS 'Descripción del error del por que no aplicó la operación';

--
-- PK_209  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_209 ON ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT
(ORDENE_ID, ORDENE_OPERACION_ID, OPERACION_INTENTO_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_209_ORDENES_OPERAC_INT  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_209_ORDENES_OPERAC_INT FOR ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT;

GRANT DELETE ON  ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_209_ORDENES_OPERAC_INT 
-- 
ALTER TABLE ADM_INFI.INFI_TB_209_ORDENES_OPERAC_INT ADD (
  CONSTRAINT PK_209
 PRIMARY KEY
 (ORDENE_ID, ORDENE_OPERACION_ID, OPERACION_INTENTO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


