--
-- INFI_TB_854_EVENTO_INTERFAZ  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_854_EVENTO_INTERFAZ
(
  EVENTO_ID       NUMBER(10)                    NOT NULL,
  PARGRP_ID       VARCHAR2(3 BYTE)              NOT NULL,
  ARCH_NAME       VARCHAR2(90 BYTE)             NOT NULL,
  FECHA_CREACION  DATE,
  USER_CREACION   VARCHAR2(25 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ADM_INFI.INFI_TB_854_EVENTO_INTERFAZ.EVENTO_ID IS 'ID del evento';

COMMENT ON COLUMN ADM_INFI.INFI_TB_854_EVENTO_INTERFAZ.PARGRP_ID IS 'ID del grupo de parametros que se corresponde con la interfaz';

--
-- INFI_TB_854_EVENTO_INTERFAZ_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.INFI_TB_854_EVENTO_INTERFAZ_PK ON ADM_INFI.INFI_TB_854_EVENTO_INTERFAZ
(EVENTO_ID, PARGRP_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_854_EVENTO_INTERFAZ 
-- 
ALTER TABLE ADM_INFI.INFI_TB_854_EVENTO_INTERFAZ ADD (
  CONSTRAINT PK_854
 PRIMARY KEY
 (EVENTO_ID, PARGRP_ID));


-- 
-- Foreign Key Constraints for Table INFI_TB_854_EVENTO_INTERFAZ 
-- 
ALTER TABLE ADM_INFI.INFI_TB_854_EVENTO_INTERFAZ ADD (
  CONSTRAINT FK_854_851 
 FOREIGN KEY (EVENTO_ID) 
 REFERENCES ADM_INFI.INFI_TB_851_EVENTO_CONTABLE (EVENTO_ID));

ALTER TABLE ADM_INFI.INFI_TB_854_EVENTO_INTERFAZ ADD (
  CONSTRAINT FK_854_001 
 FOREIGN KEY (PARGRP_ID) 
 REFERENCES ADM_INFI.INFI_TB_001_PARAM_GRUPO (PARGRP_ID));


