--
-- INFI_TB_811_INST_OPERACION  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_811_INST_OPERACION
(
  INSTRUCCION_ID             NUMBER(10)         NOT NULL,
  PROCESO_ID                 NUMBER(8)          NOT NULL,
  STATUS_OPERACION           VARCHAR2(25 BYTE)  NOT NULL,
  CEDULA_BENEFICIARIO        VARCHAR2(10 BYTE),
  NOMBRE_BENEFICIARIO        VARCHAR2(100 BYTE),
  MONTO_INSTRUCCION          NUMBER(13,4)       NOT NULL,
  MONEDA_ID                  VARCHAR2(3 BYTE)   NOT NULL,
  NUMERO_CHEQUE              VARCHAR2(25 BYTE),
  FECHA_OPERACION            DATE               NOT NULL,
  FECHA_APLICACION           DATE,
  FECHA_VALOR                DATE               NOT NULL,
  CTECTA_NUMERO              VARCHAR2(34 BYTE),
  CTECTA_NOMBRE              VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_BCO          VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_DIRECCION    VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_SWIFT        VARCHAR2(50 CHAR),
  CTECTA_BCOCTA_BIC          VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_TELEFONO     VARCHAR2(50 BYTE),
  CTECTA_BCOCTA_ABA          VARCHAR2(50 BYTE),
  CTECTA_BCOINT_BCO          VARCHAR2(50 BYTE),
  CTECTA_BCOINT_DIRECCION    VARCHAR2(50 BYTE),
  CTECTA_BCOINT_SWIFT        VARCHAR2(50 BYTE),
  CTECTA_BCOINT_BIC          VARCHAR2(50 BYTE),
  CTECTA_BCOINT_TELEFONO     VARCHAR2(50 BYTE),
  CTECTA_BCOINT_ABA          VARCHAR2(50 BYTE),
  CTECTA_OBSERVACION         VARCHAR2(210 BYTE),
  CTECTA_BCOINT_OBSERVACION  VARCHAR2(210 BYTE),
  TASA_CAMBIO                NUMBER(9,6),
  TIPO_INSTRUCCION_ID        NUMBER(1)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- INFI_TB_811_INST_OPERACION  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_811_INST_OPERACION FOR ADM_INFI.INFI_TB_811_INST_OPERACION;

GRANT DELETE ON  ADM_INFI.INFI_TB_811_INST_OPERACION TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_811_INST_OPERACION TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_811_INST_OPERACION TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_811_INST_OPERACION TO USU_INFI;

-- 
-- Foreign Key Constraints for Table INFI_TB_811_INST_OPERACION 
-- 
ALTER TABLE ADM_INFI.INFI_TB_811_INST_OPERACION ADD (
  CONSTRAINT INFI_TB_811_INST_OPERACION_R01 
 FOREIGN KEY (TIPO_INSTRUCCION_ID) 
 REFERENCES ADM_INFI.INFI_TB_045_TIPO_INSTRUCCION (TIPO_INSTRUCCION_ID));


