--
-- INFI_TB_704_TITULOS_BLOQUEO  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO
(
  TITULO_ID         VARCHAR2(25 BYTE)           NOT NULL,
  CLIENT_ID         NUMBER(8)                   NOT NULL,
  TIPBLO_ID         VARCHAR2(25 BYTE)           NOT NULL,
  BENEFICIARIO_ID   NUMBER(3)                   NOT NULL,
  TITCUS_CANTIDAD   NUMBER(12)                  NOT NULL,
  FECHA             DATE                        NOT NULL,
  NUMERO_GARANTIA   VARCHAR2(20 BYTE),
  TIPO_PRODUCTO_ID  VARCHAR2(10 BYTE)           NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO IS 'Tabla que hace referencia a los títulos que se encuentran bloqueados.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO.TITULO_ID IS 'Id del título';

COMMENT ON COLUMN ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO.CLIENT_ID IS 'Id del cliente dueño del título';

COMMENT ON COLUMN ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO.TIPBLO_ID IS 'Tipo de bloqueo aplicado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO.BENEFICIARIO_ID IS 'Id del beneficiario';

COMMENT ON COLUMN ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO.TITCUS_CANTIDAD IS 'Cantidad de títulos bloqueados';

COMMENT ON COLUMN ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO.FECHA IS 'Fecha de bloqueo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO.NUMERO_GARANTIA IS 'Número de garantía';

COMMENT ON COLUMN ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO.TIPO_PRODUCTO_ID IS 'Tipo de producto asociado';

--
-- PK_704T  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_704T ON ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO
(TITULO_ID, TIPO_PRODUCTO_ID, CLIENT_ID, TIPBLO_ID, BENEFICIARIO_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_BLOQUEO_HISTORICO  (Trigger) 
--
CREATE OR REPLACE TRIGGER ADM_INFI."INFI_BLOQUEO_HISTORICO" 
 AFTER
 INSERT OR UPDATE
 ON ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
DECLARE
  TASA_CAMBIO       INFI_TB_705_TITULOS_BLOQ_HIST.tasa_cambio%type;

BEGIN
  select tcc_tasa_cambio_compra
  into   TASA_CAMBIO
  from   infi_vi_tasa_cam_cierre_diario,
         (select titulo_moneda_den "moneda_den"
          from infi_tb_100_titulos
          where titulo_id=:NEW.TITULO_ID)
  where   tcc_codigo_divisa ="moneda_den";

  UPDATE INFI_TB_705_TITULOS_BLOQ_HIST tb
  SET    tb.TITCUS_CANTIDAD = :NEW.TITCUS_CANTIDAD,tb.TASA_CAMBIO = TASA_CAMBIO
  WHERE  tb.TITULO_ID = :NEW.TITULO_ID
  AND    tb.CLIENT_ID = :NEW.CLIENT_ID
  AND    tb.TIPBLO_ID = :NEW.TIPBLO_ID
  AND    tb.BENEFICIARIO_ID = :NEW.BENEFICIARIO_ID
  AND    trunc(tb.FECHA) = trunc(sysdate)
  AND    tb.TIPO_PRODUCTO_ID = :NEW.TIPO_PRODUCTO_ID;
  IF sql%notfound THEN
     INSERT INTO INFI_TB_705_TITULOS_BLOQ_HIST (TITULO_ID,CLIENT_ID,TIPBLO_ID,BENEFICIARIO_ID,TITCUS_CANTIDAD,
                                                FECHA,NUMERO_GARANTIA,TASA_CAMBIO,TIPO_PRODUCTO_ID)
       VALUES (:NEW.TITULO_ID, :NEW.CLIENT_ID, :NEW.TIPBLO_ID, :NEW.BENEFICIARIO_ID, :NEW.TITCUS_CANTIDAD,
               SYSDATE,:NEW.NUMERO_GARANTIA,TASA_CAMBIO,:NEW.TIPO_PRODUCTO_ID);
  END IF;

END;
/
SHOW ERRORS;


--
-- INFI_BLOQUEO_HISTORICO_DELETE  (Trigger) 
--
CREATE OR REPLACE TRIGGER ADM_INFI."INFI_BLOQUEO_HISTORICO_DELETE" 
 BEFORE
 DELETE
 ON ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO  REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
  UPDATE INFI_TB_705_TITULOS_BLOQ_HIST tb
  SET    tb.TITCUS_CANTIDAD = 0,tb.TASA_CAMBIO = 0
  WHERE  tb.TITULO_ID = :OLD.TITULO_ID
  AND    tb.CLIENT_ID = :OLD.CLIENT_ID
  AND    tb.TIPBLO_ID = :OLD.TIPBLO_ID
  AND    tb.BENEFICIARIO_ID = :OLD.BENEFICIARIO_ID
  AND    trunc(tb.FECHA) = trunc(sysdate)
  AND    tb.TIPO_PRODUCTO_ID = :OLD.TIPO_PRODUCTO_ID;
  IF SQL%NOTFOUND THEN
     INSERT INTO INFI_TB_705_TITULOS_BLOQ_HIST (TITULO_ID,CLIENT_ID,TIPBLO_ID,BENEFICIARIO_ID,TITCUS_CANTIDAD,
                                                FECHA,NUMERO_GARANTIA,TASA_CAMBIO,TIPO_PRODUCTO_ID)
       VALUES (:OLD.TITULO_ID, :OLD.CLIENT_ID, :OLD.TIPBLO_ID, :OLD.BENEFICIARIO_ID, 0, SYSDATE,
               :OLD.NUMERO_GARANTIA,0,:OLD.TIPO_PRODUCTO_ID);
  END IF;
END;
/
SHOW ERRORS;

ALTER TRIGGER ADM_INFI.INFI_BLOQUEO_HISTORICO_DELETE DISABLE;


--
-- INFI_TB_704_TITULOS_BLOQUEO  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_704_TITULOS_BLOQUEO FOR ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO;

GRANT DELETE ON  ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_704_TITULOS_BLOQUEO 
-- 
ALTER TABLE ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO ADD (
  CONSTRAINT PK_704T
 PRIMARY KEY
 (TITULO_ID, TIPO_PRODUCTO_ID, CLIENT_ID, TIPBLO_ID, BENEFICIARIO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_704_TITULOS_BLOQUEO 
-- 
ALTER TABLE ADM_INFI.INFI_TB_704_TITULOS_BLOQUEO ADD (
  CONSTRAINT FK_704_039 
 FOREIGN KEY (BENEFICIARIO_ID) 
 REFERENCES ADM_INFI.INFI_TB_039_BENEFICIARIOS (BENEFICIARIO_ID));


