--
-- INFI_TB_804_CONTROL_ARCH_DET  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET
(
  EJECUCION_ID         NUMBER(9)                NOT NULL,
  ORDENE_ID            NUMBER(10),
  ORDENE_OPERACION_ID  NUMBER(9),
  STATUS               VARCHAR2(25 BYTE),
  ERROR                VARCHAR2(500 BYTE),
  ID_OPICS             NUMBER,
  REGISTRO_SWIFT       VARCHAR2(500 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET IS 'Detalle de las líneas escritas o leidas en los archivos de envio y recepción';

COMMENT ON COLUMN ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET.EJECUCION_ID IS 'Id de ejecución';

COMMENT ON COLUMN ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET.ORDENE_ID IS 'Id de la orden que se envió. Si aplica';

COMMENT ON COLUMN ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET.ORDENE_OPERACION_ID IS 'Id de la operación. Si aplica';

COMMENT ON COLUMN ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET.STATUS IS 'Status de lectura';

COMMENT ON COLUMN ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET.ERROR IS 'Error en el proceso de la operación de lectura';

COMMENT ON COLUMN ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET.ID_OPICS IS 'Id del registro OPICS enviado. Si aplica';

--
-- INDX_804_EJECUCION  (Index) 
--
CREATE INDEX ADM_INFI.INDX_804_EJECUCION ON ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET
(EJECUCION_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INDX_804_ACTUALIZAR  (Index) 
--
CREATE INDEX ADM_INFI.INDX_804_ACTUALIZAR ON ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET
(EJECUCION_ID, ORDENE_ID, ORDENE_OPERACION_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_804_CONTROL_ARCH_DET  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_804_CONTROL_ARCH_DET FOR ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET;

GRANT DELETE ON  ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_804_CONTROL_ARCH_DET 
-- 
ALTER TABLE ADM_INFI.INFI_TB_804_CONTROL_ARCH_DET ADD (
  CONSTRAINT PK_804
 PRIMARY KEY
 (EJECUCION_ID, ORDENE_ID, ORDENE_OPERACION_ID));


