--
-- INFI_TB_222_ORDEN_PAGO_CUPONES  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_222_ORDEN_PAGO_CUPONES
(
  ID_ORDEN_PAGO  NUMBER(10),
  ID_CUPON       NUMBER(10),
  MONTO_PAGADO   NUMBER(15,5),
  FECHA_PAGO     DATE,
  USUARIO        VARCHAR2(50 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

-- 
-- Foreign Key Constraints for Table INFI_TB_222_ORDEN_PAGO_CUPONES 
-- 
ALTER TABLE ADM_INFI.INFI_TB_222_ORDEN_PAGO_CUPONES ADD (
  FOREIGN KEY (ID_ORDEN_PAGO) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));

ALTER TABLE ADM_INFI.INFI_TB_222_ORDEN_PAGO_CUPONES ADD (
  FOREIGN KEY (ID_CUPON) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));


