--
-- INFI_TB_200_TIPO_PERSONAS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_200_TIPO_PERSONAS
(
  TIPPER_ID      VARCHAR2(1 BYTE)               NOT NULL,
  TIPPER_NOMBRE  VARCHAR2(200 BYTE)             NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_200_TIPO_PERSONAS IS 'Tipo de personas registradas. V (Venezolano) E (Extranjero), J(Juridico)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_200_TIPO_PERSONAS.TIPPER_ID IS 'Id de tipo de persona';

COMMENT ON COLUMN ADM_INFI.INFI_TB_200_TIPO_PERSONAS.TIPPER_NOMBRE IS 'Definición o descripción de tipo de persona';

--
-- PK_200  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_200 ON ADM_INFI.INFI_TB_200_TIPO_PERSONAS
(TIPPER_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_200_TIPO_PERSONAS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_200_TIPO_PERSONAS FOR ADM_INFI.INFI_TB_200_TIPO_PERSONAS;

GRANT DELETE ON  ADM_INFI.INFI_TB_200_TIPO_PERSONAS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_200_TIPO_PERSONAS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_200_TIPO_PERSONAS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_200_TIPO_PERSONAS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_200_TIPO_PERSONAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_200_TIPO_PERSONAS ADD (
  CONSTRAINT PK_200
 PRIMARY KEY
 (TIPPER_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


