--
-- INFI_TB_116_UI_OFERTA_DEMANDA  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_116_UI_OFERTA_DEMANDA
(
  UNDINV_ID_OFERTA   NUMBER(7)                  NOT NULL,
  UNDINV_ID_DEMANDA  NUMBER(7)                  NOT NULL,
  OBSERVACION        VARCHAR2(500 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_116_UI_OFERTA_DEMANDA IS 'Relacion entre unidades de inversion de Ofertas y Demandas asociadas al manejo del producto Manejo de Mercado Cambiario Abierto';

COMMENT ON COLUMN ADM_INFI.INFI_TB_116_UI_OFERTA_DEMANDA.UNDINV_ID_DEMANDA IS 'Indentificador de la unidad de inversion asociada a las solicitudes de Demanda';

COMMENT ON COLUMN ADM_INFI.INFI_TB_116_UI_OFERTA_DEMANDA.OBSERVACION IS 'Posibles observaciones';

COMMENT ON COLUMN ADM_INFI.INFI_TB_116_UI_OFERTA_DEMANDA.UNDINV_ID_OFERTA IS 'Indentificador de la unidad de inversion asociada a las solicitudes de oferta';

--
-- INFI_TB_116_UI_OFERTA_DEMANDA  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_116_UI_OFERTA_DEMANDA FOR ADM_INFI.INFI_TB_116_UI_OFERTA_DEMANDA;

GRANT DELETE ON  ADM_INFI.INFI_TB_116_UI_OFERTA_DEMANDA TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_116_UI_OFERTA_DEMANDA TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_116_UI_OFERTA_DEMANDA TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_116_UI_OFERTA_DEMANDA TO USU_INFI;

-- 
-- Foreign Key Constraints for Table INFI_TB_116_UI_OFERTA_DEMANDA 
-- 
ALTER TABLE ADM_INFI.INFI_TB_116_UI_OFERTA_DEMANDA ADD (
  CONSTRAINT FK_116_106_OFERTA 
 FOREIGN KEY (UNDINV_ID_OFERTA) 
 REFERENCES ADM_INFI.INFI_TB_106_UNIDAD_INVERSION (UNDINV_ID));

ALTER TABLE ADM_INFI.INFI_TB_116_UI_OFERTA_DEMANDA ADD (
  CONSTRAINT FK_116_106_DEMANDA 
 FOREIGN KEY (UNDINV_ID_DEMANDA) 
 REFERENCES ADM_INFI.INFI_TB_106_UNIDAD_INVERSION (UNDINV_ID));


