--
-- INFI_TB_032_TRNF_FIJAS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_032_TRNF_FIJAS
(
  TRNFIN_ID         NUMBER(2)                   NOT NULL,
  TRANSA_ID         VARCHAR2(25 BYTE)           NOT NULL,
  TRNFIN_NOMBRE     VARCHAR2(50 BYTE)           NOT NULL,
  TRNFIN_DESC       VARCHAR2(250 BYTE)          NOT NULL,
  TRNFIN_TIPO       VARCHAR2(3 BYTE)            NOT NULL,
  CODIGO_OPERACION  VARCHAR2(10 BYTE)           NOT NULL,
  MANEJO_PRODUCTOS  NUMBER(2)                   DEFAULT 0
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_032_TRNF_FIJAS IS 'Contiene las transacciones invariables que INFI usa en cada proceso interno de la aplicación. Transacciones como capital, pago de cupon, acreditación son ejemplos de estas.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_032_TRNF_FIJAS.TRNFIN_ID IS 'Id de la transacción';

COMMENT ON COLUMN ADM_INFI.INFI_TB_032_TRNF_FIJAS.TRANSA_ID IS 'Id de la transacción de negocio';

COMMENT ON COLUMN ADM_INFI.INFI_TB_032_TRNF_FIJAS.TRNFIN_NOMBRE IS 'Nombre a mostrar en las operaciones financieras';

COMMENT ON COLUMN ADM_INFI.INFI_TB_032_TRNF_FIJAS.TRNFIN_DESC IS 'Descripción de la transacción';

COMMENT ON COLUMN ADM_INFI.INFI_TB_032_TRNF_FIJAS.TRNFIN_TIPO IS 'Tipo de operación. Débito, Crédito';

COMMENT ON COLUMN ADM_INFI.INFI_TB_032_TRNF_FIJAS.CODIGO_OPERACION IS 'Código de la operación que debe enviarse a SWIFT';

COMMENT ON COLUMN ADM_INFI.INFI_TB_032_TRNF_FIJAS.MANEJO_PRODUCTOS IS 'CAMPO INDICARDOR MANEJO PRODUCTOS MIXTOS (1) O UNICO (0)';

--
-- PK_032  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_032 ON ADM_INFI.INFI_TB_032_TRNF_FIJAS
(TRNFIN_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_032_TRNF_FIJAS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_032_TRNF_FIJAS FOR ADM_INFI.INFI_TB_032_TRNF_FIJAS;

GRANT DELETE ON  ADM_INFI.INFI_TB_032_TRNF_FIJAS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_032_TRNF_FIJAS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_032_TRNF_FIJAS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_032_TRNF_FIJAS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_032_TRNF_FIJAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_032_TRNF_FIJAS ADD (
  CONSTRAINT PK_032
 PRIMARY KEY
 (TRNFIN_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_032_TRNF_FIJAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_032_TRNF_FIJAS ADD (
  CONSTRAINT FK_032_012 
 FOREIGN KEY (TRANSA_ID) 
 REFERENCES ADM_INFI.INFI_TB_012_TRANSACCIONES (TRANSA_ID));

ALTER TABLE ADM_INFI.INFI_TB_032_TRNF_FIJAS ADD (
  CONSTRAINT FK_032_805 
 FOREIGN KEY (TRNFIN_TIPO) 
 REFERENCES ADM_INFI.INFI_TB_805_TRNFIN_TIPO (TRNFIN_TIPO));


