--
-- INFI_TB_816_CONFIG_TASA  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_816_CONFIG_TASA
(
  NM_REGISTRO_TASA      VARCHAR2(15 BYTE)       NOT NULL,
  NM_APROBACION_TASA    VARCHAR2(15 BYTE),
  FECHA                 DATE                    NOT NULL,
  TASA                  NUMBER(5,2)             NOT NULL,
  TIPO_PRODUCTO_ID      VARCHAR2(10 BYTE)       NOT NULL,
  TRANSA_ID             VARCHAR2(25 BYTE)       NOT NULL,
  APROBADO              NUMBER(1)               DEFAULT 0,
  FECHA_APROBACION      DATE,
  NM_MODIFICACION_TASA  VARCHAR2(15 BYTE),
  CONFIG_TASA_ID        NUMBER(10)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_816_CONFIG_TASA IS 'Tabla de configuracion de tasas';

COMMENT ON COLUMN ADM_INFI.INFI_TB_816_CONFIG_TASA.CONFIG_TASA_ID IS 'Campon identificador del registro ID';

COMMENT ON COLUMN ADM_INFI.INFI_TB_816_CONFIG_TASA.FECHA IS 'Fecha de la tasa configurada';

COMMENT ON COLUMN ADM_INFI.INFI_TB_816_CONFIG_TASA.FECHA_APROBACION IS 'Fecha en la que se realizo la aprobacion de la tasa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_816_CONFIG_TASA.NM_APROBACION_TASA IS 'Usuario que realizo la Aprobacion de la tasa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_816_CONFIG_TASA.NM_MODIFICACION_TASA IS 'Usuario que realizo una modificacion sobre la tasa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_816_CONFIG_TASA.NM_REGISTRO_TASA IS 'Usuario que realizo el proceso de registro de la tasa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_816_CONFIG_TASA.TASA IS 'Monto de la tasa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_816_CONFIG_TASA.TIPO_PRODUCTO_ID IS 'Tipo de producto al que va asociado la tasa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_816_CONFIG_TASA.TRANSA_ID IS 'Tipo de transaccion a la que va asociada la tasa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_816_CONFIG_TASA.APROBADO IS 'Indicador de aprobacion de la tasa 1 Aprobado 0 No Aprobado';

--
-- CONFIG_TASA_ID_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.CONFIG_TASA_ID_PK ON ADM_INFI.INFI_TB_816_CONFIG_TASA
(CONFIG_TASA_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_816_CONFIG_TASA  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_816_CONFIG_TASA FOR ADM_INFI.INFI_TB_816_CONFIG_TASA;

GRANT DELETE ON  ADM_INFI.INFI_TB_816_CONFIG_TASA TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_816_CONFIG_TASA TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_816_CONFIG_TASA TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_816_CONFIG_TASA TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_816_CONFIG_TASA 
-- 
ALTER TABLE ADM_INFI.INFI_TB_816_CONFIG_TASA ADD (
  CONSTRAINT PK_816
 PRIMARY KEY
 (CONFIG_TASA_ID));


-- 
-- Foreign Key Constraints for Table INFI_TB_816_CONFIG_TASA 
-- 
ALTER TABLE ADM_INFI.INFI_TB_816_CONFIG_TASA ADD (
  CONSTRAINT FK_816_012 
 FOREIGN KEY (TRANSA_ID) 
 REFERENCES ADM_INFI.INFI_TB_012_TRANSACCIONES (TRANSA_ID));

ALTER TABLE ADM_INFI.INFI_TB_816_CONFIG_TASA ADD (
  CONSTRAINT FK_816_019 
 FOREIGN KEY (TIPO_PRODUCTO_ID) 
 REFERENCES ADM_INFI.INFI_TB_019_TIPO_DE_PRODUCTO (TIPO_PRODUCTO_ID));


