--
-- INFI_TB_802_SISTEMA  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_802_SISTEMA
(
  SISTEMA_ID      VARCHAR2(10 BYTE)             NOT NULL,
  SISTEMA_NOMBRE  VARCHAR2(25 BYTE)             NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_802_SISTEMA IS 'Los diferentes sistemas asociados para el envio de las transacciones financieras';

COMMENT ON COLUMN ADM_INFI.INFI_TB_802_SISTEMA.SISTEMA_ID IS 'Id de sistema';

COMMENT ON COLUMN ADM_INFI.INFI_TB_802_SISTEMA.SISTEMA_NOMBRE IS 'Nombre del sistema';

--
-- PK_802  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_802 ON ADM_INFI.INFI_TB_802_SISTEMA
(SISTEMA_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_802_SISTEMA  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_802_SISTEMA FOR ADM_INFI.INFI_TB_802_SISTEMA;

GRANT DELETE ON  ADM_INFI.INFI_TB_802_SISTEMA TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_802_SISTEMA TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_802_SISTEMA TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_802_SISTEMA TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_802_SISTEMA 
-- 
ALTER TABLE ADM_INFI.INFI_TB_802_SISTEMA ADD (
  CONSTRAINT PK_802
 PRIMARY KEY
 (SISTEMA_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


