--
-- INFI_TB_206_ORDENES_TITULOS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_206_ORDENES_TITULOS
(
  ORDENE_ID              NUMBER(10)             NOT NULL,
  TITULO_ID              VARCHAR2(25 BYTE)      NOT NULL,
  TITULO_PCT             NUMBER(10,7),
  TITULO_MONTO           NUMBER(10)             NOT NULL,
  TITULO_UNIDADES        NUMBER(10)             NOT NULL,
  TITULO_PCT_RECOMPRA    NUMBER(9,6),
  TITULO_PRECIO_MERCADO  NUMBER(9,6),
  TITULO_MTO_INT_CAIDOS  NUMBER(15,6),
  TITULO_MTO_NETEO       NUMBER(15,6)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_206_ORDENES_TITULOS IS 'Los títulos asociados a una orden en un proceso de transacción. 
Si la transacción es de Toma de Orden aparecerá reflejado que títulos se desean comprar.
Si la transacción es de Venta aparecerán que título y la cantidad que se desea vender';

COMMENT ON COLUMN ADM_INFI.INFI_TB_206_ORDENES_TITULOS.ORDENE_ID IS 'Id de la orden';

COMMENT ON COLUMN ADM_INFI.INFI_TB_206_ORDENES_TITULOS.TITULO_ID IS 'Id del título involucrado en el proceso';

COMMENT ON COLUMN ADM_INFI.INFI_TB_206_ORDENES_TITULOS.TITULO_PCT IS 'Porcentaje usado para el título en el momento de la compra';

COMMENT ON COLUMN ADM_INFI.INFI_TB_206_ORDENES_TITULOS.TITULO_MONTO IS 'Monto de la compra o venta del título';

COMMENT ON COLUMN ADM_INFI.INFI_TB_206_ORDENES_TITULOS.TITULO_UNIDADES IS 'Unidades compradas o vendidas';

COMMENT ON COLUMN ADM_INFI.INFI_TB_206_ORDENES_TITULOS.TITULO_PCT_RECOMPRA IS 'Precio de recompra';

COMMENT ON COLUMN ADM_INFI.INFI_TB_206_ORDENES_TITULOS.TITULO_PRECIO_MERCADO IS 'Precio de mercado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_206_ORDENES_TITULOS.TITULO_MTO_INT_CAIDOS IS 'Monto de los intereses caidos generados por título';

--
-- PK_206  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_206 ON ADM_INFI.INFI_TB_206_ORDENES_TITULOS
(ORDENE_ID, TITULO_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INX_206_ORDENE_ID  (Index) 
--
CREATE INDEX ADM_INFI.INX_206_ORDENE_ID ON ADM_INFI.INFI_TB_206_ORDENES_TITULOS
(ORDENE_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_206_ORDENES_TITULOS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_206_ORDENES_TITULOS FOR ADM_INFI.INFI_TB_206_ORDENES_TITULOS;

GRANT DELETE ON  ADM_INFI.INFI_TB_206_ORDENES_TITULOS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_206_ORDENES_TITULOS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_206_ORDENES_TITULOS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_206_ORDENES_TITULOS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_206_ORDENES_TITULOS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_206_ORDENES_TITULOS ADD (
  CONSTRAINT PK_206
 PRIMARY KEY
 (ORDENE_ID, TITULO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_206_ORDENES_TITULOS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_206_ORDENES_TITULOS ADD (
  CONSTRAINT FK_206_204 
 FOREIGN KEY (ORDENE_ID) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));


