--
-- INFI_TB_221_ORDENES_SWIFT  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_221_ORDENES_SWIFT
(
  ID_SWIFT              NUMBER(10)              NOT NULL,
  ID_ORDEN_TOMA_ORDEN   NUMBER(10)              NOT NULL,
  ID_ORDEN_RELACIONADA  NUMBER(10)              NOT NULL,
  ORDENE_OPERACION_ID   NUMBER(9)               NOT NULL,
  DETALLE_SWIFT         VARCHAR2(1000 BYTE),
  TIPO_MENSAJE          VARCHAR2(100 BYTE),
  FECHA_ENVIO           DATE
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_221_ORDENES_SWIFT IS 'Contiene el contenido de los mensajes SWIFTS enviados asociados a una orden y operacion específica';

COMMENT ON COLUMN ADM_INFI.INFI_TB_221_ORDENES_SWIFT.ID_ORDEN_RELACIONADA IS 'Id de la orden relacionada a la original (ORDEN_PAGO y otros)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_221_ORDENES_SWIFT.ORDENE_OPERACION_ID IS 'Id de la operaciones relacionada al pago de divisas';

COMMENT ON COLUMN ADM_INFI.INFI_TB_221_ORDENES_SWIFT.DETALLE_SWIFT IS 'Detalle del mensaje Swift enviado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_221_ORDENES_SWIFT.TIPO_MENSAJE IS 'Definicion del tipo de mensaje (Tipo mensajes MT)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_221_ORDENES_SWIFT.FECHA_ENVIO IS 'Fecha de envio del mensaje Swift';

COMMENT ON COLUMN ADM_INFI.INFI_TB_221_ORDENES_SWIFT.ID_SWIFT IS 'Identificador del emnsaje Swift';

COMMENT ON COLUMN ADM_INFI.INFI_TB_221_ORDENES_SWIFT.ID_ORDEN_TOMA_ORDEN IS 'Id de la orden original (TOMA_ORDEN)';


GRANT DELETE ON  ADM_INFI.INFI_TB_221_ORDENES_SWIFT TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_221_ORDENES_SWIFT TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_221_ORDENES_SWIFT TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_221_ORDENES_SWIFT TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_221_ORDENES_SWIFT 
-- 
ALTER TABLE ADM_INFI.INFI_TB_221_ORDENES_SWIFT ADD (
  PRIMARY KEY
 (ID_SWIFT)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_221_ORDENES_SWIFT 
-- 
ALTER TABLE ADM_INFI.INFI_TB_221_ORDENES_SWIFT ADD (
  CONSTRAINT FK_221_204_TOMA_ORDEN 
 FOREIGN KEY (ID_ORDEN_TOMA_ORDEN) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));

ALTER TABLE ADM_INFI.INFI_TB_221_ORDENES_SWIFT ADD (
  CONSTRAINT FK_221_204_ORDEN_RELAC 
 FOREIGN KEY (ID_ORDEN_RELACIONADA) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));

ALTER TABLE ADM_INFI.INFI_TB_221_ORDENES_SWIFT ADD (
  CONSTRAINT FK_221_207 
 FOREIGN KEY (ID_ORDEN_RELACIONADA) 
 REFERENCES ADM_INFI.INFI_TB_207_ORDENES_OPERACION (ORDENE_OPERACION_ID));


