--
-- INFI_TB_043_COM_CLIENTE  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_043_COM_CLIENTE
(
  COMISION_ID  NUMBER(7)                        NOT NULL,
  CLIENT_ID    NUMBER(8)                        NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- INFI_TB_043_COM_CLIENTE  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_043_COM_CLIENTE FOR ADM_INFI.INFI_TB_043_COM_CLIENTE;

GRANT DELETE ON  ADM_INFI.INFI_TB_043_COM_CLIENTE TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_043_COM_CLIENTE TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_043_COM_CLIENTE TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_043_COM_CLIENTE TO USU_INFI;

