--
-- INFI_TB_902_REGLA_VALIDACION  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_902_REGLA_VALIDACION
(
  REGLA_VALIDACION_ID  NUMBER(3)                NOT NULL,
  TIPO_PERSONA         VARCHAR2(1 BYTE)         NOT NULL,
  REGLA_TIPO           VARCHAR2(20 BYTE)        NOT NULL,
  REGLA_DESCRIPCION    VARCHAR2(100 BYTE)       NOT NULL,
  REGLA_PERIOCIDAD     VARCHAR2(7 BYTE),
  REGLA_VALOR          VARCHAR2(25 BYTE)        NOT NULL,
  REGLA_MENSAJE        VARCHAR2(100 BYTE)       NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ADM_INFI.INFI_TB_902_REGLA_VALIDACION.REGLA_VALIDACION_ID IS 'Id de validación de regla';

COMMENT ON COLUMN ADM_INFI.INFI_TB_902_REGLA_VALIDACION.TIPO_PERSONA IS 'Tipo de persona (V,E,J,etc)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_902_REGLA_VALIDACION.REGLA_TIPO IS 'Tipo de la regla VALIDACION_CLIENTE,COMPRA,ADQUISICION_DIVISAS';

COMMENT ON COLUMN ADM_INFI.INFI_TB_902_REGLA_VALIDACION.REGLA_DESCRIPCION IS 'Descripción larga';

COMMENT ON COLUMN ADM_INFI.INFI_TB_902_REGLA_VALIDACION.REGLA_PERIOCIDAD IS 'Periocidad que se debe validar. Existen varias posibles, DIARIO,MENSUAL,ANUAL';

COMMENT ON COLUMN ADM_INFI.INFI_TB_902_REGLA_VALIDACION.REGLA_VALOR IS 'Valor usada para la validación';

COMMENT ON COLUMN ADM_INFI.INFI_TB_902_REGLA_VALIDACION.REGLA_MENSAJE IS 'Mensaje de error que debe mostrarse al usuario si la validación no se cumple';


--
-- INFI_TB_902_REGLA_VALIDACION  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_902_REGLA_VALIDACION FOR ADM_INFI.INFI_TB_902_REGLA_VALIDACION;

GRANT DELETE ON  ADM_INFI.INFI_TB_902_REGLA_VALIDACION TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_902_REGLA_VALIDACION TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_902_REGLA_VALIDACION TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_902_REGLA_VALIDACION TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_902_REGLA_VALIDACION 
-- 
ALTER TABLE ADM_INFI.INFI_TB_902_REGLA_VALIDACION ADD (
  PRIMARY KEY
 (REGLA_VALIDACION_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


