--
-- INFI_TB_852_MOV_CONTABLE  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_852_MOV_CONTABLE
(
  MOVIMIENTO_ID   NUMBER(10)                    NOT NULL,
  EVENTO_ID       NUMBER(10)                    NOT NULL,
  DESCRIPCION     VARCHAR2(100 CHAR),
  TIPO            VARCHAR2(4 BYTE),
  CUENTA_ID       NUMBER(10)                    NOT NULL,
  DEF_DINAMIC_ID  NUMBER
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_852_MOV_CONTABLE IS 'Tabla que contiene los movimientos (transacciones) asociadas a un evento contable';

COMMENT ON COLUMN ADM_INFI.INFI_TB_852_MOV_CONTABLE.EVENTO_ID IS 'Id de evento contable asociado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_852_MOV_CONTABLE.DESCRIPCION IS 'Descripción del movimiento';

COMMENT ON COLUMN ADM_INFI.INFI_TB_852_MOV_CONTABLE.TIPO IS 'Tipo de movimiento (debito, credito)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_852_MOV_CONTABLE.CUENTA_ID IS 'Cuenta contable asociada';

COMMENT ON COLUMN ADM_INFI.INFI_TB_852_MOV_CONTABLE.MOVIMIENTO_ID IS 'Identificador de movimiento contable';

--
-- INFI_TB_852_MOV_CONTABLE_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.INFI_TB_852_MOV_CONTABLE_PK ON ADM_INFI.INFI_TB_852_MOV_CONTABLE
(MOVIMIENTO_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_852_MOV_CONTABLE 
-- 
ALTER TABLE ADM_INFI.INFI_TB_852_MOV_CONTABLE ADD (
  CONSTRAINT CK_852_MOVIMIENTO_ID
 CHECK (MOVIMIENTO_ID is NOT NULL));

ALTER TABLE ADM_INFI.INFI_TB_852_MOV_CONTABLE ADD (
  CONSTRAINT CK_852_EVENTO_ID
 CHECK (EVENTO_ID is NOT NULL));

ALTER TABLE ADM_INFI.INFI_TB_852_MOV_CONTABLE ADD (
  CONSTRAINT CK_852_CUENTA_ID
 CHECK (CUENTA_ID is NOT NULL));

ALTER TABLE ADM_INFI.INFI_TB_852_MOV_CONTABLE ADD (
  CONSTRAINT PK_852
 PRIMARY KEY
 (MOVIMIENTO_ID));


-- 
-- Foreign Key Constraints for Table INFI_TB_852_MOV_CONTABLE 
-- 
ALTER TABLE ADM_INFI.INFI_TB_852_MOV_CONTABLE ADD (
  CONSTRAINT FK_852_851 
 FOREIGN KEY (EVENTO_ID) 
 REFERENCES ADM_INFI.INFI_TB_851_EVENTO_CONTABLE (EVENTO_ID));

ALTER TABLE ADM_INFI.INFI_TB_852_MOV_CONTABLE ADD (
  CONSTRAINT FK_852_850 
 FOREIGN KEY (CUENTA_ID) 
 REFERENCES ADM_INFI.INFI_TB_850_CUENTA_CONTABLE (CUENTA_ID));


