--
-- INFI_TB_905_PAIS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_905_PAIS
(
  COD_PAIS   VARCHAR2(15 BYTE),
  DESC_PAIS  VARCHAR2(60 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- INFI_TB_905_PAIS_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.INFI_TB_905_PAIS_PK ON ADM_INFI.INFI_TB_905_PAIS
(COD_PAIS)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_905_PAIS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_905_PAIS FOR ADM_INFI.INFI_TB_905_PAIS;

GRANT DELETE ON  ADM_INFI.INFI_TB_905_PAIS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_905_PAIS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_905_PAIS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_905_PAIS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_905_PAIS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_905_PAIS ADD (
  CONSTRAINT INFI_TB_905_PAIS_PK
 PRIMARY KEY
 (COD_PAIS)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


