--
-- INFI_TB_121_TIT_PREC_RCMP_HIST  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST
(
  TITULO_ID                     VARCHAR2(25 BYTE) NOT NULL,
  MONEDA_ID                     VARCHAR2(3 BYTE) NOT NULL,
  TITULO_RANGO_INVERTIDO_DESDE  NUMBER(12)      NOT NULL,
  TITULO_RANGO_INVERTIDO_HASTA  NUMBER(12)      NOT NULL,
  TITULOS_PRECIO_POOL           NUMBER(9,6)     NOT NULL,
  TITULOS_PRECIO_RECOMPRA       NUMBER(9,6)     NOT NULL,
  FECHA_ACT                     DATE            NOT NULL,
  USUARIO_ID                    VARCHAR2(15 BYTE) NOT NULL,
  TITULOS_ID_REGISTRO           NUMBER(12)      NOT NULL,
  USUARIO_ID_APROBADOR          VARCHAR2(15 BYTE),
  FECHA_APROBACION              DATE,
  TIPO_PRODUCTO_ID              VARCHAR2(10 BYTE) NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST IS 'Tabla para especificar una pizarra de precios de recompra por montos invertidos';

COMMENT ON COLUMN ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST.MONEDA_ID IS 'Id de la moneda para el establecimiento de los montos';

COMMENT ON COLUMN ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST.TITULO_RANGO_INVERTIDO_DESDE IS 'Rango de inversion desde';

COMMENT ON COLUMN ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST.TITULO_RANGO_INVERTIDO_HASTA IS 'Rango de inversión hasta';

COMMENT ON COLUMN ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST.TITULOS_PRECIO_POOL IS 'Precio pool dado por tesoreria';

COMMENT ON COLUMN ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST.TITULOS_PRECIO_RECOMPRA IS 'Porcentaje de recompra';

COMMENT ON COLUMN ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST.FECHA_ACT IS 'Fecha de actualización';

COMMENT ON COLUMN ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST.USUARIO_ID IS 'Id del usuario que modifica el registro';

COMMENT ON COLUMN ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST.TITULOS_ID_REGISTRO IS 'Id único que identifica un registro';

COMMENT ON COLUMN ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST.TITULO_ID IS 'Id del título';

--
-- INFI_TB_121_TIT_PREC_RCMP_HIST  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_121_TIT_PREC_RCMP_HIST FOR ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST;

GRANT DELETE ON  ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_121_TIT_PREC_RCMP_HIST TO USU_INFI;

