--
-- INFI_TB_909_FILTRO_CTES_HIST  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST
(
  CLIENT_ID           NUMBER(8),
  TIPPER_ID           VARCHAR2(1 BYTE),
  CLIENT_CEDRIF       VARCHAR2(10 BYTE),
  CLIENT_NOMBRE       VARCHAR2(100 BYTE),
  FECHA               DATE,
  OBSERVACION         VARCHAR2(50 BYTE),
  USUARIO_REGISTRO    VARCHAR2(50 BYTE),
  ESTATUS             VARCHAR2(25 BYTE),
  ACCION              VARCHAR2(10 BYTE),
  TIPO_PRODUCTO_ID    VARCHAR2(10 BYTE),
  CICLO_EJECUCION_ID  NUMBER(7),
  ID_REGISTRO         NUMBER(10),
  USR_TERMINAL        VARCHAR2(50 BYTE),
  USUARIO_APROBACION  VARCHAR2(50 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST IS 'Tabla registra los clientes a excluir en la ADJUDICACIÓN/CRUCE  de solicitudes en INFI. Guarda las cargas de clientes para su aprobación y el histórico de los registros aprobados';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.CLIENT_ID IS 'Id de cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.TIPPER_ID IS 'Tipo de documento';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.CLIENT_CEDRIF IS 'Cedula de Identidad del Cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.CLIENT_NOMBRE IS 'Nombre del Cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.FECHA IS 'Fecha de Carga del Registro';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.OBSERVACION IS 'Observación asociada a la carga del registro';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.USUARIO_REGISTRO IS 'Usuario que cargó la información';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.ESTATUS IS 'Estatus de la carga ''INVALIDO'', ''APROBADO'', ''REGISTRADO'',''RECHAZADO''';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.ACCION IS 'Acción asociada a la carga realizada ';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.TIPO_PRODUCTO_ID IS 'Tipo de producto asociado a la carga de registros';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.CICLO_EJECUCION_ID IS 'Id de ciclo asociado a la carga de los registros';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.ID_REGISTRO IS 'Id de registro';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.USR_TERMINAL IS 'Ip del terminal desde donde se ejecuta la carga';

COMMENT ON COLUMN ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST.USUARIO_APROBACION IS 'Usuario que aprobó la carga de los registros';

--
-- INFI_TB_909_FILTRO_CTES_HIST  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_909_FILTRO_CTES_HIST FOR ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST;

GRANT DELETE ON  ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_909_FILTRO_CTES_HIST TO USU_INFI;

