--
-- INFI_TB_237_TASASDIVISAS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_237_TASASDIVISAS
(
  FECHA       DATE                              NOT NULL,
  MONEDA      VARCHAR2(3 CHAR)                  NOT NULL,
  TASAVENTA   NUMBER(19,10)                     NOT NULL,
  TASACOMPRA  NUMBER(19,10)                     NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ADM_INFI.INFI_TB_237_TASASDIVISAS.FECHA IS 'fecha Valor de la Tasa';

COMMENT ON COLUMN ADM_INFI.INFI_TB_237_TASASDIVISAS.MONEDA IS 'Moneda de la Tasa ISO';

COMMENT ON COLUMN ADM_INFI.INFI_TB_237_TASASDIVISAS.TASAVENTA IS 'Valor para la Venta BDV';

COMMENT ON COLUMN ADM_INFI.INFI_TB_237_TASASDIVISAS.TASACOMPRA IS 'Valor para la Compra BDV';

--
-- PK_237_FECHAMONEDA  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_237_FECHAMONEDA ON ADM_INFI.INFI_TB_237_TASASDIVISAS
(FECHA, MONEDA)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

GRANT DELETE ON  ADM_INFI.INFI_TB_237_TASASDIVISAS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_237_TASASDIVISAS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_237_TASASDIVISAS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_237_TASASDIVISAS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_237_TASASDIVISAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_237_TASASDIVISAS ADD (
  CONSTRAINT PK_237_FECHAMONEDA
 PRIMARY KEY
 (FECHA, MONEDA)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


