--
-- INFI_TB_853_RISTRA_CONTABLE  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_853_RISTRA_CONTABLE
(
  RISTRA_ID       NUMBER(10),
  MOVIMIENTO_ID   NUMBER(10)                    NOT NULL,
  TIPO            VARCHAR2(4 BYTE)              NOT NULL,
  MONTO           NUMBER(15,5)                  NOT NULL,
  ORDENE_ID       NUMBER(10)                    NOT NULL,
  FECHA_CREACION  DATE,
  FECHA_CONTABLE  DATE,
  REFERENCIA_1    VARCHAR2(12 BYTE),
  REFERENCIA_2    VARCHAR2(60 BYTE),
  TASA_CAMBIO     NUMBER(5,2),
  FECHA_ENVIO     DATE,
  CODIGO_DIVISA   VARCHAR2(5 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_853_RISTRA_CONTABLE IS 'Tabla que contiene la información de las ristras contables generadas en INFI';

COMMENT ON COLUMN ADM_INFI.INFI_TB_853_RISTRA_CONTABLE.RISTRA_ID IS 'Identificador de ristra';

COMMENT ON COLUMN ADM_INFI.INFI_TB_853_RISTRA_CONTABLE.MOVIMIENTO_ID IS 'Id de evento';

COMMENT ON COLUMN ADM_INFI.INFI_TB_853_RISTRA_CONTABLE.TIPO IS 'Tipo de movimiento (debito, credito)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_853_RISTRA_CONTABLE.MONTO IS 'Monto asociado al movimiento';

COMMENT ON COLUMN ADM_INFI.INFI_TB_853_RISTRA_CONTABLE.ORDENE_ID IS 'Id de orden asociado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_853_RISTRA_CONTABLE.FECHA_CREACION IS 'Fecha de creacion de la ristra';

COMMENT ON COLUMN ADM_INFI.INFI_TB_853_RISTRA_CONTABLE.FECHA_CONTABLE IS 'Fecha de contabilizacion de la ristra';

COMMENT ON COLUMN ADM_INFI.INFI_TB_853_RISTRA_CONTABLE.REFERENCIA_1 IS 'Referencia de Conciliacion SmartStream';

COMMENT ON COLUMN ADM_INFI.INFI_TB_853_RISTRA_CONTABLE.REFERENCIA_2 IS 'Referencias asociadas a la operacion (IBS,BCV). Las referencias deben registrarse con el orden indicado y separado por comas';

COMMENT ON COLUMN ADM_INFI.INFI_TB_853_RISTRA_CONTABLE.TASA_CAMBIO IS 'Tasa asociada al movimiento';

COMMENT ON COLUMN ADM_INFI.INFI_TB_853_RISTRA_CONTABLE.FECHA_ENVIO IS 'Fecha de envio de la ristra contable';

COMMENT ON COLUMN ADM_INFI.INFI_TB_853_RISTRA_CONTABLE.CODIGO_DIVISA IS 'Codigo de divisa en el cual se realizó la operación';

--
-- INFI_TB_853_RISTRA_CONTABLE_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.INFI_TB_853_RISTRA_CONTABLE_PK ON ADM_INFI.INFI_TB_853_RISTRA_CONTABLE
(RISTRA_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_853_RISTRA_CONTABLE 
-- 
ALTER TABLE ADM_INFI.INFI_TB_853_RISTRA_CONTABLE ADD (
  CONSTRAINT INFI_TB_853_RISTRA_CONTABLE_PK
 PRIMARY KEY
 (RISTRA_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_853_RISTRA_CONTABLE 
-- 
ALTER TABLE ADM_INFI.INFI_TB_853_RISTRA_CONTABLE ADD (
  CONSTRAINT FK_853_852 
 FOREIGN KEY (MOVIMIENTO_ID) 
 REFERENCES ADM_INFI.INFI_TB_852_MOV_CONTABLE (MOVIMIENTO_ID));

ALTER TABLE ADM_INFI.INFI_TB_853_RISTRA_CONTABLE ADD (
  CONSTRAINT FK_853_204 
 FOREIGN KEY (ORDENE_ID) 
 REFERENCES ADM_INFI.INFI_TB_204_ORDENES (ORDENE_ID));


