--
-- INFI_TB_026_TRANSACCION_CAMDOC  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC
(
  TRANSA_ID          VARCHAR2(25 BYTE)          NOT NULL,
  CAMPO_ID           NUMBER(4)                  NOT NULL,
  DESCRIPCION_CAMPO  VARCHAR2(50 BYTE)          NOT NULL,
  NOMBRE_CAMPO       VARCHAR2(30 BYTE)          NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC IS 'Campos que se pueden colocar en una plantilla de documento';

COMMENT ON COLUMN ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC.TRANSA_ID IS 'Id de la transacción';

COMMENT ON COLUMN ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC.CAMPO_ID IS 'Id del campo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC.DESCRIPCION_CAMPO IS 'Descripción del campo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC.NOMBRE_CAMPO IS 'Nombre para mostrar en la plantilla';

--
-- PK_026  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_026 ON ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC
(TRANSA_ID, CAMPO_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_026_TRANSACCION_CAMDOC  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_026_TRANSACCION_CAMDOC FOR ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC;

GRANT DELETE ON  ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_026_TRANSACCION_CAMDOC 
-- 
ALTER TABLE ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC ADD (
  CONSTRAINT PK_026
 PRIMARY KEY
 (TRANSA_ID, CAMPO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_026_TRANSACCION_CAMDOC 
-- 
ALTER TABLE ADM_INFI.INFI_TB_026_TRANSACCION_CAMDOC ADD (
  CONSTRAINT FK_026_012 
 FOREIGN KEY (TRANSA_ID) 
 REFERENCES ADM_INFI.INFI_TB_012_TRANSACCIONES (TRANSA_ID));


