--
-- INFI_TB_805_TRNFIN_TIPO  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_805_TRNFIN_TIPO
(
  TRNFIN_TIPO              VARCHAR2(3 BYTE)     NOT NULL,
  TRNFIN_TIPO_DESCRIPCION  VARCHAR2(20 BYTE)    NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- PK_805  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_805 ON ADM_INFI.INFI_TB_805_TRNFIN_TIPO
(TRNFIN_TIPO)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_805_TRNFIN_TIPO  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_805_TRNFIN_TIPO FOR ADM_INFI.INFI_TB_805_TRNFIN_TIPO;

GRANT DELETE ON  ADM_INFI.INFI_TB_805_TRNFIN_TIPO TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_805_TRNFIN_TIPO TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_805_TRNFIN_TIPO TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_805_TRNFIN_TIPO TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_805_TRNFIN_TIPO 
-- 
ALTER TABLE ADM_INFI.INFI_TB_805_TRNFIN_TIPO ADD (
  CONSTRAINT PK_805
 PRIMARY KEY
 (TRNFIN_TIPO)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


