--
-- INFI_TB_234_VC_DIVISAS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_234_VC_DIVISAS
(
  ID_OPER            NUMBER(13),
  ID_OC              NUMBER(13),
  OPERACION          VARCHAR2(6 BYTE),
  STATUS_OPER        VARCHAR2(1 BYTE),
  MTO_DIVISAS        NUMBER(13,2),
  MTO_BOLIVARES      NUMBER(15,2),
  TASA_CAMBIO        FLOAT(126),
  MTO_COMI           NUMBER(13,2),
  NACIONALIDAD       VARCHAR2(1 BYTE),
  NRO_CED_RIF        NUMBER(10),
  NOM_CLIEN          VARCHAR2(31 BYTE),
  CTA_CLIEN          VARCHAR2(20 BYTE),
  FECH_OPER          VARCHAR2(10 BYTE),
  CON_ESTADIS        VARCHAR2(3 BYTE),
  COD_OFI_ORI        VARCHAR2(4 BYTE),
  COD_DIVISAS        VARCHAR2(3 BYTE),
  EMAIL_CLIEN        VARCHAR2(40 BYTE),
  TEL_CLIEN          VARCHAR2(11 BYTE),
  STATUS_ENVIO       VARCHAR2(11 BYTE),
  OBSERVACION        VARCHAR2(200 BYTE),
  ID_BCV             VARCHAR2(25 BYTE),
  MTO_DIVISAS_TRANS  NUMBER(17,4)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.STATUS_OPER IS 'Tipo de Operacion en Moneda Extranjera ''O'' Original ''R'' Reverso';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.MTO_DIVISAS IS 'Monto de la operacion en divisa USD, EURO, etc';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.MTO_BOLIVARES IS 'Monto del contravalor de la operacion en divisa USD, EURO, etc';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.TASA_CAMBIO IS 'Tasa de Cambio del Monto de la operacion en divisa USD, EURO, etc';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.MTO_COMI IS 'Monto de la comisión de la operacion en divisa USD, EURO, etc';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.NACIONALIDAD IS 'Nacionalidad ''J'',''E'',''V''';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.NRO_CED_RIF IS 'Identificar de la Persona';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.NOM_CLIEN IS 'Nombre del Cliente dueño de la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.CTA_CLIEN IS 'Cuenta Origen de la Operacion de Compra o Venta';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.FECH_OPER IS 'Fecha Valor de la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.CON_ESTADIS IS 'Concepto estadistico de BCV donde ''100'' son estaciones de Servicios';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.COD_OFI_ORI IS 'Oficina donde se realiza la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.COD_DIVISAS IS 'Codigo ISO de la moneda de la Cuenta Origen';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.EMAIL_CLIEN IS 'Correo Electronico del Cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.TEL_CLIEN IS 'Telefono del Cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.STATUS_ENVIO IS 'Estatus de la notificacion BCV ''0'' enviado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.OBSERVACION IS 'Detalles de la notificación a BCV';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.ID_BCV IS 'Identificador de la notificacion en BCV';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.ID_OPER IS 'Numero identificador de INFI';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.OPERACION IS 'Tipo de Operacion Moneda Extranjera Cara Banco ''1203'' Compra ''5204'' Venta';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.MTO_DIVISAS_TRANS IS 'Monto en Dolares contrvalor de otras divisas Euros, Etc.';

COMMENT ON COLUMN ADM_INFI.INFI_TB_234_VC_DIVISAS.ID_OC IS 'Numero de Operacion de Cambio en Moneda Extranjera';

--
-- PK_234_VC_DIVISAS  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_234_VC_DIVISAS ON ADM_INFI.INFI_TB_234_VC_DIVISAS
(ID_OC, OPERACION)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- NCED_234_VC_DIVISAS  (Index) 
--
CREATE INDEX ADM_INFI.NCED_234_VC_DIVISAS ON ADM_INFI.INFI_TB_234_VC_DIVISAS
(NACIONALIDAD, NRO_CED_RIF)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_234_VC_DIVISAS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_234_VC_DIVISAS FOR ADM_INFI.INFI_TB_234_VC_DIVISAS;

GRANT DELETE ON  ADM_INFI.INFI_TB_234_VC_DIVISAS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_234_VC_DIVISAS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_234_VC_DIVISAS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_234_VC_DIVISAS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_234_VC_DIVISAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_234_VC_DIVISAS ADD (
  CONSTRAINT PK_234_VC_DIVISAS
 PRIMARY KEY
 (ID_OC, OPERACION)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


