--
-- INFI_TB_908_ARCHIVO_RETENCION  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION
(
  ID_REGISTRO       NUMBER(15)                  NOT NULL,
  ID_CICLO          NUMBER(7),
  FECHA_PROCESO     DATE,
  CODIGO_OPERACION  VARCHAR2(10 BYTE),
  NUMERO_RETENCION  VARCHAR2(10 BYTE),
  CUENTA            VARCHAR2(30 BYTE),
  FECHA_RETENCION   DATE,
  MONTO             NUMBER(15,5),
  PROCESADO         NUMBER(1)                   DEFAULT 0,
  ESTADO_RETENCION  NUMBER(1)                   DEFAULT 0
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION IS 'Tabla destinada al registro del archivo de retenciones enviado por altair, para la conciliacion de operaciones sin número de retención';

COMMENT ON COLUMN ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION.ID_CICLO IS 'Id de ciclo asociado al envío y recepción de archivos de conciliación de retenciones';

COMMENT ON COLUMN ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION.FECHA_PROCESO IS 'Fecha de procesamiento del archivo por parte de Altair Pasivos';

COMMENT ON COLUMN ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION.CODIGO_OPERACION IS 'Código de operación';

COMMENT ON COLUMN ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION.NUMERO_RETENCION IS 'Número de retención';

COMMENT ON COLUMN ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION.CUENTA IS 'Número de cuenta del cliente';

COMMENT ON COLUMN ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION.FECHA_RETENCION IS 'Fecha en la cual fue ejecutada la retención';

COMMENT ON COLUMN ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION.MONTO IS 'Monto de la operacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION.PROCESADO IS 'Registro procesado (1), registro no procesado (0)';

COMMENT ON COLUMN ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION.ID_REGISTRO IS 'Id de registro consecutivo';

--
-- INFI_TB_908_ARCHIVO_RETENCI_PK  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.INFI_TB_908_ARCHIVO_RETENCI_PK ON ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION
(ID_REGISTRO)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_INDEX_908_CUENTA_RET  (Index) 
--
CREATE INDEX ADM_INFI.INFI_INDEX_908_CUENTA_RET ON ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION
(CUENTA, NUMERO_RETENCION)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_INDEX_908_MONTO  (Index) 
--
CREATE INDEX ADM_INFI.INFI_INDEX_908_MONTO ON ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION
(MONTO)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_908_ARCHIVO_RETENCION  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_908_ARCHIVO_RETENCION FOR ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION;

GRANT DELETE ON  ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_908_ARCHIVO_RETENCION 
-- 
ALTER TABLE ADM_INFI.INFI_TB_908_ARCHIVO_RETENCION ADD (
  CONSTRAINT INFI_TB_908_ARCHIVO_RETENCI_PK
 PRIMARY KEY
 (ID_REGISTRO)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


