--
-- INFI_TB_216_MENSAJE_OPICS_DET  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET
(
  OPICS_ID     NUMBER(8)                        NOT NULL,
  MENSAJE_NRO  NUMBER(8)                        NOT NULL,
  CLAVE_CAMPO  VARCHAR2(50 BYTE)                NOT NULL,
  VALOR_CAMPO  VARCHAR2(100 BYTE)               NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET IS 'Contiene el detalle del mensaje de opics. Sólo los campos que contengan valor diferente a "" serán almacenados';

COMMENT ON COLUMN ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET.OPICS_ID IS 'Id del proceso opics ';

COMMENT ON COLUMN ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET.MENSAJE_NRO IS 'Número de mensaje';

COMMENT ON COLUMN ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET.CLAVE_CAMPO IS 'Clave o título del campo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET.VALOR_CAMPO IS 'Valor del campo';

--
-- INDX_216_OPICS_ID  (Index) 
--
CREATE INDEX ADM_INFI.INDX_216_OPICS_ID ON ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET
(OPICS_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_216_MENSAJE_OPICS_DET  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_216_MENSAJE_OPICS_DET FOR ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET;

GRANT DELETE ON  ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET TO USU_INFI;

-- 
-- Foreign Key Constraints for Table INFI_TB_216_MENSAJE_OPICS_DET 
-- 
ALTER TABLE ADM_INFI.INFI_TB_216_MENSAJE_OPICS_DET ADD (
  CONSTRAINT FK_216_215 
 FOREIGN KEY (OPICS_ID) 
 REFERENCES ADM_INFI.INFI_TB_215_MENSAJE_OPICS (OPICS_ID)
    ON DELETE CASCADE);


