--
-- INFI_TB_050_CONCEPTOS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_050_CONCEPTOS
(
  CODIGO_ID           NUMBER(5)                 NOT NULL,
  CONCEPTO            VARCHAR2(100 BYTE),
  NUMERAL             VARCHAR2(40 BYTE),
  ESTATUS             NUMBER(1)                 DEFAULT 1                     NOT NULL,
  CANAL_ID            NUMBER(8)                 DEFAULT 1                     NOT NULL,
  FECHA_MODIFICACION  DATE                      DEFAULT SYSDATE               NOT NULL,
  ID_PRODUCTO         NUMBER(6)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_050_CONCEPTOS IS 'Tablas de conceptos para reportar la información diaria relativa a las operaciones realizadas a través del SITME';

COMMENT ON COLUMN ADM_INFI.INFI_TB_050_CONCEPTOS.ESTATUS IS 'Monto estatus';

COMMENT ON COLUMN ADM_INFI.INFI_TB_050_CONCEPTOS.CANAL_ID IS 'Id del canal';

COMMENT ON COLUMN ADM_INFI.INFI_TB_050_CONCEPTOS.FECHA_MODIFICACION IS 'Fecha de modificacion';

COMMENT ON COLUMN ADM_INFI.INFI_TB_050_CONCEPTOS.ID_PRODUCTO IS 'Id del producto';


--
-- INFI_TB_050_CONCEPTOS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_050_CONCEPTOS FOR ADM_INFI.INFI_TB_050_CONCEPTOS;

GRANT DELETE ON  ADM_INFI.INFI_TB_050_CONCEPTOS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_050_CONCEPTOS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_050_CONCEPTOS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_050_CONCEPTOS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_050_CONCEPTOS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_050_CONCEPTOS ADD (
  PRIMARY KEY
 (CODIGO_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_050_CONCEPTOS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_050_CONCEPTOS ADD (
  CONSTRAINT FK_050_904_CANAL_ID 
 FOREIGN KEY (CANAL_ID) 
 REFERENCES ADM_INFI.INFI_TB_904_CANAL (CANAL_ID));


