--
-- INFI_TB_219_MENSAJE_DETALLE  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_219_MENSAJE_DETALLE
(
  MENSAJE_ID          NUMBER(8)                 NOT NULL,
  MENSAJE_ID_DETALLE  NUMBER(10)                NOT NULL,
  CLAVE_CAMPO         VARCHAR2(50 BYTE)         NOT NULL,
  VALOR_CAMPO         VARCHAR2(100 BYTE)        NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_219_MENSAJE_DETALLE IS 'Contiene el detalle del mensaje. Sólo los campos que contengan valor diferente a "" serán almacenados';

COMMENT ON COLUMN ADM_INFI.INFI_TB_219_MENSAJE_DETALLE.MENSAJE_ID IS 'Id del mensaje generado';

COMMENT ON COLUMN ADM_INFI.INFI_TB_219_MENSAJE_DETALLE.MENSAJE_ID_DETALLE IS 'Id del mensaje detalle';

COMMENT ON COLUMN ADM_INFI.INFI_TB_219_MENSAJE_DETALLE.CLAVE_CAMPO IS 'Clave o título del campo';

COMMENT ON COLUMN ADM_INFI.INFI_TB_219_MENSAJE_DETALLE.VALOR_CAMPO IS 'Valor del campo';

--
-- PK_219  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_219 ON ADM_INFI.INFI_TB_219_MENSAJE_DETALLE
(MENSAJE_ID, MENSAJE_ID_DETALLE)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INX_219_MENSAJE_ID  (Index) 
--
CREATE INDEX ADM_INFI.INX_219_MENSAJE_ID ON ADM_INFI.INFI_TB_219_MENSAJE_DETALLE
(MENSAJE_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_219_MENSAJE_DETALLE  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_219_MENSAJE_DETALLE FOR ADM_INFI.INFI_TB_219_MENSAJE_DETALLE;

GRANT DELETE ON  ADM_INFI.INFI_TB_219_MENSAJE_DETALLE TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_219_MENSAJE_DETALLE TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_219_MENSAJE_DETALLE TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_219_MENSAJE_DETALLE TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_219_MENSAJE_DETALLE 
-- 
ALTER TABLE ADM_INFI.INFI_TB_219_MENSAJE_DETALLE ADD (
  CONSTRAINT PK_219
 PRIMARY KEY
 (MENSAJE_ID, MENSAJE_ID_DETALLE)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


-- 
-- Foreign Key Constraints for Table INFI_TB_219_MENSAJE_DETALLE 
-- 
ALTER TABLE ADM_INFI.INFI_TB_219_MENSAJE_DETALLE ADD (
  CONSTRAINT FK_219_218 
 FOREIGN KEY (MENSAJE_ID) 
 REFERENCES ADM_INFI.INFI_TB_218_MENSAJE (MENSAJE_ID)
    ON DELETE CASCADE);


