--
-- INFI_TB_007_CTAS_BIC_BANCO  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO
(
  ID_CUENTA              NUMBER(6)              NOT NULL,
  COD_BIC_BANCO          VARCHAR2(20 BYTE)      NOT NULL,
  NU_CUENTA              VARCHAR2(30 BYTE)      NOT NULL,
  DS_BANCO               VARCHAR2(50 BYTE)      NOT NULL,
  FE_ULT_ACTUALIZACION   DATE,
  USR_ULT_ACTUALIZACION  VARCHAR2(25 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO IS 'Repositorio de cuentas donde se tienen alojados los fondos para el pago a los clientes en moneda extranjera';

COMMENT ON COLUMN ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO.ID_CUENTA IS 'Consecutivo de Id de cuenta';

COMMENT ON COLUMN ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO.COD_BIC_BANCO IS 'Código BIC del banco donde se sacarán los fondos para el pago a clientes';

COMMENT ON COLUMN ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO.NU_CUENTA IS 'Número de cuenta donde se poseen los fondos';

COMMENT ON COLUMN ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO.DS_BANCO IS 'Descripción del Banco';

COMMENT ON COLUMN ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO.FE_ULT_ACTUALIZACION IS 'Fecha de última actualización';

COMMENT ON COLUMN ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO.USR_ULT_ACTUALIZACION IS 'Usuario de última actualización';

--
-- PK_007  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_007 ON ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO
(ID_CUENTA)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_007_CTAS_BIC_BANCO  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_007_CTAS_BIC_BANCO FOR ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO;

GRANT DELETE ON  ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_007_CTAS_BIC_BANCO 
-- 
ALTER TABLE ADM_INFI.INFI_TB_007_CTAS_BIC_BANCO ADD (
  CONSTRAINT PK_007
 PRIMARY KEY
 (ID_CUENTA)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


