--
-- INFI_TB_205_ORDENES_CAMP_DIN  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_205_ORDENES_CAMP_DIN
(
  ORDENE_ID    NUMBER(10)                       NOT NULL,
  CAMPO_ID     NUMBER(4)                        NOT NULL,
  CAMPO_VALOR  VARCHAR2(500 BYTE)               NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ADM_INFI.INFI_TB_205_ORDENES_CAMP_DIN.ORDENE_ID IS 'Id de la orden';

COMMENT ON COLUMN ADM_INFI.INFI_TB_205_ORDENES_CAMP_DIN.CAMPO_ID IS 'Id del campo dinámico';

COMMENT ON COLUMN ADM_INFI.INFI_TB_205_ORDENES_CAMP_DIN.CAMPO_VALOR IS 'Valor del campo';

--
-- IDX_ORDENE_ID  (Index) 
--
CREATE INDEX ADM_INFI.IDX_ORDENE_ID ON ADM_INFI.INFI_TB_205_ORDENES_CAMP_DIN
(ORDENE_ID)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- IDX_CAMPO_ID  (Index) 
--
CREATE INDEX ADM_INFI.IDX_CAMPO_ID ON ADM_INFI.INFI_TB_205_ORDENES_CAMP_DIN
(CAMPO_ID)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--
-- INFI_TB_205_ORDENES_CAMP_DIN  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_205_ORDENES_CAMP_DIN FOR ADM_INFI.INFI_TB_205_ORDENES_CAMP_DIN;

GRANT DELETE ON  ADM_INFI.INFI_TB_205_ORDENES_CAMP_DIN TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_205_ORDENES_CAMP_DIN TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_205_ORDENES_CAMP_DIN TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_205_ORDENES_CAMP_DIN TO USU_INFI;

