--
-- INFI_TB_809_TIPO_CARTAS  (Table) 
--
CREATE TABLE ADM_INFI.INFI_TB_809_TIPO_CARTAS
(
  TIPCAR_ID           NUMBER(2)                 NOT NULL,
  TIPCAR_NOMBRE       VARCHAR2(25 BYTE)         NOT NULL,
  TIPCAR_DESCRIPCION  VARCHAR2(50 BYTE)         NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--
-- PK_809  (Index) 
--
CREATE UNIQUE INDEX ADM_INFI.PK_809 ON ADM_INFI.INFI_TB_809_TIPO_CARTAS
(TIPCAR_ID)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 4 INSTANCES 1 );

--
-- INFI_TB_809_TIPO_CARTAS  (Synonym) 
--
CREATE PUBLIC SYNONYM INFI_TB_809_TIPO_CARTAS FOR ADM_INFI.INFI_TB_809_TIPO_CARTAS;

GRANT DELETE ON  ADM_INFI.INFI_TB_809_TIPO_CARTAS TO USU_INFI;

GRANT INSERT ON  ADM_INFI.INFI_TB_809_TIPO_CARTAS TO USU_INFI;

GRANT SELECT ON  ADM_INFI.INFI_TB_809_TIPO_CARTAS TO USU_INFI;

GRANT UPDATE ON  ADM_INFI.INFI_TB_809_TIPO_CARTAS TO USU_INFI;

-- 
-- Non Foreign Key Constraints for Table INFI_TB_809_TIPO_CARTAS 
-- 
ALTER TABLE ADM_INFI.INFI_TB_809_TIPO_CARTAS ADD (
  CONSTRAINT PK_809
 PRIMARY KEY
 (TIPCAR_ID)
    USING INDEX 
    TABLESPACE DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


